### ISSUE TITLE
On larger grids, header displayed incorrectly

### ISSUE THREAD

**Issue by Arbalets** [NonFactors/MVC5.Grid#10]
On larger grid when sorting and filtering is enabled the header is displayed incorrectly.
For example I have something like this:

![image](https://cloud.githubusercontent.com/assets/4578695/9408936/4bcc1d9a-481f-11e5-9ef8-6afc68281b53.png)

I'm not a css expert, but it seems to be caused by .mvc-grid-sort > display: inline-block. When disabling display: inline-block, it displays correctly:

![image](https://cloud.githubusercontent.com/assets/4578695/9408977/8aa0cf20-481f-11e5-9756-9a1e7d5cd336.png)

**Comment by Muchiachio** [comment]
Ye, I kind of knew about this, but didn't knew how to solve it.
So I always overrode it depending on the project.
I will give it a try again.

**Comment by Runy89** [comment]
What exactly is the problem after removing inline-block?

**Comment by Muchiachio** [comment]
I wanted to keep the space taken by the sort arrow in place, because removing it results in grid columns changing their width after sorting (because header needs more space for added sort arrow). Of course it would change it's width one way or another on tables with long data, but it works on shorter tables.

**Comment by Muchiachio** [comment]
I actually found a solution, but it requires a breaking change in grid header declaration so I'm moving this together with all the other breaking changes to the v3.0.0 milestone. For now you should override mvc grid styling as it is necessary for you.

**Comment by Arbalets** [comment]
Thanks, looking forward to v3.0
