### ISSUE TITLE
Mobile Responsive Design of Grid

### ISSUE THREAD

**Issue by mkchmiel** [NonFactors/MVC5.Grid#100]
Hi Muchiachio,

Thank you for your help on the Footer feature, been able to implement it and it looks pretty.
Just curious if there is something in place for mobile design or any suggestions how I would go about it?

**Comment by Muchiachio** [comment]
I'm not an expert on css, but it should be achievable with css, probably.
For example in our projects we just rewrote `_Grid.cshtml` partial to use bootstrap's grid model and it was fine for our use case, maybe something similar could work for you too if css approach isn't feasible.

**Comment by guidozanon** [comment]
Hi @mkchmiel I resolve the responsive desing adding a custom class "mobile-hide" on columns that I will like to hide on mobile views.

On stylesheet add media for mobile devices and mobile-hide should set `display:none;`

You can add also diferent classes for diferent devices... mobile-hide, tablet-hide, etc

**Comment by mkchmiel** [comment]
Those are both great suggestions, thanks you both for your help. I should be able to sneak in some BootStrap stuff while I am at it.

**Comment by mkchmiel** [comment]
@Muchiachio could you provide an example of how you are using the boot strap grid?
Assuming its something along the lines of this example:
https://v4-alpha.getbootstrap.com/content/tables/

**Comment by Muchiachio** [comment]
No, it's https://v4-alpha.getbootstrap.com/layout/grid/, we are resizing grid content based on the size of the view port.

**Comment by mkchmiel** [comment]
Thanks for the help @Muchiachio, as always thanks for the quick response.
