### ISSUE TITLE
Html .Grid() in _IndexGrid partial view doesn't recognise in ASP NET MVC Area

### ISSUE THREAD

**Issue by keremburak** [NonFactors/MVC5.Grid#101]
Hi,

I use the MVC 5 Grid in a project. I use ASP NET MVC Area structure. When I try to use Html.Grid extension method in partial view of one of MVC areas. System doesn't recognise this extension method.

Without area there is no problem. I have a BaseViewPage inherited from WebViewPage class and I added namespace for MVC Grid into webconfig files in both area and root mvc project. 
In web.config files;

` <pages pageBaseType="ST.Model.Security.BaseViewPage">
      <namespaces>
        <add namespace="System.Web.Mvc" />
        <add namespace="System.Web.Mvc.Ajax" />
        <add namespace="System.Web.Mvc.Html" />
        <add namespace="System.Web.Routing" />
        <add namespace="System.Web.Optimization" />
        <add namespace="NonFactors.Mvc.Grid" />
      </namespaces>
    </pages>`

How can I introduce / use MVC 5 Grid extension method of Html.Grid in my Area structure_

Thanks in advance

**Comment by Muchiachio** [comment]
It doesn't work with default mvc application or in your current project?

**Comment by keremburak** [comment]
No, it doesn't. 

I used this MVC Grid with MVC 5 in another project. It works perfect.  But, if I used it in MVC Area views, it doesn't work. It works normal MVC project without Area structure. 

Is there any limitations with ASP NET MVC 5 Area structure?

**Comment by Muchiachio** [comment]
No, I use it with areas without any problems, could you share a repro?

**Comment by keremburak** [comment]
I tried to see what happened in the code on another PC. It didn't give any error. SO, I pulled the code from repository, it seems that there is no problem. It is weird. Now it works on both PC. Case can be closed. Thanks.

**Comment by wstaelens** [comment]
@Muchiachio  how do you get it working in an area? any example? the ajaxgrid loads but css of pager is completely wrong.

**Comment by Muchiachio** [comment]
It shouldn't matter if you are using grid in an area or not, maybe you are including grid css in a static url instead of using `Url.Content` or other url building functions?

**Comment by wstaelens** [comment]
The problem was a route conflicting with the css bundles! :-)
