### ISSUE TITLE
Master - Details Editing / Parent Child

### ISSUE THREAD

**Issue by weedkiller** [NonFactors/MVC5.Grid#102]
Hello, how can we 

1. Link 2 grids, for e.g. `CustomerGrid `& `OrdersGrid`
2. How can we **allow CRUD edits in both grids** so that the edits are posted to their own tables

**Comment by Muchiachio** [comment]
1. Render two grids (details one has to be ajax one), and use rowClicked event on master grid to reload the details one.
2. This can be done with your own javascript binding.

**Comment by weedkiller** [comment]
I like the backend view syntax and the simplicity of the auto render form the view. To extend that...

- [ ] Any chance we can get functionality to load both grids from MVC5.Grid by specifying the FK key that links the grid.
- [ ] Also, how can we perform CRUD, are these read only grids?

**Comment by Muchiachio** [comment]
1. Nothing planned as it's more flexible to do it via `rowClicked` event, introducing FK would still require some kind of event binding like row click, focus or other kind select of seelction. And as with other "automated" things other people will pop out wanting to somehow disable it or change it to meet their requirements, which in turn would introduce even more configuration.
2. CRUD has to be performed by hand, I don't think that CRUD is a responsibility of the grid.
