### ISSUE TITLE
Get grid data

### ISSUE THREAD

**Issue by agromenawer** [NonFactors/MVC5.Grid#105]
Hello, I have master-detail grids and I want the detail of the first row of the master to be loaded. How can I access the data in the first row to load the detail? It would do what I do with the rowclicked but start. Sorry for my English, is the translator of Spanish-English google.

**Comment by Muchiachio** [comment]
You can bind `rowClicked` event on the master grid and use the data parameter for your needs.

**Comment by agromenawer** [comment]
Thanks, what I want is that when loading the page, loads the detail of row one of the master grid without any click.

**Comment by Muchiachio** [comment]
Just pass the data of the first row as details grid parameter, or filter the data before initializing details grid.

**Comment by agromenawer** [comment]
Can you give me an example of how to get the data from the first row?

**Comment by Muchiachio** [comment]
Probably `Model.First().Property`.

**Comment by agromenawer** [comment]
Ahhh ok, thanks.

**Comment by agromenawer** [comment]
Sorry, Muchiacho, `Model.First()` works fine, but when I sort by a column it get data the first row of the Model but not the first row of the grid.

**Comment by Muchiachio** [comment]
Hmm, you could assign the grid to a variable and use its `Rows`.
```C#
var html = Html.Grid(Model).Build(...);
var firstRow = html.Grid.Rows.FirstOrDefault().Model.Property; // careful for nulls

@(html) // render the grid
```

**Comment by agromenawer** [comment]
Wowww, works fine. Thanks, Muchiachio.
