### ISSUE TITLE
bootstrap modal popup when click  html acnhor/link element on grid row?

### ISSUE THREAD

**Issue by keremburak** [NonFactors/MVC5.Grid#107]
Hi Muchiachio,

I use your grid in one of my project, It is a nice grid. I want to open a Bootstrap Modal popup when I click a link on a row (I use normal anchor element \ not Html.ActionLink on that row). 

Is there a way to open a Bootstrap modal popup when I click like this link option ?

Thanks in advance

Kerem

**Comment by Muchiachio** [comment]
Adding `data-toggle="modal" data-target="#myModal"` to your anchor attributes should be enough if you have correctly installed bootstrap in your application.
