### ISSUE TITLE
Row select and row clicked event not working?

### ISSUE THREAD

**Issue by MrNorth35** [NonFactors/MVC5.Grid#108]
Thank you for a really nice grid component.

We have started working with this along with bootstrap 3 and your helper @Html.AjaxGrid and everything is working nicely, but we have two issues that are unresolved.

1) In your example mvc-grid.azurewebsites.net/Javascript/RowClicked there is an effect in the grid that marks a row as "selected". How is this accomplished? We have  used the exact same razor configuration and javascript but when we click a row, no effect is visible. Is it a bootstrap issue?  Or what have we missed?

2) When binding the  rowClicked event as in your example, the "data" structure is undefined. In your example, there is a json object with data. Any idea why we can't get the data like that?

Also, it would be nice with an example of how to edit, delete rows. We plan to use the row double click event along with a bootstrap custom modal to edit row values. Also, we would like to add a delete button on each row that call by ajax a controller action that deletes a row.

Best regards

**Comment by Muchiachio** [comment]
1. Selected is achieved by `$(row).toggleClass('selected');`
2. Could you share a small repro of that, because I can't reproduce that kind of behavior.

As for edit/delete rows you will have to use your own javascript event bindings to do that.

**Comment by MrNorth35** [comment]
Hi and thank your for such a quick reply.

I have added this line of code $(row).toggleClass('selected'); to the rowClicked event and can confirm that the class="selected" is added. However, this happens on every row that I click on, I also need to perform the toggleClass on the previous row that was selected, so there are not multiple rows visually selected. Also, I guess we have to write custom css for the "selected" class on the <tr>  to give it some kind of visual appearance., since by default it looks just the same as a row that doesn't have the selected class. 

As for #2, I can confirm that it is working in Chrome (F12->Console). In IE11 it is just blank, no clue why.

Thank you for a really nice component!

**Comment by Muchiachio** [comment]
Does it also happen in row clicked example (maybe example is outdated)?
If it works there, you can download and see the sources, maybe you are doing something differently.

**Comment by MrNorth35** [comment]
Thank you for the answer. The example seems to be working correctly. But when running the exact same code on my dev environment with bootstrap style, the rows are selected but are not unselected when I click another row. If you can, can you verify that the examples are working as the production code? The behaviour I get corresponts to "multi select" where u click multiple rows and get multiple rows selected. This is nice in some ways, but not what we are looking for here.

**Comment by Muchiachio** [comment]
Selection is controller by you, just like browser's `click` event, `rowclicked` get's called on every grid row click, everything else is up to the developer.

If you want single selection you will have to unselected other rows and select a new one, I usually do
```JS
$(row).addClass('selected').siblings().removeClass('selected');
```

**Comment by MrNorth35** [comment]
Thank you, I think I have a better understanding now on how to get things done with this grid! Problem solved.
