### ISSUE TITLE
Bug filter popup location on pages that require horizontal Scrolling  

### ISSUE THREAD

**Issue by lukehammer** [NonFactors/MVC5.Grid#109]
First Thank you for this Toolset. 

I'm using the grid on one of my projects.  and the grid width is so wide it requires horizontal scrolling to view all the data. Normally the grid width is about 3x  to 4x the width of a standard monitor. 

 When scrolled all the way to the right side of the screen. Selecting a filter button does not cause a Popup window near the selected Filter button which was selected.  

Instead, it causes the popup window to be displayed off-screen to the left.

**Comment by Muchiachio** [comment]
Could you share a repro for this? Because I'm suspecting that your page styling is getting in the way of popup positioning or I'm not testing it on small enough screen, because this is what I get now
![image](https://user-images.githubusercontent.com/6647444/33512844-63aaab46-d73f-11e7-94e2-48305f06951d.png)
for it to get out of screen you would need a sub 200 pixel screen to not fit from left to right.
Your fixed version pushes the whole page to the right, to make space for the popup, I don't think that users would want to open the pop up to additionally scroll the whole page to the right to actually see it
![image](https://user-images.githubusercontent.com/6647444/33512854-9030897e-d73f-11e7-97b6-c5ff30e8c05c.png)
![image](https://user-images.githubusercontent.com/6647444/33512856-a150a6f8-d73f-11e7-90da-96a5cd2320f6.png)

**Comment by lukehammer** [comment]
What is happening to me I just realized is that my rows are breakout side of the parent object of 
`<table` class="table` mvc-grid-table"></table>

I have created a demo project demonstrating this [https://github.com/lukehammer/NonFactorsTesting](url)

If I filter on Column 26  the arrow shows in the correct location but the popup shows near Column 13 off the screen to the left. 

I agree with you **users should not have to scroll after clicking a popup**. and although my changes fix my use case it would have an undesirable effect as you described.

**Comment by Muchiachio** [comment]
Well this can be fixed too, just need to use document width instead of window one as it only covers the body width. I will patch it tomorrow.

**Comment by lukehammer** [comment]
Thank you very much. 

my testing i made that switch 



line    201          
old      var winWidth = $(window).width();
new     var winWidth = $(document).width();

however this is still squezzing the popup box when selecting filtering pass body width.

![capture](https://user-images.githubusercontent.com/8842287/33572391-aaf87574-d8e7-11e7-985d-ba69d75e823d.JPG)

again thank you for the help i will remove pull request

**Comment by Muchiachio** [comment]
Yes, it still needs width and some fiddling with arrow positioning.
```JS
setFilterPosition: function (column, popup) {
    var filter = column.header.find('.mvc-grid-filter');
    var documentWidth = $(document).width();
    var arrow = popup.find('.popup-arrow');
    var filterLeft = filter.offset().left;
    var filterTop = filter.offset().top;
    var filterHeight = filter.height();
    var popupWidth = popup.width();

    var popupTop = filterTop + filterHeight / 2 + 14;
    var popupLeft = filterLeft - 8;
    var arrowLeft = 15;

    if (filterLeft + popupWidth + 5 > documentWidth) {
        popupLeft = documentWidth - popupWidth - 5;
        arrowLeft = filterLeft - popupLeft + 7;
    }

    arrow.css('left', arrowLeft + 'px');
    popup.css('left', popupLeft + 'px');
    popup.css('top', popupTop + 'px');
}
```
```CSS
.mvc-grid-popup {
    width: 200px;
}
```

**Comment by junrikson** [comment]
Hi there, how you make a horizontal scrollbar? I have a table with so many columns, but the horizontal scrollbar didn't appears

**Comment by Muchiachio** [comment]
What do you mean by doesn't appear? Columns are just hidden on the right side?
Maybe you have your grid inside a `overflow-x: hidden` container?

**Comment by Muchiachio** [comment]
This looks like enough space, so browser didn't create scrollbar, you can also try using
`white-space: nowrap;` on your cells to avoid automatic column shrinkage to multi lines.

**Comment by junrikson** [comment]
Thank you, you got it right. `nowrap` made it scroll appear. 👍
