### ISSUE TITLE
How to add checkbox and routevalues

### ISSUE THREAD

**Issue by dragonsky18** [NonFactors/MVC5.Grid#11]
Hi , 
   I got some issues when I use mvc grid 

  1)  how to add checkbox in Mvc grid
  2)  how to add hidden columns?
  3)  how to specify route values when I use AddActionLink?(It's only use the keyattributes columns)

Thank you in advance 

Mark

**Comment by Muchiachio** [comment]
1) You can add any html to a grid column, but you need to specify that its not html encoded.
```C#
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "<input type='checkbox' />").Encoded(false);
    })
)
```

2) Simplest thing, would be to use your own hidden class.
```C#
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.SomeHiddenData).Css("hidden");
    })
)
```
```CSS
.hidden {
    display: none;
}
```
3) `AddActionLink` is just an extensions method in [MVC.Template](https://github.com/NonFactors/MVC5.Template/blob/develop/src/MvcTemplate.Components/Extensions/Html/MvcGrid/MvcGridExtensions.cs#L17), you can create your own extensions which accepts route values, or you can add action link from the view.
```C#
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "<a class='details-action' href='" + Url.Action("Details", new { id = 1, x = Model.X }) + "'><i class='fa fa-info'></i></a>").Encoded(false);
    })
)
```

And one more thing, I would really appreciate if next time, you could ask question in [web/docs](https://github.com/NonFactors/MVC5.Grid.Web) repository, so I could improve the examples base on your questions. Thanks for your understanding.

Muchiachio

**Comment by dragonsky18** [comment]
Thank you very very much.
