### ISSUE TITLE
Creating a Custom Filter For Custom Enum Type

### ISSUE THREAD

**Issue by lukehammer** [NonFactors/MVC5.Grid#111]
related to #77 Question 

First again thank you for your time and quick responce last time. 

I'm also attempting to Create a custom filter for my Enum Type.  I've been using example [here](http://mvc-grid.azurewebsites.net/Filter/Register)

my Goal is a similar experience to the custom Bool filter in the example,  but my Enums would have 3 to 7 unique entries. 

I have a [Test Project](https://github.com/lukehammer/NonFactorsTesting) up But here are the highlights.

Global.asax.cs  Added

` MvcGrid.Filters.Register(typeof(bool), "Is", typeof(InForeCastTypeEqual));`

model/GridFilters

    using NonFactors.Mvc.Grid;
    using System.Linq.Expressions;

    namespace NonFactorsTesting.Models
    {
    public class InForeCastTypeEqual : BaseGridFilter
    {
        public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, Expression.Constant(null));
        }
      }
    }

veiws\TestGird.cshtml

    <script>var InForeCastTypeEqual = (function () {
     function InForeCastTypeEqual() {
        }

        InForeCastTypeEqual.prototype = {
            render: function (grid, popup, filter) {
                var lang = $.fn.mvcgrid.lang.Number;
                lang.NotSpecified = 'Not specified';

                popup.html(
                    '<div class="popup-arrow"></div>' +
                    '<div class="popup-content">' +
                    '<div class="first-filter popup-group">' +
                    '<ul class="mvc-grid-boolean-filter">' +
                    '<li ' + (filter.first.val == '0' ? 'class="active" ' : '') + 'data-value="0">' + 
    @(((InForeCastType)0).ToString()) + '</li>' +
                    '<li ' + (filter.first.val == '1' ? 'class="active" ' : '') + 'data-value="1">' + 
    @(((InForeCastType)1).ToString()) + '</li>' +
                    '<li ' + (filter.first.val == '2' ? 'class="active" ' : '') + 'data-value="2">' + 
    @(((InForeCastType)2).ToString()) + '</li>' +
                    '<li ' + (filter.first.val == '3' ? 'class="active" ' : '') + 'data-value="3">' + 
    @(((InForeCastType)3).ToString()) + '</li>' +
                    '</ul>' +
                    '</div>' +
                    '<div class="popup-button-group">' +
                    '<button class="btn btn-success mvc-grid-apply" type="button">✔</button>' +
                    '<button class="btn btn-danger mvc-grid-cancel" type="button">✘</button>' +
                    '</div>' +
                    '</div>');
            },

            init: function (grid, column, popup) {
                this.bindValue(grid, column, popup);
                this.bindApply(grid, column, popup);
                this.bindCancel(grid, column, popup);
            },
            bindValue: function (grid, column, popup) {
                var values = popup.find('.first-filter li');
                values.on('click.mvcgrid', function () {
                    $(this).addClass('active').siblings().removeClass('active');
                });
            },
            bindApply: function (grid, column, popup) {
                var apply = popup.find('.mvc-grid-apply');
                apply.on('click.mvcgrid', function () {
                    popup.removeClass('open');
                    column.filter.first.val = popup.find('.first-filter .active').data('value');
                    if (column.filter.first.val == 'NotSpecified') {
                        column.filter.first.type = 'Is';
                    } else {
                        column.filter.first.type = 'Equals';
                    }

                    grid.applyFilter(column);
                    grid.reload();
                });
            },
            bindCancel: function (grid, column, popup) {
                var cancel = popup.find('.mvc-grid-cancel');
                cancel.on('click.mvcgrid', function () {
                    popup.removeClass('open');

                    if (column.filter.first.type) {
                        grid.cancelFilter(column);
                        grid.reload();
                    }
                });
            }
        };;

        return InForeCastTypeEqual;
    })();

    $('.mvc-grid').mvcgrid({
        filters: {
            'InForeCastType': new InForeCastTypeEqual()
        }
    });</script>

**Comment by Muchiachio** [comment]
`MvcGrid.Filters.Register(typeof(bool), "Is", typeof(InForeCastTypeEqual))`
Boolean should be changed to your enum type here, because you are registering a filter for a type.

**Comment by lukehammer** [comment]
Ok That was one of the things I attempted. I have made that change and it is reflected in the (test project)[https://github.com/lukehammer/NonFactorsTesting].

Currently, the filter button is not popping up nor is it producing a JS error when clicked. 

Selecting the filter button will close any other popup.  but will not create it's own.

**Comment by Muchiachio** [comment]
Other things would be `columns.Add(model => model.InForeCastType)` needs a `.FilteredAs("InForeCastType")`, because it doesn't know a filter name you registered at
```JS
$('.mvc-grid').mvcgrid({
    filters: {
        'InForeCastType': new InForeCastTypeEqual()
    }
});
```
Boolean example worked, because it's already built in. Also, you should upgrade your grid, you are using 2.X together with 4.X documentation or you can clone older versions of docs to your computer.

**Comment by lukehammer** [comment]
OK, 

Updated the line to include "Filtered As".

` columns.Add(model => model.InForeCastType).Titled("InForeCastType").Sortable(true).FilteredAs("InForeCastType");'

I also upgraded the Project to 4.2 I should have caught that one.


But I'm still having problems. The Popup is still **NOT** popping up. 

Also, i have made a second grid using http://mvc-grid.azurewebsites.net/Column/CustomFilter as an example. This Grid is also having the same problem.

**Comment by lukehammer** [comment]
my guess what that I was not configuring the C# filter class correctly 
    public class InForeCastTypeEqual : BaseGridFilter
    {


        public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, Expression.Constant(null));
        }
    }

**Comment by lukehammer** [comment]
OK got http://mvc-grid.azurewebsites.net/Column/CustomFilter example working.   The problem was my JS file was in the head. after moving the file to the end of the body it is working again.  Also i nuget installed from 4.2 to 2.2 then back to 4.2. I think i might not have gotten a clean install on my first trip to 4.2

**Comment by lukehammer** [comment]
Ok i have the POPUP poping up  

     '<li ' + (filter.first.val == '0' ? 'class="active" ' : '') + 'data-value="0"> ' + '@(((InForeCastType)1).ToString())' + ' </li>' +

`'@(((InForeCastType)1).ToString())'` needed to be in qoutes

**Comment by lukehammer** [comment]
What should I inherit from? I'm working with an Enum so I think INT32 but I'm looking for behavior like the nullable boll employed in the example. http://mvc-grid.azurewebsites.net/Filter/Register. 

I think this is the last step Thank you very much for your help.

**Comment by Muchiachio** [comment]
Your inherit is ok, you need to cast Value to your enum and pass it as `Expression.Constant(yourEnumValue)`.

**Comment by lukehammer** [comment]
Ok I have a few tryes here and still no luck. I will spend some time toning out on expressions but i thought one of these would work  

       public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, 
    Expression.Constant((InForeCastType)Enum.ToObject(typeof(InForeCastType),Value)));
        }

**Comment by Muchiachio** [comment]
It's not getting called now, because you registered enum filter for `Is`, but not for `Equals`.
`MvcGrid.Filters.Register(typeof(bool), "Equals", typeof(InForeCastTypeEqual))`

**Comment by lukehammer** [comment]
OK I'm closer now. I'm now hitting my custom filter method after making change to `MvcGrid.Filters.Register(typeof(bool), "Equals", typeof(InForeCastTypeEqual))`

however not getting yellow screen error "The binary operator Equal is not defined for the types 'NonFactorsTesting.Models.InForeCastType' and 'System.RuntimeType'."

**Comment by Muchiachio** [comment]
Yes, you now need `Expression.Equal(expression, Expression.Constant(yourEnumValue)`.

**Comment by lukehammer** [comment]
OK 
and that should be in my InForeCastTypeEqual class 

    public class InForeCastTypeEqual : BaseGridFilter
    {
        public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, Expression.Constant(typeof(InForeCastType)));
        }
    }
![capture](https://user-images.githubusercontent.com/8842287/33705312-a1621db8-dae4-11e7-8034-bdd6fb5e09da.JPG)

**Comment by Muchiachio** [comment]
It throws, because you are creating expression without using the `value`, you are making this now
`models = models.Where(model => model.InForeCastType == typeof(InForeCastType))`

**Comment by lukehammer** [comment]
OK i got it working by doing this

    public class InForeCastTypeEqual : Int32Filter
    {
        public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, Expression.Constant((InForeCastType) int.Parse(Value)));
        }
    }
IT WORKS Thank you soo much.
