### ISSUE TITLE
Setting different css classes for th and td elements?

### ISSUE THREAD

**Issue by MrNorth35** [NonFactors/MVC5.Grid#112]
Hi!

We have spent quite some time trying to figure out how to style the header (th) and row/cell (td) elements individually.

Our issue is that we want the header to wrap but the data not to wrap.  We created a simple class;

```
.col-nowrap {
    white-space: nowrap;    
}
```

that we added with razor using the .Css("col-nowrap") method when configuring the row. We noticed that this class is added both to the th and td tags. Is there a preferred way to solve this issue so we can style the th text and the td text individually?

**Comment by Muchiachio** [comment]
This should be enough
```CSS
th.col-nowrap {
    white-space: nowrap;    
}
```
