### ISSUE TITLE
Show loading while loading data of paging

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#113]
Maybe it's nice to see a loader when paging of using the ajax grid.
This because it takes a few seconds to load data into the grid with @Muchiachio Html.AjaxGrid(Url.Action("IndexGrid", new { param = "value"}))

Also paging takes a second and i can imaging users will click again because they don't see anything happen.

**Comment by Muchiachio** [comment]
Yes, I left it to the user, [here's](http://mvc-grid.azurewebsites.net/Javascript/ReloadEvents) an example on how to do that. I don't think that my own content lock and loading styling would be suitable for most of the applications. :smile:

**Comment by vinicius83** [comment]
I'm thinking of doing the same thing. My pagination after rendering takes a few seconds to get it working and let me click the next page. Just to remind I'm using the custom grid partial.

**Comment by vinicius83** [comment]
The javascript event reloadEnded is triggered before the grid is actually updated, maybe its because of the "custom grid partial". I have update the version today after see this bug [here](https://github.com/NonFactors/MVC5.Grid/issues/28) but I still have the same problem :|
