### ISSUE TITLE
QBE Line

### ISSUE THREAD

**Issue by dev-marc** [NonFactors/MVC5.Grid#114]
Hi there,

Yesterday I played around with the grid for a project i'm working on. I love the easy setup and the way you can connect it to any backend. For my web project I would like it to use it as the default way to show data, but my project sponsors are huge fans of QBE (Query by example) headers. Basically adding the filter inputs in the header of the grid.  Like this:

![image](https://user-images.githubusercontent.com/35723053/35265063-55410b1e-001f-11e8-8f95-cc237aa639cc.png)

Is this a feature you think will add extra value? I'm willing to contribute to create it.

**Comment by Muchiachio** [comment]
Well I'm guessing that custom grid partial feature will be lost in the next major release if this and Nonfactors/Mvc6.Grid#101 would land as it will be riddled with conditionals :smile:

**Comment by dev-marc** [comment]
Thanks for your response. Do you have suggestion or any direction on how I still can add this feature for my own project?

**Comment by Muchiachio** [comment]
I will probably be adding this in the next major release.
As for now it can be added through `custom grid partial`, it would go similarly to this.

1. Render additional row before rendering the data
```HTML
<tbody>
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            <td data-filter="@column.IsFilterable"
                data-filter-name="@column.FilterName"
                data-filter-first-type="@(column.Filter != null && column.Filter.First != null
                            ? column.Filter.First.Type : "")"
                data-filter-first-val="@(column.Filter != null && column.Filter.First != null
                            ? column.Filter.First.Value : "")"><input class="qbe-filter" /></td>
        }
    </tr>
```
2. Process search requests
```JS
$('.qbe-filter').on('input', function () {
    var grid = $(this).mvcgrid().closest('.mvc-grid').data('mvc-grid');
    var columns = grid.columns;

    var column = // find column in columns by name or position
    
    // apply filter
    column.filter.first.type = 'Equals';
    column.filter.first.val = this.value;

    grid.applyFilter(column);
    grid.reload();
});
```

**Comment by dev-marc** [comment]
Thanks a lot! If there is anything I can help you out with in return. Let me know!

**Comment by dev-marc** [comment]
@Muchiachio just one question, any thought on when the next major release will be released?

**Comment by Muchiachio** [comment]
Probably in 2-5 months time, I want to collect as many breaking changes as possible so I wouldn't have to do a major release too often.
