### ISSUE TITLE
Popup Confirmation before delete a row

### ISSUE THREAD

**Issue by Krupskaia** [NonFactors/MVC5.Grid#115]
I love you grid and I wanted to use it, but I have been trying to do a popup confirmation before deleting a row without success. If you have an example it will be very appreciated. Thanks

**Comment by Muchiachio** [comment]
Simplest way would be
```C#
columns.Add(model => Html.ActionLink("Delete", "Del", new { model.Id }, new { @class = "del" }));
```
Bind `.del` to show confirmation
```JS
$('.del').on('click', function(e) {
    if (!confirm('Do you want to delete?')) {
        e.preventDefault();
    }
});
```
