### ISSUE TITLE
List inside a model 

### ISSUE THREAD

**Issue by vinicius83** [NonFactors/MVC5.Grid#117]
My Grid receive a List<T> that is inside my model.  

Exemple:
```
@model System.ViewModels.CountryModel
@if (Model != null)
{
    @(Html
        .Grid(Model.listTax)
...
```

The Grid show the data correctly, when I load the View with the model, but when I try to invoke the Model on the Controller, the List is null.

```
[HttpPost]
[SubmitButtonSelector(Name = "Save")]
public ActionResult Save(CountryModel countryModel , CountryTaxModel test)
{
    try
    {
````
The others parameters of the model are fine and completed.

**Comment by Muchiachio** [comment]
Grid only shows the data, it doesn't create input fields to be submitted by the form.
That's why you don't get them in the post request.

**Comment by vinicius83** [comment]
Solved using `@Html.Hidden("[" + index + "]." + column.Name, @column.ValueFor(row)) `

On View _Grid.cshtml:

` @if (Model.Rows.Any())
            {
                int index = 0;
                foreach (IGridRow<Object> row in Model.Rows)
                {
                    
                    <tr class="@row.CssClasses">
                        @foreach (IGridColumn column in Model.Columns)
                        {
                            <td class="@column.CssClasses">@column.ValueFor(row)</td>
                             @Html.Hidden("[" + index + "]." + column.Name, @column.ValueFor(row))
                        }
                    </tr>
                    index++;
                }
            }`


On Controller:

`public ActionResult Save(CountryModel countryModel , List<CountryTaxModel> lstCountryTaxModel )`
