### ISSUE TITLE
Filtered export

### ISSUE THREAD

**Issue by HoloJackStones** [NonFactors/MVC5.Grid#119]
I followed your example for grid exporting but i cannot get it working.
This code seems not to working:

`grid.Query = new NameValueCollection(Request.QueryString);`

The queryString contains correct parameters, bht the filter is not applied even on the view. 

Do i have to manually parse the querystring and apply filtering to the source?

**Comment by Muchiachio** [comment]
No, it should work automatically. Did you enable filtering on all the columns?
Because current example works with filtered data, so something is most likely missing on your side.

**Comment by HoloJackStones** [comment]
My code is almost identical to your:

```
private IGrid<AnswerModel> CreateExportableGrid(string fv)
    {
      var items = GetAnswersByFilter(fv);     
      IGrid<AnswerModel> grid = new Grid<AnswerModel>(items);

      grid.Columns.Add(model => model.LicensePlate).Titled("LicensePlate");
      grid.Columns.Add(model => model.CustomerName).Titled("CustomerName");
      grid.Columns.Add(model => model.CustomerMobile).Titled("CustomerMobile");
      grid.Columns.Add(model => model.CustomerEmail).Titled("CustomerEmail");
      grid.Columns.Add(model => model.CarManufacturer).Titled("CarManufacturer");
      grid.Columns.Add(model => model.CarModel).Titled("CarModel");
      grid.Columns.Add(model => model.JobStartDateTime).Titled("JobStartDateTime");
      grid.Columns.Add(model => model.CheckoutDateTime).Titled("CheckoutDateTime");
      grid.Columns.Add(model => model.AnswersDescriptions).Titled("AnswersDescriptions");
      grid.Columns.Add(model => model.AnswerNotes).Titled("AnswerNotes");
      grid.Columns.Add(model => model.NoAnswerReason).Titled("NoAnswerReason");

      grid.Query = new NameValueCollection(Request.QueryString);

      grid.Pager = new GridPager<AnswerModel>(grid);
      grid.Processors.Add(grid.Pager);
      grid.Pager.RowsPerPage = 20;

      var rows = grid.Rows.Count();

      foreach (IGridColumn column in grid.Columns)
      {
        column.IsFilterable = true;
        column.IsSortable = true;
      }

      return grid;
    }

```

**Comment by Muchiachio** [comment]
Move `grid.Rows.Count()`, below the `IsFilterable = true` code, because it caches the result.
If you need total count before filtering, use either `items.Count()` or `grid.Source.Count()`.

**Comment by HoloJackStones** [comment]
Perfect, it works!
I added that line of code for debug purposes. Can't imagine that could be the cause of the issue.

Thanks a lot

**Comment by HoloJackStones** [comment]
Just another questions: 
in the export case, i have to disable pagination, right?
Because i need to export all rows regardless of the paging size.

**Comment by Muchiachio** [comment]
Yes, if you want to export all rows you would have to disable pagination.

**Comment by HoloJackStones** [comment]
Great. Thanks again for fast support.
