### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#120]
I just updated our version to version Mvc.Grid 4.3.0.
Now i got a javascript error in (IE Explorer, Firefox, Edge, Chrome)

Unable to get property 'element' of undefined or null reference
mvcgrid (1,3438)

Thanks guys

**Comment by Muchiachio** [comment]
Can you share a small repro?

**Comment by NathalieSpierings** [comment]
Steps we have done:
1) I updated our packages from version 4.1.0 to 4.3.0.
2) I rebuild the solution. 
3) I run the application and go to a view with the grid on it.

All seems to work just fine.

4) I hit F12 in the browser for the developer tools and in the console log i am getting the error:
Unable to get property 'element' of undefined or null reference
mvcgrid (1,3438)

5) I updated our packages to version 4.2.0
Same error in developer tools

6) I updated our packages back to version 4.1.0
Error gone

**Comment by Muchiachio** [comment]
Well by repro I meant a small project showing a problem
Because I would have seen this issue on previous updates or on [documentation site](http://mvc-grid.azurewebsites.net/), but it's not there.

**Comment by NathalieSpierings** [comment]
I have following code:
When i look at the debugger, is see Started, then Ended, then js error: i is undefined on row 134.

$('.mvc-grid').mvcgrid({        
        reloadStarted: function () {
            console.log('Started :)');
        },
        reloadEnded: function () {
            console.log('Ended :)');
        },
        reloadFailed: function (result) {
            console.log('Failed :)');
        },
        reload: true,
        rowClicked: function (row, data, e) {
         
             console.log('Clicked :)');
        }       
    });

**Comment by Muchiachio** [comment]
Could you share a full project in github? Documentation page has similar page and I tried copying this code and it worked without an error. Maybe you have additional content in grid partial?

**Comment by NathalieSpierings** [comment]
I have made a simple sample project with a simple grid for Persons.
When you run it you will see the javascript error in F12 developertools. 
I use firefox but it's also giving this error in IE and Chrome.
Download the sample i made from here: https://github.com/NathalieSpierings/GridMvc.JSError

**Comment by Muchiachio** [comment]
It happens because you are reloading the grid twice at the same time, once in `myApp.js#initGrid` and another in `index.js:6`, both are using ajax's done method to append the grid, resulting in a race conditions.
