### ISSUE TITLE
Html anchor doesn't work

### ISSUE THREAD

**Issue by keremburak** [NonFactors/MVC5.Grid#122]
Hi Muchiacho,

I use your grid many pages of my some projects. It is fascinating. But when I used it in a partial view in bootstrap tab, the anchor in the row, doesn't work. I create an Index page which includes three bootstrap tabs. And I create a different partialview for each tab. And I put a grid in them one by one.

My structure is like this:

Index.cshtml (bootstrap tabs, I load grid in Index.cshtml with below LoadGrid JS func)
       |
_SpecialPartialView.cshtml  (I put grid here)

I put all needed codes
       
This is my "_IndexGrid.cshtml" partial view code

```
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id).Css("hiddenCol");
        columns.Add(model => model.DocumentType).Titled("Evrak Tipi");    
        columns.Add(model => "<a href='#' class='detail' data-id='" + model.Id + `"'>Display</a>").Encoded(false);`
    })
    .Sortable()
    .Pageable(pager =>
    {
        pager.RowsPerPage = 5;
        pager.PagesToDisplay = 3;
    }))

```

I call grid like this:

`     @Html.AjaxGrid(Url.Action("IndexGrid"))`

I load it with this function :

```
   function LoadGrid(element, searchtext) {
            content = $(element).find('.mvc-grid');   //'element" corresponds an HTML div.

            $(content).mvcgrid({
                query: 'search=' + searchtext,
                reloadStarted: function () {
                    content.block({ message: "Loading..." });
                },
                reloadEnded: function () {
                    content.unblock();
                },
                reloadFailed: function (result) {
                    operations.showMessage("An error has been occured", "danger", { from: "top", align: "right" });
                },
                reload: true
            });
        }
```
I put anchor click event in "_SpecialPartialViw.cshtml". It is like this.

```
    $(document).ready(function () {
        $('.detail').on('click', function () {   //anchor link click event
            //get companies
            $.getJSON('@Url.Action("GetAccountTransaction", "AccountTransaction",new { area = "Admin"})', { id: $(this).val() }, function (data) {
                console.log(data);
                $('#tbUpdate').show();
            });
        });
    });
```
As I said above my problem is that my anchor link click event (it is above) , doesn't trigger. I putan alert for testing in the click block, it doesn't trigger click event.

May be, you can have an idea. Could you give me a hand ?

Thanks in advance 

Kerem

**Comment by Muchiachio** [comment]
You probably need to bind your action on a static parent in the DOM
```JS
$('.static-parent').on('click', '.detail', function () {
```
or after grid is loaded
```JS
$(content).mvcgrid({
    reloadEnded: function () {
        $('.detail').on('click', function () {
        });

        content.unblock();
    }
});
```
because dynamic grid content isn't there yet at the time of your event binding.

**Comment by keremburak** [comment]
Yeah.. You are right. I missed that point. It is OK . 

Thanks for your help.
