### ISSUE TITLE
Global search & paging

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#125]
As a user of the grid i am paging for example page 3. After the paging i beside to search in the global search textbox. I see my search results. If i remove my search text from the input i am back on page 1 and not on page 3. This is not correct

**Comment by Muchiachio** [comment]
It's debatable, if I search for `equals=abc` and I go to 5th page, and then search for `equals=ab` and I only get 2 pages, should I stay on the 5th or go back to the 2nd or to the first? What happens after I search for `equals=abc` again, I should be back on 5th page, even though I'm on x page now?

The other question, I asked the users and usability people is:
`Is it better to see newly filtered data in random page you left your old data in or from the start to finish in your specified sorting order?` and both groups agreed that's better to reset the page.

The same can be observed in other widely used websites like youtube, google and so on, if you change filtering or even sorting criteria in some cases, your page and your loaded data (infinite scroll scenario) is reset back to the first page.

**Comment by NathalieSpierings** [comment]
Oke, it's debatable.
I will convince my users about it.
