### ISSUE TITLE
Duplicate rows

### ISSUE THREAD

**Issue by omarhimada** [NonFactors/MVC5.Grid#126]
Hey when I sort by a column while filtering another column I get duplicate pages (e.g. paging with 20 rows at a time pages 1 and 2 are always identical, if I do paging 15 rows at a time pages 1, 2 and 3 are all identical, showing identical rows)

I've tried changing the paging processor type to manual and paging manually, that didn't work. I'm not really sure whats going on

Any help much appreciated!

**Comment by Muchiachio** [comment]
How are you returning your data?
Does the same happen with lets say
```C#
return View(
    Enumerable
        .Range(1, 1000)
        .Select(model => new YourModel { YourProperty = model.ToString() });
```

**Comment by Muchiachio** [comment]
I'm not suggesting to use `IEnumerable`. What I'm getting at is maybe your data is paged or filtered somehow, because I can't reproduce the issue on documentation page (sorting string and filtering boolean).

**Comment by omarhimada** [comment]
Yeah I'm definetly doing some filtering with a Where clause, but I can't imagine how that would interfere. Here is my return statement:

    return View(db.MyTable
        .Where(i => i.ImportantString == "C" && i.Expired == null)
        .OrderBy(i => i.Id));

**Comment by omarhimada** [comment]
I should mention the columns I'm filtering/sorting by that produces the problem aren't mentioned in that Where clause, they're different

**Comment by Muchiachio** [comment]
Look ok, can you share a repro project? I don't have any more ideas on why it doesn't work.

**Comment by omarhimada** [comment]
Accidentally closed this, my bad!

**Comment by Muchiachio** [comment]
Hehe, you don't have to share your owned code, just create a new web app and make a dummy grid.

**Comment by omarhimada** [comment]
Weirdly enough, if I set RowsPerPage = 10, then instead of the first two pages being the same, the first FOUR pages are the same...
I think it has something to do with the Skip/Take logic

**Comment by Muchiachio** [comment]
You can try doing the same on your result set and inspecting it in debug.
Or try logging database queries, maybe you can see something out of place in there.

**Comment by omarhimada** [comment]
I did SQL profiler and this is whats being executed. Note only the "OFFSET" is different. I ran the SQL and I'm getting the same 20 rows back for both pages... doesn't make any sense to me. The rows are unique, there are no duplicates in the database. Any ideas?

	-- Page 1
	SELECT *
	FROM [dbo].[DigitalOffers] AS [Extent1]
	WHERE (N'L' = [Extent1].[PromotionPrefix]) AND ([Extent1].[Expired] IS NULL) AND (1 = [Extent1].[Active])
	ORDER BY [Extent1].[OfferType] ASC
	OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY 

	-- Page 2
	SELECT *
	FROM [dbo].[DigitalOffers] AS [Extent1]
	WHERE (N'L' = [Extent1].[PromotionPrefix]) AND ([Extent1].[Expired] IS NULL) AND (1 = [Extent1].[Active])
	ORDER BY [Extent1].[OfferType] ASC
	OFFSET 20 ROWS FETCH NEXT 20 ROWS ONLY

**Comment by omarhimada** [comment]
According to this stackoverflow post it has to do with an issue that arises when you ORDER BY a column that doesn't contain unique data 

https://stackoverflow.com/questions/15783608/sql-server-2012-offset-return-same-record

**Comment by Muchiachio** [comment]
Yep that happens in sql engines, then sorting by one column.
