### ISSUE TITLE
Loading screen before data loads

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC5.Grid#127]
I am calling an ajax grid with

    @Html.AjaxGrid(Url.Action("IndexGrid"))

and it works great, however I want to show a loading message before the data loads (so that the screen is not empty).

I checked [this issue](https://github.com/NonFactors/MVC5.Grid/issues/56), but it does not actually answer the question, as the `reloadStarted` event only seems to fire on a **reload**, and not an initial load.

IE, if I navigate to the grid or refresh the screen, the event does not fire, but if I use for example the search functionality, then the event does fire, as the grid is reloaded.

Is there not something like a `loadStarted` event rather than `reloadStarted`? If not how can I implement a simple loading message?

**Comment by Muchiachio** [comment]
It should fire if your first call to `.mvcgrid()`, includes `reloadStarted` binding.
Maybe you are calling empty `.mvcgrid()` constructor and then the one with reload binding?

**Comment by sebasijan** [comment]
@Muchiachio Thanks for your reply.

I am only calling `mvcgrid()` once:

    @Html.AjaxGrid(Url.Action("IndexGrid"))

    @section Scripts {
        <script>
            $(document).on('rowclick', '.mvc-grid', function (e, data, grid, originalEvent) {
                window.location.href = '@Url.Action("Details","CRMTItems")/' + data.Id
            });

            $(document).on('keyup', '.grid-search', function () {
                $('.mvc-grid').mvcgrid({
                    query: 'search=' + this.value,
                    reload: true,
                    reloadStarted: alert('load');
                });
            });

            $('.plgram').on('click', function () {
                var value = $(this).text();
                $('.mvc-grid').mvcgrid({
                    query: 'filter=' + value,
                    reload: true,
                    reloadStarted : alert('load')
                });
            })
        </script>
    }

Where my partial view looks like this

    @model IEnumerable<ADVWKSP.Models.ViewModels.CRMTItemViewModel>
    @using NonFactors.Mvc.Grid

    @{
        Layout = null;

        var archiveStatus = (bool)Session["archive"];
    }

    @(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.Id).Css("hidden");
                columns.Add(model => model.ProjectTitle).Sortable(true);
                columns.Add(model => model.Client).Sortable(true);
                columns.Add(model => model.ProjectManagerDisplayName).Sortable(true);
                columns.Add(model => $@"<a class=""btn btn-default btn-sm rowWorkspaceLink pull-right"" href=""{model.WorkspaceUrl}"" target=""_blank""><span class=""glyphicon glyphicon-globe"">").Encoded(false);
            })
            .RowCss(model => ($"{model.Stage} crmtRow"))
            .Pageable()
    )

    @section scripts {
        <script>
        
        </script>
    }

So I'm expecting to see an `alert` whenever the grid loads, but nothing happens ( no errors in console either..)

**Comment by sebasijan** [comment]
@Muchiachio  Okay I found the problem..

Just need to add a

        $(document).ready(function () {
            $('.mvc-grid').mvcgrid({
                reloadStarted: alert('load')
            });
        });

As it seems it wasn't getting called until i searched... But then how was it being initialised?
