### ISSUE TITLE
Annoying issue where the whole page refreshes after reloading AJAX grid

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC5.Grid#129]
I am seeing this extremely annoying issue and I just don't know what is going on.

**VIEW**

    <div class="row">
        <button id="refresh" type="button" class="form-control"><span class="glyphicon glyphicon-refresh"></span></button>
    </div>

    @Html.AjaxGrid(Url.Action("UserList", "Box"))

When I click the `refresh` button, it should reload the ajax grid, but **NOT** the entire page (I wish to pass some details into the controller, and if the page reloads then that query comes through to the controller as `null`).

**SCRIPT**

    @section Scripts {
        <script>
            function refresh() {
                var q = 'refresh=true';
                
                $('.mvc-grid').mvcgrid({
                    query: q,
                    reload: true,
                    reloadStarted: function(result) {
                        $('#loadingmessage').show();
                        loading = true;
                    },
                    reloadEnded: function(result) {
                        $('#loadingmessage').hide();
                        loading = false;
                    },
                    reloadFailed: function(result) {
                        $('#loadingmessage').hide();
                        console.log('fail');
                    }
                });
            }

            $('#refresh').on('click',function() {
                refresh();
            });

            $(document).ready(function(){
                loading = true;
                $('.mvc-grid').mvcgrid({
                    reloadStarted: function(result) {
                        $('#loadingmessage').show();
                        loading = true;
                    },
                    reloadEnded: function(result) {
                        $('#loadingmessage').hide();
                        loading = false;
                    },
                    reloadFailed: function(result) {
                        $('#loadingmessage').hide();
                        console.log('fail');
                    }
                });
            });
        </script>
    }

**Controller**

    public ActionResult UserList(string refresh)
    {
        var boxManager = new BoxManager();

        if(!_cache.TryGetValue($"boxuserreport", out boxusers) || refresh=="true")
        {
            boxusers = boxManager.GetWPBoxUsers();
            // Set cache options.
            var cacheEntryOptions = new MemoryCacheEntryOptions()
            // Keep in cache for this time, reset time if accessed.
            .SetSlidingExpiration(TimeSpan.FromSeconds(30000));
            _cache.Set($"boxuserreport", boxusers, cacheEntryOptions);
        }

        return PartialView("_BoxUsersGrid", boxusers);
    }

I have definitely done this before (e.g. when implementing a search using a similar pattern) and it works just fine.. Please can someone help.

I can see that after refreshing, the url changes from http://localhost:5000 to 

    http://localhost:5000?

**Comment by Muchiachio** [comment]
Are you only including grid content in ajax partial?

**Comment by Muchiachio** [comment]
Your `_BoxUsersGrid.cshtml` should only include grid content, because ajax grid gets updated with whatever is returned from the partial.
