### ISSUE TITLE
Filter text value null

### ISSUE THREAD

**Issue by Liuk0** [NonFactors/MVC5.Grid#130]
Hi,
when using filter on grid like this
![image](https://user-images.githubusercontent.com/38788301/39365705-330a878e-4a32-11e8-9432-7fa8f41dbf52.png)
on the post request i got Request.QueryString = "m-e-s-e-equals=" without "test"
![image](https://user-images.githubusercontent.com/38788301/39366126-52f89a4e-4a33-11e8-95a5-c9e466f895fb.png)

I have investigated the problem and it seems that the error is in the js MvcGridFilter.apply method.
so the last version of the method is:

apply: function (grid, column, popup) {
	popup.removeClass('open');

	var container = $(column.rowFilter || popup);

	column.filter.operator = container.find('.mvc-grid-operator').val();
	column.filter.first.method = container.find('.first-filter .mvc-grid-method').val();
	column.filter.second.method = container.find('.second-filter .mvc-grid-method').val();

	if (grid.filterMode != 'FilterRow' && column.filter.hasOptions) {
		debugger;
		column.filter.first.value = popup.find('.first-filter .mvc-grid-value').val();
		column.filter.second.value = popup.find('.second-filter .mvc-grid-value').val();
	} else {
		column.filter.first.value = container.find('.first-filter .mvc-grid-value').val();
		column.filter.second.value = container.find('.second-filter .mvc-grid-value').val();
	}

	grid.applyFilter(column);
	grid.reload();
}

and if i change the lines:
else {
		column.filter.first.value = container.find('.first-filter .mvc-grid-value').val();
		column.filter.second.value = container.find('.second-filter .mvc-grid-value').val();
	}

To:

else {
		column.filter.first.value = container.find('.first-filter .mvc-grid-value')[1].value;
		column.filter.second.value = container.find('.second-filter .mvc-grid-value').val();
	}

the filter work

Can you check this?

Thanks

Luca

**Comment by Muchiachio** [comment]
I saw this happening if the page has multiple `mvc-grid.js` included, can you check if it's not the case?

**Comment by Liuk0** [comment]
I was asking you why $ ('. mvc-grid-popup'). length returns 2 and I verified that I made the script render twice on different pages, thanks for the help
