### ISSUE TITLE
How to distinguish search from pagination

### ISSUE THREAD

**Issue by Veelja** [NonFactors/MVC5.Grid#133]
I want to use cached data for pagination, but i don't know in controller if request is pagination or new search.

**Comment by Muchiachio** [comment]
Pagination passes query parameters in a form of `[Grid.Name-]Page=X&[Grid.Name-]Rows=Y`, so you can check if they are set in `Request.QueryString` and continue from there.

**Comment by Veelja** [comment]
Thanks. 
If i were on the page 2 and do ajax search there is still paging info in query string.
When i set any value in query parameter paging invo removed.

```
 $('.mvc-grid').mvcgrid({
                    query: 'refresh=true', //this removes paging from query string
                    requestType: 'post', // defaults to get
                    name:"partner-pretraga",
                    reload: true,
                    data: $("#pretraga").serialize()
                });
```

**Comment by Muchiachio** [comment]
Yes, because you are setting the whole query If that's the problem you can take the current query from `$('.mvc-grid').mvcgrid('instance').query` and modify it, but I usually reset paging information on every new search to improve user experience and avoid over paging problems.
