### ISSUE TITLE
Filter dropdown language

### ISSUE THREAD

**Issue by Krupskaia** [NonFactors/MVC5.Grid#134]
How I can change the language of the text of filter's dropdowns. I have tried the example that you have but that does not change them.

**Comment by Muchiachio** [comment]
It should work, maybe you are using older grid version?

**Comment by Muchiachio** [comment]
Did you find the problem?

**Comment by Krupskaia** [comment]
Thanks, I updated the version and that fix the problem.

**Comment by rmzncvk** [comment]
Hi,
I have same problem ,
I dont know  how can I change filter language.

**Comment by Muchiachio** [comment]
Does localization example not work?

**Comment by rmzncvk** [comment]
yes not working

**Comment by rmzncvk** [comment]
> yes not working

can you give me example file ?

**Comment by Muchiachio** [comment]
You already have an example file and it's not working, so what is not working? Do you get any errors?
Did you try seeing what is wrong? What did you try? Which page are you looking for example?
