### ISSUE TITLE
render 3 action Link in a column

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Grid#137]
Hi there, 

is there any function to add 3 action link in a column, like col-span?

**Comment by Muchiachio** [comment]
Whatever you pass as a column value will get rendered, if you pass 3 action links, 3 action links will get rendered. Maybe you have a styling issue and not the grid one? For example this adds three links
```C#
columns.Add(model => "<a href='#'>1</a><a href='#'>2</a><a href='#'>3</a>").Encoded(false);
```
If you are using `Html.ActionLink`, you will have to make them strings and concatenate, other than that I would still recommend using 3 different columns with some class like `.action-link` if you don't want borders or want to space them differently.

**Comment by junrikson** [comment]
thank you, `Encoded(false)` works perfectly in my case
