### ISSUE TITLE
Can not Filter Type Data Guid

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Grid#138]
Hi there, 

I have Guid field in model 
`public System.Guid UserId { get; set; }`

And added to mvc grid like below :
`columns.Add(model => model.UserId).Titled(@Html.DisplayNameFor(model => model.UserId));`

The filter button showed up, but nothing happens when I click the button.

**Comment by Muchiachio** [comment]
You will have to register your own guid value filter, because it's not supported out of the box. Supported:
- all numbers
- boolean
- string
- date

**Comment by Muchiachio** [comment]
As shown in [here](http://mvc-grid.azurewebsites.net/Filter/Register). You need a server side filter and a javascript popup html provider for a new filter.
Extending `MvcGridFilter` can help with basic filter html on the client side.

**Comment by junrikson** [comment]
is there any easy way to make the guid act like string?

**Comment by Muchiachio** [comment]
Save it as string, or map it to string when selecting from the database. I don't think that EF or other providers support using string like operations on the native guid type though.

**Comment by junrikson** [comment]
Thank you.
