### ISSUE TITLE
How to get currentPage in Controller's action

### ISSUE THREAD

**Issue by dragonsky18** [NonFactors/MVC5.Grid#14]
Hi,

    I want to know how to How to get currentPage in Controller's action?  you use grid-page as querystring , but I cannot use it as parameter in Controller's action.

Thanks in advance

**Comment by Muchiachio** [comment]
Everything is accessible from request's query string.
```C#
[HttpGet]
public ViewResult Index()
{
    NameValueCollection query = Request.QueryString;
    String pageValue = query["grid-page"];

    return View();
}
```

I will consider renaming `grid-page` to `GridName` in v3, so it can be accessed more easily.

**Comment by dragonsky18** [comment]
thank you
