### ISSUE TITLE
Quick start example not work

### ISSUE THREAD

**Issue by ste22g** [NonFactors/MVC5.Grid#142]
Hello,
 I'm trying to display the elements of a single table using the basic example, but I get the error:
 "invalidoperationexception: The operation can not be completed because the DbContext has been disposed". 
I'm using MVC5 and EF6.
In the controller the code is identical to the example as shown `below:
```
[HttpGet]
public ViewResult Index3()
{
    using (var context = new MCS1DBEntities())
    {
        var cts = context.Contracts.OrderBy(b => b.Id);
	return View(cts);
    }
}
```
The error disappears if I remove the "using" in the allocation of the dbcontext:
```
[HttpGet]
public ViewResult Index3()
{
        var context = new MCS1DBEntities())
 	var cts = context.Contracts.OrderBy(b => b.Id);
	return View(cts);
}
```
Thank you.

**Comment by Muchiachio** [comment]
True, context dispose should be in controller's dispose method, will update the example page.

**Comment by ste22g** [comment]
Would it be possible to use an "`IList`" collection instead of "`IQueryable`"?
Thanks again.

**Comment by Muchiachio** [comment]
You can use any `IEnumerable` implementation, just be careful with what their implementations imply.

**Comment by ste22g** [comment]
Excuse me again, 
but if I use an "`IList`" collection (`return context.Foos.OrderBy(b => b.Id).ToList();`) I get the following error:
"The model element passed in the dictionary is of type 'System.Collections.Generic.List`1 [Grid4Test.Models.Foo]' but this dictionary requires a model element of type 'System.Linq.IQueryable`1 [Grid4Test .Models .foo] '".
Thanks for your patience.

**Comment by Muchiachio** [comment]
That's the error from your view are you taking `@model IList<Foo>` as a model for your view?

**Comment by ste22g** [comment]
Damn! I modified the Index2 controller but the view was Index3! Thank you.
