### ISSUE TITLE
version 5 rowclicked data name issue.

### ISSUE THREAD

**Issue by SDEBEUL** [NonFactors/MVC5.Grid#143]
Hi,

First of all many thanks for this GREAT library!  

I just updated to the latest version and got an issue with handling the row click events.
in the data of the event names of my columns changes from. ie Tool_Nr to tool_-nr

I trace this back to this [change](https://github.com/NonFactors/MVC5.Grid/commit/6e4c7d691f7cde21e71828d9eabd12382164a83d#diff-4b26824274219a6edae0f6609467211c).
```C#
private String GetName(Expression<Func<T, TValue>> expression)
{
    return String.Join("-", Regex.Split(ExpressionHelper.GetExpressionText(expression), "(?<!^)(?=[A-Z])")).ToLower();
}
```
Is there a reason for adding the `-` ?

**Comment by Muchiachio** [comment]
Yes, grid query moved to lower case and kebab casing for consistency with previously used dashes before filter/sort/paging information, for example `ToolNr-contains=test` now goes `tool-nr-contains`.

I guess it was my mistake to not check other splitting symbols, especially underscore. I should change it, so it doesn't split before underscore at all. If you have a lot of script, best would be to use a custom `AddColumn` extension which preserves old column naming.
