### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by BleuLain** [NonFactors/MVC5.Grid#145]
Hello, good job !,
i have a question, how do you get this filter?
on column  "Marital status"
![issue](https://user-images.githubusercontent.com/43861512/46560059-af02a280-c8c8-11e8-9831-5c5177ce2af8.PNG)
thx

**Comment by Muchiachio** [comment]
It comes from enum values, if the property is an enum. You can also make a list of your own as shown [here](http://mvc-grid.azurewebsites.net/Column/FilterOptions).
