### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by RafaelLiendo2409** [NonFactors/MVC5.Grid#146]
HI,

 I am trying to use Sorting, but is does not work. I click on the columns but the arrows to put "Sort" do not appear.

This is the code:

MVC View:

@model IEnumerable<SIGEMA.Models.Sitios>
@using NonFactors.Mvc.Grid;

@{
    ViewBag.Title = "Index3";
}

<h2>Index3</h2>
<link href="~/Content/MvcGrid/mvc-grid.css" rel="stylesheet">

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.ID).Titled("ID").Sortable(true);
                columns.Add(model => model.Sitio).Titled("Sitio").Sortable(true);

            })
            .Sortable()

)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/JQuery/jquery.js"></script>
    <script src="~/Scripts/MvcGrid/mvc-grid.js"></script>
    <script>
        $('.table').mvcgrid();
    </script>

}

Controller:

        [HttpGet]
        public ActionResult Index3()
        {

            var sitios = db.Sitios.OrderByDescending(x => x.Estado).ThenBy(x => x.Sitio);

            return View( sitios.ToList());
        }

**Comment by Muchiachio** [comment]
Everything looks ok, except `$('.table').mvcgrid();`.
Not sure which version you are using, but grid doesn't add `table` class by default.

**Comment by RafaelLiendo2409** [comment]
Thank you very much, it was a silly mistake from my side.  I am using the NonFactors.Grid MVC 5.
