### ISSUE TITLE
Examples from http://mvc-grid.azurewebsites.net/Grid/Ajax

### ISSUE THREAD

**Issue by senzacionale** [NonFactors/MVC5.Grid#148]
Is it possible to get examples from this site?
http://mvc-grid.azurewebsites.net/Grid/Ajax

It woule be nice to see working examples

**Comment by Muchiachio** [comment]
What do you mean by working examples? That page includes all the needed sources for it to work.
If it's not enough you can check the [project source](https://github.com/NonFactors/MVC5.Datalist.Web) directly.

**Comment by senzacionale** [comment]
By working examples I would like to start them locally.

That would be great. Thank you for the link!
