### ISSUE TITLE
How to Export grid to Excel in MVC

### ISSUE THREAD

**Issue by leeolevis** [NonFactors/MVC5.Grid#15]
MrNonFactors NiHao !

how to export grid to excel in MVC ? I need to include the search criteria
eg：pagesize=10，There are 100 eligible search total result 

I really like your work ! ：）

plese help me, tks

**Comment by Muchiachio** [comment]
你好,

You got here almost in time, I need to make an excel export for one of my clients, so if you can wait for a week or two I may be able to provide an actual "copy paste" example in [documentation page](http://mvc-grid.azurewebsites.net/). Because it's not easy to, given the current implementation.

**Comment by leeolevis** [comment]
谢谢!
Really looking forward tooooo  ^o^

**Comment by Muchiachio** [comment]
Added example to [documentation](http://mvc-grid.azurewebsites.net/Grid/Export) page.

Basically you need to create grid inside the controller, and not in the view.
I used EPPlus as excel library, but you could use anything else, if you like.
If you don't have any special requirements for exported file, you can write a shared helper to iterate all grid columns and it's data and use it from any controller.

**Comment by leeolevis** [comment]
tks

**Comment by ruchit-patel** [comment]
Can you add an example for export in Razor Pages version of asp.net core? @Muchiachio 
It would be of great help.. Thanks in Advance!

**Comment by Muchiachio** [comment]
It's the same concept @ruchit-patel, two actions, one for loading the page and other one for export.
And index page has a model of the grid as in mvc example.

**Comment by ruchit-patel** [comment]
Ohh Thanks A Lot @Muchiachio .. It helped me a lot

**Comment by ruchit-patel** [comment]
Ohh and one more thing.. can i generate a table to export with data from multiples tables in database?

**Comment by Muchiachio** [comment]
It doesn't matter how many tables do you use in a query grid just renders what you pass to it's columns.

**Comment by Muchiachio** [comment]
I don't know how you are doing, but it's usually a select statement into a class, for example
```C#
context.Set<Person>().Select(person => new FullPersonInfoModel
{
    Name = person.Name,
    Address = person.MainAddress.Street + " " + person.MainAddress.HouseNumber,
    LastEmployed = person.Employements.OrderByDescending(emp => emp.Date).FirstOrDefault()
});
```
where main address and employments are joined tables and grid uses `FullPersonInfoModel` as a model.

**Comment by ruchit-patel** [comment]
Ohh.. got it @Muchiachio. Thanks a lot for helping!
