### ISSUE TITLE
Checkboxes which are persisted by paging and sorting

### ISSUE THREAD

**Issue by senzacionale** [NonFactors/MVC5.Grid#150]
I would like to know if is possible to use checkboxes which are persisted by paging and sorting?

Problem is that page is in ajaxgrid mode always rendered and checboxes are lost if you use paging

**Comment by Muchiachio** [comment]
Only if you persist them on every click with a save to the database or similar.

**Comment by senzacionale** [comment]
Do you have an example?

**Comment by Muchiachio** [comment]
No I don't have it. It would just be an ajax call, probably with id and checkbox value, which would update the data you are showing in the grid. So that after the reload checkbox values would be loaded from the data.
