### ISSUE TITLE
Keep filter in AJAX Grid on refresh

### ISSUE THREAD

**Issue by duncangallimore** [NonFactors/MVC5.Grid#154]
First of all, thank you so much for a fantastic control! Not sure what I'd have done without it tbh.
The only (really pretty minor) thing I can't work out how to do is either:
- Keep an applied filter on Refresh
- Add an AJAX refresh button to the grid (I can't work out from the sample how yours works(!)

Apologies if this isn't really an 'issue' - I couldn't find anywhere else to post it.
Many thanks, Duncan

**Comment by Muchiachio** [comment]
- Applied filter is already preserved if you are using grid filters, if you are using ajax grid your search input should be cleared either?
- Sorry there was some artifacts left from yesterday's release, which version you are using? Older ones used `$('.mvc-grid').mvcgrid({ reload: true });` or `$('.mvc-grid').mvcgrid('reload');` to refresh the ajax grid.

**Comment by duncangallimore** [comment]
Thanks for getting back to me so soon.
Example: http://mvc-grid.azurewebsites.net/Grid/Ajax
If you filter for Joe and then refresh the browser, the filter is gone and all results show again.

**Comment by Muchiachio** [comment]
Yes, because it's ajax grid, if you want it to persist filter information on F5 refresh you can use a normal grid which preserves the filter in url and works with refreshes.

**Comment by duncangallimore** [comment]
Okay understood. So what's the easiest way to add a refresh button to the grid? On the example website it seems to be in a separate control above it?

**Comment by Muchiachio** [comment]
Example on the page is showing how to refresh an ajax grid. But if you will use normal one I don't really see a point on making a separate refresh button if browser refresh button or F5 works the same way.

**Comment by duncangallimore** [comment]
I mean to call the ajax reload function

**Comment by Muchiachio** [comment]
As I mentioned above, if you are using older ajax  grid versions
> `$('.mvc-grid').mvcgrid({ reload: true });` or `$('.mvc-grid').mvcgrid('reload');`.

New ones should work with the example provided on the official page, it's now fixed.

**Comment by duncangallimore** [comment]
Okay thanks
And thanks again for a great project
