### ISSUE TITLE
User selected source file - Grid -- loading  data source at runtime 

### ISSUE THREAD

**Issue by weedkiller** [NonFactors/MVC5.Grid#155]
Hello, I see an export to excel. 

User wants to select a file from dir. while browser, then load a excel or CSV file from some dir. while the app is running and filter the file.

How can we load a CSV or Excel file into the grid at runtime?

**Comment by Muchiachio** [comment]
As long as you can pass a valid enumerable to grid construction you could use a file.
So something similar to `Html.Grid(myFile.ToDataEnumerable())`.

Although I'm not sure what would you achieve by using grid on a file? Filtering, sorting or paging would require reopening the file for data and if it's a file from user's computer it might not be available.

**Comment by weedkiller** [comment]
> Although I'm not sure what would you achieve by using grid on a file? Filtering, sorting or paging would require reopening the file for data and if it's a file from user's computer it might not be available.

To answer your question. An external SAP & Oracle, Siebel, system is dropping off csv and excel files hourly in a server directory. `\\myserver\exportedSAPpayrollHours\Vendor`  the power admin user is allowed access because of his role to this directory. 

SAP & Oracle, Siebel, dump files for each vendor in the directories. He browses, loads the file, which he then has to upload, and then filters down was specific data he needs, for e.g. billed hours by a project or a specific resource and then export/save to excel or some other place (I am doing the export already). I liked your grid and wanted to try to fit the loading part.

If you look at some of the other grids, not all but some syncf / kendo allow you import/select load on the fly. But yours is wayyy faster and free.

**Comment by Muchiachio** [comment]
Well it makes it simpler if it's already on the server you just have to convert your csv/excel to data enumerable based on your csv schema or just plain excel columns and use the same
```
public ViewResult Browse(String file)
{
    using (File file = Read(file))
    {
        IEnumerable<YourPocoClass> data = ConvertCsvToEnumerable(file);

        return View(data);
    }
}
```

If you don't have static columns in your files you could leverage `Datatable` or similar data store to render columns dynamically, [here](https://github.com/NonFactors/MVC5.Grid/issues/16#issuecomment-154826539) is an example on that.
