### ISSUE TITLE
rowclick event not working for ajax grid

### ISSUE THREAD

**Issue by sebasijan** [NonFactors/MVC5.Grid#156]
My razor page

    @page
    @model Portal.Pages.Packing.IndexModel

    <div class="row">
        <div class="col-xs-12">
            @(Html.AjaxGrid(Url.Page("IndexGrid")))
        </div>
    </div>

    @section scripts {
    <script>
        $('.mvc-grid tr').on('rowclick', function (e) {
            console.log('data: ', e.detail.data);
            console.log('grid: ', e.detail.grid);
            console.log('original event: ', e.detail.originalEvent);
        });
    </script>
    }

Grid partial

    @page

    @model Portal.Pages.Packing.ConsignmentGridModel

    @{
        Layout = null;
    }

    @(Html
            .Grid(Model.Packages)
            .Build(columns =>
            {
                columns.Add(model => model.PackageId).Titled("ID");
                columns.Add(model => model.Description).Titled("Description");
            })
            .Empty("No data found")
            .Filterable()
            .Sortable()
            .Pageable()
    )

But when I click on a row nothing happens (no error in console, no network errors)

I also noticed there is no hover effect - Should there be one by default? If so perhaps its related to that?

**Comment by sebasijan** [comment]
I can see that there is an event tied to `<tr>` in the DOM viewer:

![capture](https://user-images.githubusercontent.com/13226838/48614190-58dc5100-e996-11e8-891f-9c1c3fb99ff5.PNG)

**Comment by sebasijan** [comment]
It seems it is working for normal grids but not ajax

**Comment by Muchiachio** [comment]
You should use event delegation by binding it on a static parent element or rebinding it after every reload.
I should update example pages to not use `.mvc-grid` as a listening parent, because it gets replaced.

**Comment by sebasijan** [comment]
@Muchiachio Do you happen to have a simple example handy? I'm not sure what 'binding on a static parent element or rebind after reload' means here

**Comment by Muchiachio** [comment]
Your current binding is
```JS
$('.mvc-grid tr').on('rowclick', handle);
```
which translates to `tr element should listen for a rowclick event from itself`, with event delegation you are assigning event handling to a shared static parent
```JS
$('.row').on('rowclick', 'tr', handle);
```
which is `element with a class row should listen for any rowclick event from its tr element children`, it works by keeping event handler on the row div, which doesn't get updated with a new grid content.

**Comment by sebasijan** [comment]
This worked:

    $('.row').on('rowclick', 'tr', function (e) {
        console.log(e.detail.data)
    });

And I also found that this works:

    $(document).on("rowclick", ".mvc-grid tr", function () {
        console.log('click');
    });
