### ISSUE TITLE
Custom paging and sorting

### ISSUE THREAD

**Issue by JanPalasek** [NonFactors/MVC5.Grid#158]
Hi, I ran into a possible bug.

If I choose manual paging in the grid, the grid sorts result I send to him anyway.

If I have 100 entries of strings and use manual paging in the grid with page size 10 and I display the first page. The main advantage of manual sorting is obviously that I can sort and page it in the database, so I send sorted and paged result to the grid.
As I found out, the grid sorts the result I sent to him again. This doesn't seem to be a problem at first, but it is, because sorting in a database can be defined else than sorting in C#.

For example when sorting ascending, NHibernate and Oracle tends to leave null entries at the end of the result, while C# leaves them at the beginning. If I have array of strings ```{ "a", "b", "c", "b", null, "d", null, null, null }``` and I sort it in the database, the ordered result will look like this ```{ "a", "b", "b", "c", "d", null,  null, null, null }```. If we page this with pageSize = 3 and take the second page, then we should get ```{"c", "d", null}``` and the third page should look like ```{ null, null, null }```. However, it seems the framework sorts in C# as well, so the second page will look like ```{ null, "c", "d" }``` (and the third page will contain ```{null, null, null}``` as before). This looks inconsistent, because null entry should be followed up by another null entries, but instead of that it's followed by "c" and "d" and nulls are on the next page.

Imo in case of manual paging there's no reason to sort it by the framework as well.

**Comment by Muchiachio** [comment]
This is true and it works like that, however grid pager and every column is a different `data processor`.
Generally grid runs all the column filters and then sorts (pre) and then paging (post).
So setting manual on pager doesn't change the columns.

The only problem I see now is that grid column doesn't have an extension to set processor type to manual, so it has to be done directly on the column
```
columns.Add(model => model.Name).ProcessorType = GridProcessorType.Manual;
```
I will try adding the necessary extensions in the next release.

**Comment by Bimbinbiribong** [comment]
I think I understand, but why would you ever want to let the framework sort the result if you choose manual paging?

If I have manual paging, in your proposed solution (even with that extension method) I would have to literally write that for every column I have in the grid.

**Comment by Muchiachio** [comment]
There would be a change on `.Sortable` and `.Filterable` extensions too, to avoid "on every column" problem. But yes, having a global grid property for "I will do everything manually" would make the most sense and it is in my backlog for a while now, but for reasons it wasn't done till now.

Manual paging itself was added way after the initial grid API was formed, so I chose the least API breaking way to add manual paging (by adding a new processor type), which resulted in a 4 line change at the time.

Moving forward, maybe next major release, a global change could be made if won't find any edge cases.
Some people actually expect filtering and sorting to work after manual paging, but it's not possible without taking a performance hit on larger tables or even having a semantic change like in your sorting example.

**Comment by abdoneem** [comment]
there is a performance problem on this grid because it execute entire query on database instead of executing only required page query, for example if i want to take top(100) rows with paging

**Comment by Muchiachio** [comment]
No there is not, unless you are giving the grid in memory collection and not a proper `IQueryable`.

**Comment by abdoneem** [comment]
I mean how can I achieve skip rows as part of database query, with sorting and filtering, I tried manual paging but it filter and sort current  page not entire page

**Comment by Muchiachio** [comment]
There's an example on how to do a [manual paging](http://mvc-grid.azurewebsites.net/Grid/ManualPaging). As per this conversation, you also have to make columns manual, and do similar sorting and filtering building in the controller. However filtering is way harder, because of manual parameter parsing needed.

**Comment by abdoneem** [comment]
In manual example there is no filtering or paging option how can I achieve them

**Comment by Muchiachio** [comment]
There is paging option shown in the example page
```C#
[HttpGet]
// Take page and rows values from the query, which are provided from the grid.
public ViewResult Index(Int32? page, Int32? rows)
{
    // Do your own total count on the records, this is the same as writing.
    // `SELECT COUNT(1) FROM YOUR_TABLE`
    ViewBag.TotalRows = PeopleRepository.GetPeople().Count();

    // Do your own paging on the records using the provided page values,
    // they have to be null coalesced, because initial grid doesn't have paging information.
    // This is the same as writing `SELECT * FROM YOUR_TABLE LIMIT 3 OFFSET 0`.
    return View(PeopleRepository.GetPeople().Skip((page - 1 ?? 0) * (rows ?? 3)).Take(rows ?? 3));
}
```
Sorting is basically the same as paging, just that parameters names are `sort` and `order` respectively.
Filtering needs to parsed from `Request.Query`, it is passed in this format
`<grid-name-if-any>-<column-name>-<filter-type>=<filter-value>`

You can check [column grid filter](https://github.com/NonFactors/MVC5.Grid/blob/v6.0.3/src/Mvc.Grid.Core/Filtering/GridColumnFilter.cs#L115) for example parsing.
