### ISSUE TITLE
Grid.MVC

### ISSUE THREAD

**Issue by vipsinghal88** [NonFactors/MVC5.Grid#16]
i am using grid.mvc, when i am passing list than it's working fine , but when i am passing dynamic datatable from controller , than please tell me how can i bind this datatable by grid.mvc , please reply me asap.

**Comment by vipsinghal88** [comment]
for your ref. i am using this grid url ref. : http://mvc-grid.azurewebsites.net/  , please tell me how can i bind dynamic datatable from this grid., reply me asap

**Comment by Muchiachio** [comment]
Could you show me an example of what you are doing in Grid.Mvc, and what doesn't work?

**Comment by vipsinghal88** [comment]
in grid, i am creating dynamic grid, every time column will be changed acc. to configuration , so i am storing data in datatable , when i am passing this datatable from controller , like return view("test",datatable) , now i want to know how can i bind this datatable from this grid

**Comment by vipsinghal88** [comment]
can you please me asap. if you have any solution of my requirement

**Comment by Muchiachio** [comment]
Simply iterate your data with `foreach`, if your project is burning on hell flame :cold_sweat:
It all depends on your data structure, if you have an array of all columns you could write
```C#
for(int col = 0; col < columnCount; col++)
{
    var column = col;
    columns.Add(model => model[column]);
}
```

**Comment by vipsinghal88** [comment]
it's a datatable like datatable dt = new datatable() , ... can you please write full code of view page, i am passing @model System.data.datatable    and  @Html.Grid(Model).Columns(columns =>
      {
    for (int col = 0; col < columns.Count(); col++)
    {
        var column = col;
        columns.Add(model => model[column]);
    }
    });

it's not working

**Comment by vipsinghal88** [comment]
i am facing this  problem :The type or namespace name 'GridMvc' could not be found (are you missing a using directive or an assembly reference?)

**Comment by vipsinghal88** [comment]
while i install this package : Install-Package NonFactors.Grid.Mvc5

**Comment by Muchiachio** [comment]
GridMvc is not my namespace you should include `NonFactors.Mvc.Grid` to your views if needed.

**Comment by vipsinghal88** [comment]
u mean @using NonFactors.Mvc.Grid like that

**Comment by Muchiachio** [comment]
yes

**Comment by vipsinghal88** [comment]
now i am getting this error : The type arguments for method 'NonFactors.Mvc.Grid.MvcGridExtensions.Grid<T>(System.Web.Mvc.HtmlHelper, System.Collections.Generic.IEnumerable<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by vipsinghal88** [comment]
now my code is : @model System.Data.DataTable
@using NonFactors.Mvc.Grid
  @Html.Grid(Model).Columns(columns =>
{
    for (int col = 0; col < columns.Count(); col++)
    {
        var column = col;
        columns.Add(model => model[column]);
    }
});
and in controller i am returning this view like return view("test",datatable)  and i am getting this error : The type arguments for method 'NonFactors.Mvc.Grid.MvcGridExtensions.Grid<T>(System.Web.Mvc.HtmlHelper, System.Collections.Generic.IEnumerable<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.,  please give me solution asap

**Comment by Muchiachio** [comment]
Grid model needs to be generic enumerable, try casting you data table rows to `Model.Rows.Cast<DataRow>()`

I'm unable to create a working sample because of retarded `DataTable` API, which doesn't let me create a data rows by hand...

**Comment by Muchiachio** [comment]
I got it working like so

```C#
@(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column]);
        }
    })
)
```

**Comment by vipsinghal88** [comment]
but it's not showing header of column with filter. please tell me how can i get with column header

**Comment by vipsinghal88** [comment]
and one column is action column where i am defining edit and view link, so please implement with action column also

**Comment by Muchiachio** [comment]
You can find examples on how to set header title in http://mvc-grid.azurewebsites.net/Column/Title.
Rendering links is just adding not encoded stuff like so http://mvc-grid.azurewebsites.net/Column/Encoding.

**Comment by vipsinghal88** [comment]
thanks muchiachio , it's working fine , now i am able to see it, but tell me what about perfomance with this grid, because i will be loaded approx 1 lacs data, how much time it will take to load that data

**Comment by Muchiachio** [comment]
It doesn't take much time if you enable paging and don't load data in memory.

**Comment by vipsinghal88** [comment]
ok thanks , how to apply header css

**Comment by Muchiachio** [comment]
Please read through all the http://mvc-grid.azurewebsites.net/.

**Comment by vipsinghal88** [comment]
and my paging is not working ,   .Pageable(pager =>
            {
                pager.PagesToDisplay = 10;
                pager.InitialPage = 1;
                pager.RowsPerPage = 5;
            })

**Comment by vipsinghal88** [comment]
@(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column]).Titled(column.ColumnName);
        }
    }).MultiFilterable()
    .Filterable()
     .Sortable()
                .Pageable(pager =>
            {
                pager.PagesToDisplay = 3;
                pager.InitialPage = 2;
                pager.RowsPerPage = 2;
            })
    )
paging, sorting , and filter no one is working , i am missing anything here

**Comment by vipsinghal88** [comment]
i am reading your given url, but it's not explaining what i am missing, can you please tell me what i am missing in paging ,sorting and multi filter

**Comment by vipsinghal88** [comment]
please reply friend asap, it's final stage , so please don't leave it without completion ...

**Comment by Muchiachio** [comment]
try adding `.Filterable(true).Sortable(true)` to each column declaration, because they may not be filterable by default.

**Comment by vipsinghal88** [comment]
i have done, but it's not working , i think i need to add any ref here. even paging also not working

**Comment by vipsinghal88** [comment]
it's working see right now i apply for sorting : @(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column]).Titled(column.ColumnName).Sortable(true);
        }
    }).Css("table-hover").Sortable()
    )

it's not working , tell me what i am missing here

**Comment by Muchiachio** [comment]
Did you add mvc grid scripts and initialized grid instances through java script?

**Comment by vipsinghal88** [comment]
i have added this instance : <script type="text/javascript">
    $('.mvc-grid').mvcgrid();
</script>
and these four scripts : <link href="@Url.Content("~/Content/MvcGrid/mvc-grid.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/MvcGrid/mvc-grid.js")"></script>

**Comment by vipsinghal88** [comment]
my view page code is : @model System.Data.DataTable
@using System.Data

@using NonFactors.Mvc.Grid
@{
    ViewBag.Title = "GridTest";
}
<link href="@Url.Content("~/Content/MvcGrid/mvc-grid.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
<script src="@Url.Content("~/Scripts/MvcGrid/mvc-grid.js")"></script>


<script type="text/javascript">
    $('.mvc-grid').mvcgrid();
</script>
<div style="overflow-x:scroll;white-space:nowrap; max-width:1500px;" class="table-responsive">

    @(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column]).Titled(column.ColumnName).Filterable(true).Sortable(true);
        }
    }).Sortable().Filterable()
    )
</div>

**Comment by vipsinghal88** [comment]
i think ,it's not calling your filterable,sortable classes, because here i am binding datatable dynamically , so please give me a suggestion to fix it

**Comment by Muchiachio** [comment]
Don't know then, at least sorting should be working, at least it works for me.
I will check to see why filtering doesn't want to work.

**Comment by vipsinghal88** [comment]
but for me sorting,paging and filtering ,no one is working

**Comment by vipsinghal88** [comment]
did you find out whats issue?

**Comment by Muchiachio** [comment]
Filtering is not working, because `model[column]` returns `object` type, which can not be filtered.
Initializing columns like this `columns.Add(model => model[item].ToString()).Sortable(true).Filterable(true).Named(item.ColumnName);` helps, but `ToString()`'ing is not always supported by the database provider

**Comment by vipsinghal88** [comment]
than whats the solution of this issue, because of this, this grid is useless for me..any solution to fix this issue

**Comment by vipsinghal88** [comment]
now my code is :  @(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column].ToString()).Titled(column.ColumnName).Sortable(true).Filterable(true).Named(column.ColumnName);
        }
    }).Sortable().Filterable()
    )

still it's not working for sorting and filtering

**Comment by vipsinghal88** [comment]
you are owner of this grid, when you are not able to fix this issues, than i don't think anyone can resolve this type of issues,,,please tell me these issues can be fixed or not, otherwise give me suggestion for another grid if you know

**Comment by vipsinghal88** [comment]
do you have any solution of this issue, pleasae tell me

**Comment by Muchiachio** [comment]
If it's useless for you, don't use it.
I ran out of ideas why it is not working on your side.

**Comment by vipsinghal88** [comment]
i am able to see filter button , but when i am clicking on filter button nothing is happening
.please give me a solution my friend, i need urgent

**Comment by Muchiachio** [comment]
If nothing is happening when it's java script error.
Debug it to see what is going wrong.

**Comment by vipsinghal88** [comment]
because it's not calling jquery methods, if it calls jquery methods, and if there is any error, than we can see in browser console, but i am not able to see, it means it's not calling jquery methods

**Comment by Muchiachio** [comment]
Did you call `$('.mvc-grid').mvcgrid();` ?

**Comment by vipsinghal88** [comment]
yes

**Comment by vipsinghal88** [comment]
<script type="text/javascript">
    $('.mvc-grid').mvcgrid();
</script>

**Comment by Muchiachio** [comment]
Debug this line then:
https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L105

**Comment by vipsinghal88** [comment]
actually problem is that when i click on filter button , than its not calling this method, so debug point is not coming here

**Comment by Muchiachio** [comment]
ok then debug initialization https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L12

**Comment by vipsinghal88** [comment]
now it's working , issue was : <script type="text/javascript">
    $(function(){
        $('.mvc-grid').mvcgrid();
    })
</script> , i was not loading on load , i was writing direct without $(function()....but there is problem , when i am sorting data than page is refreshing, can be stop refresh

**Comment by Muchiachio** [comment]
I see you still didn't read http://mvc-grid.azurewebsites.net/Grid/Ajax

**Comment by vipsinghal88** [comment]
thank you so much my friend, it's working now, there is some problem in paging and searching , but i think now i can resolve these type of issues, if i feel there is any issue, than i will ping you , by d way you are very nice guy ... this is vipin singhal , sr. software engineer in HP banglore, can we talk as a friend

**Comment by vipsinghal88** [comment]
hello, as per given url by you, i applied but still it's refreshing , 
main view : @Html.AjaxGrid(Url.Action("GridTestPartial",new { @id = "frmContentALL" }))
controller : return PartialView("_gridTest", result);
partial view :  @(Html
    .Grid(Model.Rows.Cast<System.Data.DataRow>())
    .Build(columns =>
    {
        foreach (DataColumn column in Model.Columns)
        {
            columns.Add(model => model[column]).Titled(column.ColumnName).Sortable(true).Filterable(true);
        }
    }).Css("table-hover").Sortable().Filterable()
    )

**Comment by vipsinghal88** [comment]
hello can you please tell me why filter is not working for this grid, i debug js, but not getting proper issue, it's working without datatable, but for datatable ,it's not working, so please tell me about this issue, how can i fix it?
