### ISSUE TITLE
Problem with row click

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#162]
Hi, 
I want to press any row and get (alert) the Ithe first column data.
Please help me

**Comment by Muchiachio** [comment]
Was [row click binding](http://mvc-grid.azurewebsites.net/Javascript/RowClicked) binding example not enough for your use case?

**Comment by samihatuka** [comment]
In that example, how can I get the age?
Also I tried to replace console.lig to alert, but  it does not work

**Comment by Muchiachio** [comment]
Data is in `e.detail.data`, and age is just `e.detail.data['age']`. You can see the data in F12 too.
Grid does not implement the alert function, so I don't know why it didn't work for you.
