### ISSUE TITLE
Reload (Ajax) if two Grid's?

### ISSUE THREAD

**Issue by ThiloL** [NonFactors/MVC5.Grid#163]
How to reload a mvc-grid (with javascript) if there are two grids on the page? 
`$('.mvc-grid').reload()`
will not work.

**Comment by Muchiachio** [comment]
It's `$('.mvc-grid').mvcgrid({ reload: true });` if you want to reload both.

**Comment by ThiloL** [comment]
Grid is in a separate partial view. If I use the above code from you, it says "Property or method mvcgrid not found".

**Comment by Muchiachio** [comment]
`Property or method mvcgrid not found.` sounds like grid js is not included to me.
Or you are have misconfigured something.

**Comment by Muchiachio** [comment]
> It seems that the code in the partial view cannot use mvc-grid.js code.
Never seen a partial not being able to use layout includes, it's the same html in the end.

If you are using newest grid sources then initialization is
```JS
new MvcGrid(native_html_element);
```
which in jquery translates to
```JS
new MvcGrid($('.mvc-grid')[0]);
```

**Comment by ThiloL** [comment]
Yea. With newest code:` $(...).mvcgrid()` is not working like before, if `new MvcGrid(native_html_element);` was ran before.

**Comment by Muchiachio** [comment]
Yes, because newest version doesn't have jquery dependency and `$.fn.mvcgrid` is not available.

**Comment by ThiloL** [comment]
OK. Thanks.

**Comment by Virgil-z** [comment]
in case someone else runs into this problem, i solved it by creating a function from this in the layout file and calling it when i need a refresh on grids:
 ```
[].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
        new MvcGrid(element).reload();
    });
```

**Comment by wstaelens** [comment]
very annoying that I could not clearly find in release notes that I now have to use `new MvcGrid` instead of `$('.mvc-grid').mvcgrid({` after updating nuget package.

This code below was pretty clean, but doesn't work anymore after upgrading nuget:
```
    $('.mvc-grid').mvcgrid({
      reloadStarted: function () {
        $('#loading').show();
      },
      reloadEnded: function () {
        $('#loading').hide();
      },
      reloadFailed: function () {
        $('#loading').hide();
      }
    });
```
