### ISSUE TITLE
Loading animation

### ISSUE THREAD

**Issue by ThiloL** [NonFactors/MVC5.Grid#164]
There seems to be there is a built-in loading animation in css (`.mvc-grid-loading`). How to use it in partial view with ajax?

**Comment by Muchiachio** [comment]
It should already work in there?

**Comment by ThiloL** [comment]
Unfortunately not. In my view there is a: 
`@Html.AjaxGrid(Url.Action("LongRunning"), new {Name="123"}, new {id="MyID"})`

This loads a 7 seconds, but there comes no load animation. Does something interfere with Bootstrap?

**Comment by Muchiachio** [comment]
Not sure if it's bootstrap, I'm running official page on bootstrap and it works correctly.
Please provide a repro so I can fix the potential issue.

**Comment by ThiloL** [comment]
Check: https://codepen.io/anon/pen/yGKewo
`overflow-x:auto;` on the parent container...

**Comment by Muchiachio** [comment]
Yes, but that's a cut out example, it works fine on [official page](http://mvc-grid.azurewebsites.net/Javascript/ReloadEvents) (try the refresh in the top right corner).

**Comment by ThiloL** [comment]
The **refresh** works, if there is still a Grid. 
**But on initial (first)** load the animation doesn't work, because the Grid has a height near 0.

**Comment by Muchiachio** [comment]
Well yes, I'm not sure what to do with that situation, if you somehow know the height of the which will be loaded, you can set it.
