### ISSUE TITLE
Creating columns dynamically

### ISSUE THREAD

**Issue by RichieGecko** [NonFactors/MVC5.Grid#165]
Is it possible to create column dynamically? My Model is collection and it contain another collection of different field which number depend on type. Is it possible to show this fields dynamically? 

Thanks in advance.

**Comment by Muchiachio** [comment]
Yes, automate `.Build(columns)` call and you will have it.

**Comment by RichieGecko** [comment]
Thank you for really fast response. Could you please give me more information. How can I automate .Build(columns).

**Comment by Muchiachio** [comment]
```C#
.Build(columns =>
{
    foreach (var column in yourDynamicColumnDeclarationList)
        columns.Add(column.Expression).Titled(column.Title); // and so on
})
```

**Comment by RichieGecko** [comment]
When i try to use Add method on columns on that way, I get this error:
The type arguments for method 'IGridColumnsOf<TaskReportViewModel>.Add<TValue>(Expression<Func<TaskReportViewModel, TValue>>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by Muchiachio** [comment]
Well that's a c# error, you can find more information on that in the internet than I can tell you.

**Comment by RichieGecko** [comment]
OK, thank you for theeffort in any case.
