### ISSUE TITLE
Column Width

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Grid#169]
Hi there,

How to custom column width? The column get too big `min-width` when `GridFilterMode.FilterRow`. I tried modify min-width in css, but look like no effect.
![image](https://user-images.githubusercontent.com/5647735/51615819-5b8d9080-1f5b-11e9-8b4b-33d747a98b7f.png)

**Comment by Muchiachio** [comment]
Input has a default size of 20, so even if you lower column width, input has to be minimized too.

**Comment by junrikson** [comment]
Thank You
