### ISSUE TITLE
Grid.MVC

### ISSUE THREAD

**Issue by vipsinghal88** [NonFactors/MVC5.Grid#17]
hello can you please tell me why filter is not working for this grid, i debug js, but not getting proper issue, it's working without datatable, but for datatable ,it's not working, so please tell me about this issue, how can i fix it?

**Comment by Muchiachio** [comment]
Did you find a solution to your problem?

**Comment by vipsinghal88** [comment]
No sir.
    so I hv created my own grid.its working fine

-----Original Message-----
