### ISSUE TITLE
Opendialog with grid

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#170]
Hi,
How can I show this grid in a modal/dialog?
I tried with jQuery opendialog but when I press any button ( like page number) the pop-up closes.
Thank you

**Comment by Muchiachio** [comment]
Maybe it closes because the grid is not ajax, resulting in page reload?

**Comment by samihatuka** [comment]
You mean I have to implement it ajax grid with post data"?You mean I have
to implement this "Reloading ajax grid with post data"?




בתאריך שבת, 2 בפבר׳ 2019, 8:51, מאת Muchiachio <notifications@github.com>:

**Comment by Muchiachio** [comment]
No, you can use ajax grid example instead, it will reload the grid in place instead of reloading the page.

**Comment by samihatuka** [comment]
Thank you. It's working.
