### ISSUE TITLE
Display date column with sort 

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#171]
Hi,
How can I display only date like dd/Mm/yyyy ? 
Thanks

**Comment by Muchiachio** [comment]
`.Formatted("{0:d}")`.

**Comment by samihatuka** [comment]
Thanks , but can you help me with this?
columns.Add(model => model.mydate).Titled("mydate")
.Filterable(true).Sortable(true).Encoded(false).
Formatted("{0:d}").RenderedAs(model => model.mydate.Value.AddDays(180) >
DateTime.Now ? "<span style='color: green';font-size: 11px;>"+ model.mydate
+ "</span>" : (model.mydate.Value.AddDays(180) < DateTime.Now ? "<span
style='color: red';font-size: 1px;>"+ model.mydate + "</span>" : "<span
style='color: #CC4444';font-size: 10px;></span>"));

בתאריך יום ג׳, 12 בפבר׳ 2019, 17:09, מאת Muchiachio <
notifications@github.com>:

**Comment by Muchiachio** [comment]
If you are already using rendered as function, you can do all the formatting in there instead.
