### ISSUE TITLE
How to sort dynamic column

### ISSUE THREAD

**Issue by ThiloL** [NonFactors/MVC5.Grid#172]
Sorting on such a column does not work. Ideas why?

`columns.Add(model => Html.ActionLink(model.Hostname,"PcInfo",new { Hostname = model.Hostname },new { target = "_blank", title = "PcInfo" })).Titled("Hostname").Sortable(true).Named("Hostname");`

**Comment by Muchiachio** [comment]
Probably because model source doesn't support converting `Html.ActionLink` function into sql.
You can use `columns.Add(model => model.Hostname).RenderedAs(model => Html.ActionLink(...))` pattern, to enable sorting on hostname but rendering something different.

**Comment by ThiloL** [comment]
Great.
