### ISSUE TITLE
Missing overload for .Css() extension method

### ISSUE THREAD

**Issue by Runy89** [NonFactors/MVC5.Grid#177]
It will be nice if you would add overload for `.Css("bolded")` grid column extension method. We need to add CSS classes for current cell, not for all column cells. Example:
`.Css(x => x.IsMajor ? "bolded" : "");`

Thanks.

**Comment by Muchiachio** [comment]
You can use row css on grid `.RowCss(x => x.IsMajor ? "bolded" : "")` and have it mapped with particular cell if needed with a css like this `.bolded .yourcell`.

**Comment by Muchiachio** [comment]
Yes, but I don't want to have N x M delegate allocations for this.
