### ISSUE TITLE
Move/Copy paging controls

### ISSUE THREAD

**Issue by jamesmercer** [NonFactors/MVC5.Grid#178]
It would be nice if the paging controls could be moved to above the table if desired.  (And, better yet, allow paging controls both above and below.)  This would make it more likely the user could see the paging controls wherever they are scrolled in the grid.

(I tried simply moving the paging partial in _Grid.cshtml and no such luck.)

**Comment by Muchiachio** [comment]
Moving it in your own grid partial should be enough, why it didn't work?

**Comment by jamesmercer** [comment]
The only change I made to _Grid.cshtml is shown below where I moved the Model.Pager if block to right above the table...

```
...
<div id="@Model.Id" class="mvc-grid" data-name="@Model.Name" data-filter-mode="@Model.FilterMode" data-source-url="@Model.SourceUrl">
    @if (Model.Pager != null)
    {
        @Html.Partial(Model.Pager.PartialViewName, Model.Pager)
    }
    <table@(Model.Attributes)>
...
```
Here is what I see in dev tools when I inspect the page...

```
...
<div class="mvc-grid" data-name="" data-id="0">
<div class="mvc-grid-pager">
        <input class="mvc-grid-pager-rows" type="hidden" value="10">
</div>
    <table>
        <thead>
            <tr class="mvc-grid-headers ">
...
```
Debugging, _Pager.cshtml to try to guess why it is only including a hidden field in the pager, it looks like Model.TotalPages = 0 (and Model.TotalRows = 0) for some reason even though it does go on to show me records in the grid. 

Any ideas?

**Comment by Muchiachio** [comment]
But it works when it's below the table?
