### ISSUE TITLE
Export grid footer partial view

### ISSUE THREAD

**Issue by agromenawer** [NonFactors/MVC5.Grid#179]
Hi! Is it possible to export the footer partial view grid to excel?

**Comment by Muchiachio** [comment]
Non of the partials are exportable to excel, you build excel on your own using grid data.
So if you want to add footer, you would just have to add same cells in excel as in your partial.

**Comment by agromenawer** [comment]
Ohhh, I already thought it was too nice.
So, what is property "grid.FooterPartialViewName" for?

**Comment by Muchiachio** [comment]
It's the partial view to use for rendering the footer html, you can see an [example](http://mvc-grid.azurewebsites.net/Grid/Footer) on how it is used.

**Comment by agromenawer** [comment]
Yes, I'm using it in html but I needed to export to excel the footer too

**Comment by Muchiachio** [comment]
Yes, so you can do the same in excel cell, like
```
sheet.Cells[1, ageColumn].Value = grid.Rows.Average(row => row.Model.Age)
```

**Comment by agromenawer** [comment]
Ok, I'll do it, thanks
