### ISSUE TITLE
Javscript help with this grid

### ISSUE THREAD

**Issue by jhodges13** [NonFactors/MVC5.Grid#181]
I am trying to use Javascript to place an AjaxGrid on an MVC 5 view when the submit button is clicked. I've been hacking away for half a day and made no progress. Can someone offer a tip here? 

this function is called on submit:

    function onbtnSubmit() {
       var sourceurl = 'validpath';   //Points to a MVC controller action, built from serializeform(). 
        var thegrid = new MvcGrid(document.querySelector('.mvc-grid')).;
         thegrid.sourceurl = sourceurl;
         thegrid.reload();
    }

This is on the view:
@Html.AjaxGrid(Url.Action("SNPMemberCarePlanGrid", "Reports"))

**Comment by Muchiachio** [comment]
Theoretically it looks okay, you don't see the request happening or you are getting an error?
Should be easy enough to find a root cause from stepping into reload function.

**Comment by jhodges13** [comment]
This is the full function:
    function onbtnSubmit() {
        if (ValidateReportForm()) {
            var theformdata = $("#TheReportForm").serialize();
            var thesourceurl = '@Url.Action("SNPMemberCarePlanGrid", "Reports")' + '?' + theformdata.replace('"', '');
            var thegrid = new MvcGrid(document.querySelector('.mvc-grid'));
            thegrid.dataSource = thesourceurl;
            thegrid.reload();
        }

        return false;
    }

**Comment by jhodges13** [comment]
> Theoretically it looks okay, you don't see the request happening or you are getting an error?
> Should be easy enough to find a root cause from stepping into reload function.

I'll try that. thanks.
