### ISSUE TITLE
MVC5 Nuget Installation and DLLs

### ISSUE THREAD

**Issue by TorreyGarland** [NonFactors/MVC5.Grid#184]
I manually downloaded all of the required nuget packages for MVC5.  

The javascript, css and cshtml files installed correctly.

Not getting any intellisense for "@Html.Grid" on any of the razor pages. 

Checked references folder:  No dll for Nonfactors.

Nothing in the packages folder for Nonfactors.

Using Visual Studio 2019.

Any suggestions?

**Comment by Muchiachio** [comment]
Try using `@NonFactors.Mvc.Grid.MvcGridExtensions.Grid(Html, Model)` if the page crashes, there is something wrong with references, otherwise it's just buggy intellisense.
