### ISSUE TITLE
MultiFilterable gives js errors

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#187]
Hi, i am currently using Mvc.Grid 6.1.2.
I have a column setup as MultiFilterable. When i want to filter, it gives me  TypeError: e is undefined in mvcgrid.js. and TypeError: parent is null in mvcgrid.js. Buttons to apply or release filter wil not work because of this script error.

I have made a sample project. In this sample project i only get the e is undefined error.

Also on your website http://mvc-grid.azurewebsites.net on sample page MultiFilterable i get the same error. When i filter on age equals to 31 or equals to 33 i get this error in F12 developertools. On your sample page i can click the buttons and filtering will be aplied

Is this something you know about or have a solution for me how to fix it?

Thanks a lot

**Comment by Muchiachio** [comment]
Yes, downgrade to `v6.1.1` for now.
