### ISSUE TITLE
Add a datepicker on date columns?

### ISSUE THREAD

**Issue by JensKlambauer** [NonFactors/MVC5.Grid#188]
http://mvc-grid.azurewebsites.net/Grid/Filtering
- Birthday column
Is it possible to add a datepicker?

Thanks a lot

**Comment by Muchiachio** [comment]
Yes you can by creating your own date filter, there was an example of using jquery ui datepicker [here](https://github.com/NonFactors/MVC6.Grid/issues/175#issuecomment-444996172).

**Comment by JensKlambauer** [comment]
same problem, if i click -> filter popup hide and datepicker is still active on
jquery-ui.js, error  "Uncaught Missing instance data for this datepicker"

next steps in your comment?
- Overriding hide function.
- Unbinding or rebinding window events.
- Binding your date picker popup and preventing event propagation.

**Comment by Muchiachio** [comment]
Did you try them and they didn't work? Not sure what is the question here :confused:
Didn't try others, but overriding hide works.
```JS
var originalHide = MvcGridPopup.prototype.hide;
MvcGridPopup.prototype.hide = function (e) {
    if (!$(e && e.target).parents('.ui-datepicker').length) {
        originalHide.call(this, e);
    }
};

[].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
    new MvcGrid(element);
});
```

**Comment by JensKlambauer** [comment]
sorry, no did not try the steps from the comment

**Comment by JensKlambauer** [comment]
yes your code to overriding hide works.
next problem,  compare equal didn't work

Thanks for your help

**Comment by Muchiachio** [comment]
Make sure your date picker format is the same as the server side date format.

**Comment by JensKlambauer** [comment]
yes i have problem with my german formatted date
`columns.Add(model => model.AntragsDatum).Titled("Antrag Datum").Formatted("{0:dd.MM.yyyy}").InitialSort(GridSortOrder.Desc)`
if i have no datepicker 'equals' also didn't work

Thanks

**Comment by JensKlambauer** [comment]
next problem, the datepicker added the class hasDatepicker to the input textbox
`<input class="mvc-grid-value hasDatepicker" data-filter="first" id="dp1560540723822">`
after apply, the value ist undefined
Request URL: /IndexGrid?antrags-datum-equals=&_=1560541344693
reopen the filter is empty

in your code i found to get the value 
`rowFilter.querySelector('.mvc-grid-value')`
is this the error for this case?

**Comment by Muchiachio** [comment]
It doesn't matter if it has datepicker classes or not. It didn't bound because date picker doesn't dispatch any change or input event after selection, which is needed for the grid to get the value. You can dispatch it your self after date selection or set the value the same as `.bindValues` does.

**Comment by JensKlambauer** [comment]
i use Grid.Mvc5 Version 7.0.0
is a error in my implementation?
'equals', 'later-than', 'earlier-than' didn't work

here my js code,

`var JqueryUIDateFilter = (function (base) {
            MvcGridExtends(JqueryUIDateFilter, base);

            function JqueryUIDateFilter(column) {
                base.call(this, column);

                this.methods = ['equals', 'not-equals', 'later-than', 'earlier-than'];
            }

            JqueryUIDateFilter.prototype.bindValues = function (column) {
                var filter = this;

                base.prototype.bindValues.call(this, column);

                [].forEach.call(filter.popup.element.querySelectorAll('.mvc-grid-value'), function (input) {
                    $(input).datepicker();
                });
            };

            return JqueryUIDateFilter;
        })(MvcGridFilter);

        $(document).ready(function () {
            var originalHide = MvcGridPopup.prototype.hide;
            MvcGridPopup.prototype.hide = function (e) {
                if (!$(e && e.target).parents('.ui-datepicker').length) {
                    originalHide.call(this, e);
                }
            };

            [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
                new MvcGrid(element, {
                    filters: {'date': JqueryUIDateFilter }
                });
            });
        });
`

**Comment by Muchiachio** [comment]
Seems to work on [official page](http://mvc-grid.azurewebsites.net/?birthday-earlier-than=1%2F1%2F1979&sort=birthday&order=asc) and my other projects, can you share a repro?
.

**Comment by JensKlambauer** [comment]
Sorry, the project is on Azure DevOps non public,
possible a Grid localization problem? 
i use german dates, german localization like this  http://mvc-grid.azurewebsites.net/Grid/Localization
i will try make a sample project on github

**Comment by JensKlambauer** [comment]
Samplepage https://geodatendienste.de/samplemvc5grid
datecolumn with Jquery-UI datepicker,  filtering not working
on apply Request URL: IndexGrid?activate-date-equals=&_=1560603265126 -> equals is empty
repo source https://github.com/JensKlambauer/Sample.MVC5.Grid

**Comment by Muchiachio** [comment]
It doesn't work because
> ... date picker doesn't dispatch any change or input event after selection, which is needed for the grid to get the value. You can dispatch it yourself after date selection or set the value the same as .bindValues does.

What I mean by that is that having stuff like this in a form doesn't work
```HTML
<input class="date" />

$('.date').datepicker();
$('.date').on('input', function () {
    console.log("Doesn't get called, there is no way to know when to bound datepicker value");
});
```
