### ISSUE TITLE
Grid.Mvc - Uncaught Error: Grid partial should only include grid declaration.  

### ISSUE THREAD

**Issue by estela72** [NonFactors/MVC5.Grid#189]
I'm having a problem only in Production environment. In development it's ok. Could you help me?
I have this view:
@model IEnumerable<ClasificacionViewModel>
@{

    @foreach (var categoria in Model)
    {
        <style type="text/css">
            @foreach(var premio in categoria.Premios)
            {
                @string.Format(".premio-{0} {{ background-color:{1}; }}  ", premio.Id, premio.ColorName)
            }
        </style>
        <h3><span style="color:darkkhaki">@categoria.Categoria</span></h3>
        @Html.Partial("_ClasificacionReferencias", categoria)
        <hr />
        @Html.Partial("_ClasificacionCategoria", categoria)
    }
}

and each of the partial views are:

@model ClasificacionViewModel
@(Html
    .Grid(Model.Equipos)
    .Build(columns =>
    {
        columns.Add(model => model.Puesto).Titled("-").Encoded(false).RenderedAs(model => "<i class='" + model.Premio?.Simbolo + "'></i><span class='sr-only'></span>" + " " + model.PuestoSinBot);
        columns.Add(model => model.Equipo).Titled("Equipo");
        columns.Add(model => model.Jugados).Titled("J");
        columns.Add(model => model.Ganados).Titled("G");
        columns.Add(model => model.Empatados).Titled("E");
        columns.Add(model => model.Perdidos).Titled("P");
        columns.Add(model => model.GolesFavor).Titled("GF");
        columns.Add(model => model.GolesContra).Titled("GC");
        columns.Add(model => model.Diferencia).Titled("Dif");
        columns.Add(model => model.Puntos).Titled("Puntos");
    })
    .RowCss(model => "premio-" + model.Premio?.Id)
    .Empty("No hay clasificaciones")
    .Id("ajax-grid-clasi")
    .Css("mvc-grid-negrita")
)

@model ClasificacionViewModel
@(Html
    .Grid(Model.Premios)
    .Build(columns =>
    {
        columns.Add(model => model.Simbolo).Titled("-").Encoded(false).RenderedAs(model => "<i class='" + model.Simbolo + "'></i><span class='sr-only'></span>");
        columns.Add(model => model.Descripcion).Titled("Premio");
    })
    .RowCss(model => "premio-" + model.Id)
    .Empty("No hay clasificaciones")
    .Id("ajax-grid-refe")
    .Css("mvc-grid-clasificaciones")
)

The grid is not painted in the web page. And the error **Uncaught Error: Grid partial should only include grid declaration.**  is shown in the console.

Could you help me?

Thanks,

**Comment by estela72** [comment]
don't worry, I found the mistake

**Comment by smanam09** [comment]
@estela72 ,  i'm also getting the same error ? Uncaught Error: Grid partial should only include grid declaration.   How to fix it ?

**Comment by Muchiachio** [comment]
Include only grid partial declaration? Not anything else no divs no html tags just the grid declaration.
