### ISSUE TITLE
how to reload ajaxgrid with new parameter

### ISSUE THREAD

**Issue by ryzam** [NonFactors/MVC5.Grid#19]
Hi

I would like to reload ajaxgrid but with different parameter value. Any example that i can follow.
Tq

**Comment by Muchiachio** [comment]
Does this [example](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch) help in any way?

**Comment by ryzam** [comment]
Ok, tq for the example, but if there are more than one grid on the page how to select which grid to reload?

**Comment by Muchiachio** [comment]
You can add different classes on tables using [Css(...)](http://mvc-grid.azurewebsites.net/Grid/Styling) method and select it from that.
I will expose grid name attribute in the next release, maybe you know a better way?.
```JS
var grid = $('.onegrid').parent().data('mvc-grid');
```

**Comment by ryzam** [comment]
I'm trying to do something like this but got error undefine

var grid = $('.sendonbehalfgrid').parent().data('mvc-grid');

                    grid.mvcgrid({
                        reload: true
                    });

**Comment by Muchiachio** [comment]
Maybe it's still not initialized?

**Comment by ryzam** [comment]
I have my html code like this :

<div class="col-sm-offset-2 col-sm-10">
                                        @Html.AjaxGrid(Url.Action("GetGroupSendOnBehalf", new { samAccountName = Model.SamAccountName }))

                                        
                                        </div>
 </div>

Then my partial view

 @(Html
                                                    .Grid(Model.lSendBehalf)
                                                    .Build(columns =>
                                                    {

                                                        columns.Add(model => model.displayName).Titled("DisplayName");
                                                        columns.Add(model => model.primaryEmail).Titled("Email");
                                                        columns.Add(model => Html.ActionLink("Remove", "RemoveGrantSendOnBehalf", "Groups", new { @id = Model.id, @sendOfBehalf = model.SamAccountName, @samAccountName = Model.SamAccountName }, new { @class = "btn btn-danger" })).Encoded(false);

                                                    })
                                                 .Filterable()
                                                 .Sortable()
                                                 .Css("sendonbehalfgrid")
                                                 .Pageable(pager =>
                                                 {
                                                     pager.RowsPerPage = 50;
                                                 })
                                                 .Empty("No data found"))


And here is my javascript

 $(document).ready(function () {
 var grid = $('.sendonbehalfgrid').parent().data('mvc-grid');

  grid.mvcgrid({
                        reload: true
                    }); 

});

**Comment by Muchiachio** [comment]
And where is your initialization code?
```JS
$('.mvc-grid').mvcgrid();
```

**Comment by ryzam** [comment]
somewhere on the page i have this initialization code, before calling  $(document).ready(...)

<script type="text/javascript">
        $('.mvc-grid').mvcgrid();
    </script>

**Comment by Muchiachio** [comment]
Make sure it happens before your codes.

**Comment by ryzam** [comment]
still no success ...
