### ISSUE TITLE
reloadend not firing

### ISSUE THREAD

**Issue by simone40love** [NonFactors/MVC5.Grid#190]
reloadstart is firing, but reloadend is not firing.
I need reloadend  to fire to get a row count. Is there another way I can get a row count?

var grid = document.querySelector('.mvc-grid');

        // Triggered before grid starts loading
        grid.addEventListener('reloadstart', function (e) {
            alert('start');
        });

        // Triggered after grid stop loading
        grid.addEventListener('reloadend', function (e) {
            alert('end');
            //alert(document.querySelector('.mvc-grid').firstElementChild.rows.length);
        });

**Comment by Muchiachio** [comment]
If your grid is ajax one, you need to use event delegation to listen for reload ended event, because the grid you bound your even on get's destroyed and recreated in the dom.

**Comment by simone40love** [comment]
My grid is not ajax grid. This is the code I use:

  @(Html
        .Grid(Model.Delegates)
        .Build(columns =>
        {
            columns.Add(model => model.Id).Titled("Id").Css("collapse");
            columns.Add(model => model.ProfileUID).Titled("ProfileUID").Css("collapse");
            columns.Add(model => model.VendorEmployeeId).Titled("Employee Id");
            columns.Add(model => model.LastName).Titled("Last Name");
            columns.Add(model => model.FirstName).Titled("First Name");
            columns.Add(model => model.MiddleName).Titled("Middle Name");
            columns.Add(model => model.StatusName).Titled("Status");
            columns.Add(model => model.StartDate).Titled("Start Date").Formatted("{0:d}");
            columns.Add(model => model.TermDate).Titled("Term Date").Formatted("{0:d}");

        })
        //.AjaxGrid(Url.Action("IndexGrid"))
        .Empty("No data found. Do you need to add this delegate? Click the button to go to the Add screen.")
        .Filterable()
        .Sortable()
        .Css("css-classes") // Overwrites all classes with the new ones
        .AppendCss("table-hover") // Appends classes to the current ones
        .Pageable(pager =>
        {
            pager.RowsPerPage = 10;
        })

**Comment by Muchiachio** [comment]
Reload ended is not fired on normal grid, because there is no reload of the grid, you can just write your code inline so it executes on page refresh.
