### ISSUE TITLE
Row select using right click? 

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#194]
Is there anyway i can get the row data by using right click?

Edit: Thank you for this super-flexible grid.

**Comment by Muchiachio** [comment]
You could do the same row to data conversion grid does.
```JS
var data = {};
var row = clicked_row_element;
var grid = new MvcGrid(element);

grid.columns.forEach(function (column, i) {
    data[column.name] = row.cells[i].innerText;
});
```

**Comment by dheoxic** [comment]
Do I implement your code in here?
`document.addEventListener('rowclick', function (e) {
    . . . .
});`

or in a separate function that listens to a right click event?

**Comment by Muchiachio** [comment]
You add it in your own right click listener.

**Comment by dheoxic** [comment]
Got it. Thanks.
