### ISSUE TITLE
.toggleClass/.addClass not working well with paging

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#197]
Been using your grid for a while now and i'd say it saves me a lot of work when it comes to data processing, and is actually much better than other grid extensions out there.
I'm just having this issue with `toggleClass` and `addClass`, paging seems to remove the added class to the selected.
Am i missing something? Thanks in advance.

Code below
`$(document).on("rowclick", "#thegrid tr", function (e) {`
`            $(this).addClass('selected').siblings().removeClass('selected');`
`            //data processing`
`});`

**Comment by Muchiachio** [comment]
It's not client sided grid, so every page reload the html, thus losing classes.
