### ISSUE TITLE
Total columns in the header

### ISSUE THREAD

**Issue by estela72** [NonFactors/MVC5.Grid#200]
Hello

Is it possible to put the 'footer' as the first or second row of the grid?

It's very important for me!

Thanks!

**Comment by Muchiachio** [comment]
You can change layout with your custom view.
```C#
Html.Grid(Model, "_MyGridPartial")
```

**Comment by estela72** [comment]
Ok, I'm not sure how to use custom view, could you give me an example?

Thanks!

**Comment by Muchiachio** [comment]
http://mvc-grid.azurewebsites.net/Grid/Partial

**Comment by estela72** [comment]
Oh! I see! thank you very much! I will try!
