### ISSUE TITLE
.Hidden() alternative

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#201]
Is there any way i can do the `.Hidden()` extension like `.Hidden(false|true)`?

**Comment by Muchiachio** [comment]
No, you would have to create extension for your use.

**Comment by dheoxic** [comment]
Oh I see. Would love to see it as a feature if possible. Thanks anyway.

**Comment by Muchiachio** [comment]
What's the point though? Currently there is only back end support for hiding the column, and you can't unhide it through any UI. So using `.Hidden()` is almost the same as not adding column at all.

**Comment by dheoxic** [comment]
I have an external search which depends on the user's lookup choice. 
My grid datasource is like this:
`public class ViewModel{`
`public bool HideUnhide{get;set;}`
`public IEnumerable<GridData> GridData {get;set;}}`

and in my partial view:
`@(Html.Grid(Model.GridData )`
`                            .Build(columns =>{`
                                `columns.Add(m => m.columnA).Titled("Column Title").Hidden(Model.HideUnhide);`

`HideUnhide` will be set based on what the user chooses as search option.

**Comment by dheoxic** [comment]
I can do it using some hacky client-side jquery and css but i want to do less of it as much as possible

**Comment by Muchiachio** [comment]
Would still go with
```
if (Model.HideUnhide)
    columns.Add(m => m.columnA).Titled("Column Title");
```
Less html to be rendered if you are not planning to unhide dynamically.
