### ISSUE TITLE
Resize columns (request)

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#202]
Our company requires resizable columns for our grids. 

I wrote a small script to adjust the columns. For usability i append a span inside the th which will show a grip handle on hover over the th. Because the MvcGrid sort click event is bounded to the table header the column get's sorted each time i drag my handle for resizing. Now i adjusted the script a litte so the click event is set to the mvg-grid-title and sort button. Ofcourse it's not done to adjust the script so the question i have is, if it's possible for you guys to set the sort on the title instead of the whole th, or create a resize column feature. 

Thanks a lot 

Talsja

**Comment by Muchiachio** [comment]
You should be able to prevent event propagation when clicking on your handle.
Similarly to how it is currently done [on sorting](https://github.com/NonFactors/MVC5.Grid/blob/v7.0.0/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L521-L525).
