### ISSUE TITLE
localization not working

### ISSUE THREAD

**Issue by ronnahmias** [NonFactors/MVC5.Grid#205]
hi
I have try to insert localization but in startup.cs the Localize("true");
doesnt recognize..

This is what I have Tried:
```
public partial class Startup
{
    public void Configuration(IAppBuilder app)
    {
        ConfigureAuth(app);
        (MvcGrid.Filters as GridFilters).BooleanTrueOptionText = () => **Localize("true")**; // This is Error
    }
    
}
```

**Comment by ronnahmias** [comment]
Sorry I didnt understand you..
I only want that in the grid there will be other language

**Comment by Muchiachio** [comment]
I updated the examples, so they can be copy pasted.
