### ISSUE TITLE
mvc-grid.js does not recognize 2 two distinct grids on custom grid partial

### ISSUE THREAD

**Issue by vinicius83** [NonFactors/MVC5.Grid#206]
Hello Muchiachio I have a problem with custom grid partial. When I click on the grid, a javascript error occurs.

> 0x800a138f - JavaScript runtime error: Unable to get property 'innerText' of undefined or null reference

In
>        [].forEach.call(grid.element.querySelectorAll('tbody tr'), function (row) {
>                 if (!row.classList.contains('mvc-grid-empty-row')) {
>                     row.addEventListener('click', function (e) {
>                         var data = {};
> 
>                         grid.columns.forEach(function (column, i) {
>                             data[column.name] = row.cells[i].innerText;
>                         });
>                    ...

My grid in view have 7 columns and in partial have 4 columns. Whenever you pass this code, the grid has 8 columns.  
The error occurs because the number of columns in "grid" (8)  is different from columns in row (4).

The only difference I have is that in partial view I don't have the partial name call inside .Grid (....) because this causes me another error, could this be the problem?

Thanks a lot, I admire your work.

**Comment by Muchiachio** [comment]
No the problem is that it can't map out merged rows. Will see if I can use column names to create a data map. I don't see any other way how to solve that from my side.

**Comment by vinicius83** [comment]
Thank you for your support.
