### ISSUE TITLE
Paging with data

### ISSUE THREAD

**Issue by rosauro** [NonFactors/MVC5.Grid#207]
Hi everyone, 

I have thousands of data, around 8000.
Loading all data, it's too slow, so I paged the load and I only send to the grid 20 rows.
Setting the value to show only 2 rows per page, the last page is page 10.
How can I do to get the last page the corresponding page with all the total data?

I mean, I have 8000 data and I only show 2 per page, the last page should be page
 4000 instead of page 10.

Any suggestion is welcome. Thanks!

**Comment by Muchiachio** [comment]
If you are doing [manual paging](http://mvc-grid.azurewebsites.net/Grid/ManualProcessing), you need to set total rows, for the pager to render correctly.

**Comment by rosauro** [comment]
Thanks a lot!
Now it's working like a charm.

That's the code was I missing:
`.UsingProcessingMode(GridProcessingMode.Manual)`

**Comment by rosauro** [comment]
using `GridProcessingMode Manual`, and `Filterable()`, filters doesn't work, 
Is it possible to filter the grid with manual paging? 

Thanks in advance.

**Comment by Muchiachio** [comment]
No, everything becomes manual because you are possibly manipulating hand written query if you do manual paging.
