### ISSUE TITLE
Grid header dynamic name

### ISSUE THREAD

**Issue by mustaqueahmad** [NonFactors/MVC5.Grid#208]
Hi,

I am using this Grid. This is excellent. only thing I am trying to make dynamic header. Based on variable value, I want to set Header name. Please help on this.

Thanks in Advance.
Mustaque

**Comment by Muchiachio** [comment]
What does `.Titled` function not provide for your needs?

**Comment by mustaqueahmad** [comment]
Thanks for the reply. .
.Titled is for static string value. I want variable string value.

**Comment by Muchiachio** [comment]
Who stops you from passing variable into a function in c#?

**Comment by mustaqueahmad** [comment]
for example I am trying to fetch @ViewBag.Header1 inside .Titled

**Comment by Muchiachio** [comment]
Seem's like you are running into [this](https://stackoverflow.com/questions/8057751/pass-a-dynamic-variable-in-a-static-parameter-of-a-method-in-c-sharp-4).

**Comment by mustaqueahmad** [comment]
Thanks for the reply.
Not that.
 Columns.Add(c => c.Asset.Model.Name).Titled("Model").Filterable(true); 

 Actually here I am using "Model" as header name but I am trying to set variable value in .Titled(@ViewBag.Header1). is it possible here.

**Comment by Muchiachio** [comment]
Yes and it doesn't work because of the link I provided you.
You can't implicitly pass dynamic object into a statically typed function.

**Comment by mustaqueahmad** [comment]
ok, thanks for the clarification.
