### ISSUE TITLE
How to make a custom filter with more than two parameters

### ISSUE THREAD

**Issue by Draw507** [NonFactors/MVC5.Grid#21]
![image](https://cloud.githubusercontent.com/assets/5288627/12200400/b01e6b0a-b5ec-11e5-9720-951b6e2a6ff0.png)

**Comment by Muchiachio** [comment]
By creating and registering and applying your [own filter](http://mvc-grid.azurewebsites.net/Filter/Register).

**Comment by Draw507** [comment]
I tried to implement this:

JS

var CustomTextFilter = (function () {
    function CustomTextFilter() {
    }

    CustomTextFilter.prototype = {
        render: function (popup, filter) {
            popup.html(
                '<div class="popup-arrow"></div>' +
                '<div class="popup-content">' +
                    '<div class="first-filter popup-group">' +
                        '<input class="mvc-grid-input" placeholder="Contains" type="text" value="' + filter.first.val + '">' +
                    '</div>' +
                    (filter.isMulti ?
                    '<div class="popup-group popup-group-operator">' +
                        '<select class="mvc-grid-operator">' +
                            '<option value=""></option>' +
                            '<option value="And"' + (filter.operator == 'And' ? ' selected="selected"' : '') + '>And</option>' +
                            '<option value="Or"' + (filter.operator == 'Or' ? ' selected="selected"' : '') + '>Or</option>' +
                        '</select>' +
                    '</div>' +
                    '<div class="second-filter popup-group">' +
                        '<input class="mvc-grid-input" placeholder="Contains" type="text" value="' + filter.second.val + '">' +
                    '</div>' +
                     '<div class="popup-group popup-group-operator">' +
                        '<select class="mvc-grid-operator">' +
                            '<option value=""></option>' +
                            '<option value="And"' + (filter.operator == 'And' ? ' selected="selected"' : '') + '>And</option>' +
                            '<option value="Or"' + (filter.operator == 'Or' ? ' selected="selected"' : '') + '>Or</option>' +
                        '</select>' +
                    '</div>' +
                    '<div class="third-filter popup-group">' +
                        '<input class="mvc-grid-input" placeholder="Contains" type="text" value="' + filter.third.val + '">' +
                    '</div>' :
                    '') +
                    '<div class="popup-button-group">' +
                        '<button class="btn btn-success mvc-grid-apply" type="button">✔</button>' +
                        '<button class="btn btn-danger mvc-grid-cancel" type="button">✘</button>' +
                    '</div>' +
                '</div>');
        },

        init: function (grid, column, popup) {
            this.bindType(grid, column, popup);
            this.bindValue(grid, column, popup);
            this.bindApply(grid, column, popup);
            this.bindCancel(grid, column, popup);
            this.bindOperator(grid, column, popup);
        },
        bindType: function (grid, column, popup) {
            column.filter.first.type = "Contains";
            column.filter.second.type = "Contains";
            column.filter.third.type = "Contains";
        },
        bindValue: function (grid, column, popup) {
            var firstValue = popup.find('.first-filter .mvc-grid-input');
            firstValue.bind('keyup.mvcgrid', function (e) {
                column.filter.first.val = this.value;
                column.filter.first.type = "ContainsString";
                if (e.keyCode == 13) {
                    popup.find('.mvc-grid-apply').click();
                }
            });

            var secondValue = popup.find('.second-filter .mvc-grid-input');
            secondValue.bind('keyup.mvcgrid', function (e) {
                column.filter.second.val = this.value;
                column.filter.second.type = "ContainsString";
                if (e.keyCode == 13) {
                    popup.find('.mvc-grid-apply').click();
                }
            });

            var thirdValue = popup.find('.third-filter .mvc-grid-input');
            thirdValue.bind('keyup.mvcgrid', function (e) {
                column.filter.third.val = this.value;
                column.filter.third.type = "ContainsString";
                if (e.keyCode == 13) {
                    popup.find('.mvc-grid-apply').click();
                }
            });
        },
        bindApply: function (grid, column, popup) {
            var apply = popup.find('.mvc-grid-apply');
            apply.bind('click.mvcgrid', function () {
                popup.removeClass('open');
                grid.reload(grid.formFilterQuery(column));
            });
        },
        bindCancel: function (grid, column, popup) {
            var cancel = popup.find('.mvc-grid-cancel');
            cancel.bind('click.mvcgrid', function () {
                popup.removeClass('open');
                grid.reload(grid.formFilterQueryWithout(column));
            });
        },
        bindOperator: function (grid, column, popup) {
            var operator = popup.find('.mvc-grid-operator');
            operator.bind('change.mvcgrid', function () {
                column.filter.operator = this.value;
            });
            operator.change();
        }
    };

    return CustomTextFilter;
})();

C#

public class CustomFilter : BaseGridFilter
    {
        public override Expression Apply(Expression expression)
        {
            return Expression.Equal(expression, Expression.Constant(null));
        }
    }

Application_Start

MvcGrid.Filters.Register(typeof(String), "ContainsString", typeof(CustomFilter));
When I register "ContainsString" search is not accomplished:

?Grid-SHORT_NAME-ContainsString=A&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-ContainsString=B&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-ContainsString=C

Without use the Filter.Register the search is accomplished whith only two parameters:
?Grid-SHORT_NAME-Contains=A&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-Contains=B&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-Contains=C

**Comment by Muchiachio** [comment]
Yes because default [formFilterQuery](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L219) doesn't know anything about third filter.
You could use [addOrReplace](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L303) to form your own query.

**Comment by Muchiachio** [comment]
If you will have any feedback on implementing and extending default filters feel free to write them down, so I can improve the grid based on your feedback. :+1:

**Comment by Draw507** [comment]
if I use addOrReplace to build the query, I need to use &Grid-COLUMN-Op=Or& to unite the values of search?
I would like to search multiple values for a column, for this is just modify the query by js? How this works in conjunction with registration?
I create this query directly:
?Grid-SHORT_NAME-Contains=CITI&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-Contains=BBVA&Grid-SHORT_NAME-Op=Or&Grid-SHORT_NAME-Contains=KOREA
and ignores the third parameter

**Comment by Muchiachio** [comment]
Yes it is ignored, now that your client side knows about the filter you need to make the server know about it too, because [grid filters](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid.Core/Filtering/GridFilters.cs#L110) only applies up to two filters at a time.

You can overwrite it with `MvcGrid.Filters = new CustomGridFilters()`.
And [let your own grid filter implementation handle the filtering](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid.Core/Filtering/GridColumnFilter.cs#L15).
