### ISSUE TITLE
Multi Filter Problem

### ISSUE THREAD

**Issue by Roi467** [NonFactors/MVC5.Grid#210]
hello :) I have tried to add multi filter
but its not working

`columns.Add(model => model.Statuss).Titled(Html.DisplayNameFor(s => s.Statuss)).Filterable(true).Filterable(GridFilterType.Multi);`

tnx :)

**Comment by Muchiachio** [comment]
Normal filter working but not the multi one? What is the type of `Statuss`?

**Comment by Roi467** [comment]
yes the normal filter is working
ths `Statuss` is string type

**Comment by Muchiachio** [comment]
Maybe you have old content files, js/css/views everything up to date with the dll version you are using?
If yes, please share a small repro so I can take a look, because I can't repro on examples web site.

**Comment by Roi467** [comment]
the dll is update
but never mind I used  another option
