### ISSUE TITLE
Pager hiding options

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#211]
Is it possible to only show the pager if the grid data source exceeds a certain number of rows?

**Comment by Muchiachio** [comment]
It's possible with custom pager partial.

**Comment by dheoxic** [comment]
Is there an example in the documentation?

**Comment by Muchiachio** [comment]
Pager partial no, it's the same as grid partial though you copy `\MvcGrid\_Pager.cshtml` to your own file, change whatever you need and then specify it in pager options.
```C#
.Pageable(pager =>
{
    pager.PartialViewName = "_MyGridPagerPartialPath";
}
```

**Comment by dheoxic** [comment]
Thank you for the idea. I ended up modifying the `_Pager.cshtml` file and putting the code below:
```
<div class="mvc-grid-pager @Model.CssClasses @(Model.TotalRows <= 10 ? "force-hide":"")" 
            data-show-page-sizes="@Model.ShowPageSizes"> . . . . .

<style>
.force-hide{
    display: none;
}
</style>
```

and ended up getting the results i wanted. Will this have any bad effect on the `.Pager(...)` property of the grid?

**Comment by Muchiachio** [comment]
Modifying library assets directly is risky, because the next time you update the grid you have to not forget to reapply your changes.

**Comment by dheoxic** [comment]
I see. This will probably break my layout when you release a major update. I will go with your first suggestion with the custom pager partial. Thank you.
