### ISSUE TITLE
How to change column width

### ISSUE THREAD

**Issue by simone40love** [NonFactors/MVC5.Grid#212]
The columns all seem to be 200px. How do I change so I can make the description column bigger? I want it to be 400 px.

@model IEnumerable<Database.Models.vw_DelegateVendor>
@* Should only include grid declaration *@
@(Html
                    .Grid(Model)
                    .Build(columns =>
                    {
                        columns.Add(model => model.Id).Titled("Id").Css("collapse");
                        columns.Add(model => "<i title='Edit Vendor'  class='fas fa-edit fa-lg font-awesome-icon' onclick=\"location.href='Update?id=" + model.Id + "'\"></i>").Encoded(false);
                        columns.Add(model => model.Name).Titled("Name");
                        columns.Add(model => model.Active).Titled("Active");
                        columns.Add(model => model.Description).Titled("Training Description").Css("col-size");
                    })
                    .UsingFooter("_GridFooter")
                    .Filterable()
                    .Sortable()
                    .Css("css-classes") // Overwrites all classes with the new ones
                    .AppendCss("table-hover") // Appends classes to the current ones
                    .Pageable(pager =>
                    {
                        pager.RowsPerPage = 20;
                    })
                    .Id("vendor-grid")
                    .Named("vendor-grid")
)

**Comment by Muchiachio** [comment]
By default column just auto resize based on html table. Recommended way to do it is to used a css styling rule on the column.
```css
.col-size {
    width: 100px;
}
```
