### ISSUE TITLE
footer throw exception while no rows in table

### ISSUE THREAD

**Issue by ronnahmias** [NonFactors/MVC5.Grid#213]
hello,

I have added footer to table but when I use filter on on of the columns and there is no data to see the partial view throw exception.
how to check in the partial view if the model doesnt have parameters to see just skip the partial view?
I have tried to check if(Model != null) but the Model is always not null

partial view:

> @using DataEntities;

> @model IGrid<SpSocio>

> @if` (Model != null)

> {
>  <tr>
>         <td colspan="2"><b>ממוצע כללי</b></td>
>         <td><b>@(Model.Rows.Average(row => row.Model.AvgIncome))</b></td>
>         <td><b>@(Model.Rows.Average(row => row.Model.AvgExpense))</b></td>
>         <td></td>
>     </tr>
> }

**Comment by Muchiachio** [comment]
You have to check `Model.Rows.Any()`.

**Comment by ronnahmias** [comment]
Thanks! 
Is there a Way to do the table responsive in bootstrap?

**Comment by Muchiachio** [comment]
Bootstrap uses css to achieve responsiveness, you can apply your own css through
`IHtmlGrid.Css(...)` and `IHtmlGrid.Attributed(...)` functions.
