### ISSUE TITLE
Model with List

### ISSUE THREAD

**Issue by DirkMolman** [NonFactors/MVC5.Grid#215]
I'm trying to create a view showing model detail information and also data in a grid.

public class Person()
{
	int Id { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	**public List<Travel> TravelsList { get; set; }**
}

public class Travel()
{
	int Id { get; set; }
	public string Country { get; set; }
	public DateTime From { get; set; }
	public DateTime Until { get; set; }
}

View
@model Travel.Data.Models.Person

	@(Html
		**.Grid(Model.TravelsList)**
		.Build(columns =>
		{
			columns.Add(model => model.Name).Titled("country");
		})
		.Empty("No travels")
		.Filterable()
		.Sortable()
		.Pageable()
	)
	
'HtmlHelper<Person>' does not contain a definition for 'Grid' and no accessible extension method 'Grid' accepting a first argument of type 'HtmlHelper<Persoon>' could be found 
(are you missing a using directive or an assembly reference?)

Is this silly what I want to achieve?
I have checked the examples, but cannot find a solution.

**Comment by Muchiachio** [comment]
It should work. Does any grid work? Is `NonFactors.Mvc.Grid` namespace included in the view?

**Comment by DirkMolman** [comment]
You were spot on. The namespace was not included.
Thanks for the quick response.
