### ISSUE TITLE
Question: How to Prevent Ajax Grid on Initial Page Load

### ISSUE THREAD

**Issue by TorreyGarland** [NonFactors/MVC5.Grid#216]
My apologies if this has been answered already.

I have an Ajax Grid on a page, but I don't want it to load during the initial load of a page.  It is initially hidden and I only want it to make its Ajax call after it has been displayed by user action.

Is there a JavaScript solution for this, such as "preventDefault()"?

**Comment by Muchiachio** [comment]
If you don't want it to load don't call or delay calling `new MvcGrid(element)`. If you have some global initialization then your only option is to hide it in a container until user takes action.

**Comment by TorreyGarland** [comment]
Trying it out now.

**Comment by TorreyGarland** [comment]
Worked like a champ!!!

Thanks for the speedy response.
