### ISSUE TITLE
Question: Reloaded event trigger

### ISSUE THREAD

**Issue by NathalieSpierings** [NonFactors/MVC5.Grid#218]
I have a global script where i initialize each grid and have the reloadstart, reloadend and reloadfail events.  Now i have a page with a grid on it and a empty-data div. When there's no data i do not render the MvcGrid but instead i render the empty-data div with a button to create a first item.

I have a sidebar in which i load content true ajax. In the above case i will load a form with a textbox and a save button. As soon i start typing in my textbox i see in the browsers developerstools a js error:
Grid element was not specified. 

This means that somehow my typing in the textbox triggers MvcGrid.

When i have already items and thus MvcGrid is rendered, and i create a new item in my sidebar loaded content, i can see that the reloaded event get's triggered when i start typing in my textbox.

Is there a way to prevent this? Or why is this triggering the reloaded event?

Thank you

**Comment by Muchiachio** [comment]
It should be visible from the stack trace who invoked the grid constructor.
Or check the event listeners on the textbox, maybe some lose event handler is initializing grid.

**Comment by NathalieSpierings** [comment]
Yes you are totally right. I have found an on keyup function for the global search input which get triggerd. So i will look at that function again. Thank you for your support
