### ISSUE TITLE
MVC Grid bug inside bootstrap modal

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#219]
![image](https://user-images.githubusercontent.com/50933655/69767141-cf20af80-11b5-11ea-8364-1c7f5b73f24e.png)

The text input inside the dropdown filter option gets disabled when the grid element is inside bootstrap modals. Tested on bootstrap ver 3.x

**Comment by Muchiachio** [comment]
So grid disables it?

**Comment by dheoxic** [comment]
I'm not sure if it disables it. Clicking the input doesn't put the focus on it. Tried re initializing the grid on modal shown event but still same thing happens. Apart from that, all grid features work properly

**Comment by Muchiachio** [comment]
I remember rising z-index on the modal itself, maybe bootstrap increased it again.

**Comment by dheoxic** [comment]
The dropdown for the filter options works properly, except for text input which you cannot enter text.

**Comment by Muchiachio** [comment]
Seems to work with bootstrap 4. As for v3 I found that `tabindex="-1"` on the bootstrap modal is preventing the focus, even though grid filter is rendered outside the modal. I have no idea how to fix it.

**Comment by dheoxic** [comment]
I'm closing this since I switched to a different filter mode. I'll try to meddle with the source files and hit you up if i find something. Overall, a great plugin. Thanks.
