### ISSUE TITLE
Questions & propositions

### ISSUE THREAD

**Issue by boukenka** [NonFactors/MVC5.Grid#22]
Hello,

I have 3 questions:

A) Is it possible to add an extension on column level to define the width for a particular column? (It is possible today by CSS)
```C#
@(Html.Grid(Model).Named("PersonGrid")
    .Build(columns =>
    {
        columns.Add(model => model.X).Width(250);
    })
    .Filterable()
 ``` 

B) Is it possible to add an extension on grid level to define the height of all rows? (It is possible today by CSS)
```C#
@(Html.Grid(Model).Named("PersonGrid")
    .Build(columns =>
    {
        columns.Add(model => model.X)
    })
    .Height(150)
    .Filterable()
```
C) To come back to my previous issue/question and after reading some articles on unobtrusive method, I have tried to replace:
```C#
columns.Add(model => Html.Hidden("")).Titled("Action").Encoded(false).RenderedAs(model => 
"<a onclick='suppress(event," + model.Id + ");return false;'>Remove</a>");
```
by 
```C#
columns.Add(model => Html.Hidden("")).Encoded(false).
RenderedAs(model => "<a id='removegrid' >" + model.Id + "</a>");
```
with:
```JS
$('body').on('click', '#removegrid', function (e) {
    alert('Hello');
    e.stopPropagation();
    return false;
});
```
Or the grid event for clicking the row is always fired even there is the following coding:
```JS
$('.mvc-grid-row a').on('click', function (e) {
    e.stopPropagation();
    return false;
});
```
Do you have a solution?

Thanks

**Comment by Muchiachio** [comment]
A) I do it with css classes, I'm wondering if width is widely used
```C#
columns.Add(model => model.X).Css("default-width")
```
B) yes you can write your own extensions, but row styling would be enough here
```C#
.Build(columns =>
{
    columns.Add(model => model.X)
})
.RowCss(model => "default-height")
```
C) Strange, I tried `stopPropagation` and it works as expected, anchor click is fired. And if you tell the event to stop propagating, it doesn't bubble to more generic row event.

**Comment by boukenka** [comment]
Hello,

Thanks for the answers.

For C, I have updated my coding to make it more accurate. It is still not working for me. The row click event is still fired. Could you provide an example with more coding please?

**Comment by boukenka** [comment]
Good evening,

Are you Ok with my request? If yes, do you think it will be possible soon? (Just a simple project or an addition to the demo web site)

**Comment by Muchiachio** [comment]
Yes, in an hour or so, just got home :smile:

**Comment by Muchiachio** [comment]
This works for me
```C#
@(Html
    .Grid(new Object[] { 1, 2, 3, 4 })
    .Build(columns =>
    {
        columns.Add(model => model).Titled("Value");
        columns.Add(model => "<a href='#'>Remove</a>").Encoded(false).Titled("Action");
    })
    .Filterable()
    .Sortable()
)
<script>
    $('.mvc-grid').mvcgrid({
        rowClicked: function () {
            console.log('This is called, because it was not stopped.');
        }
    });
    $('.mvc-grid-row a').on('click', function (e) {
        console.log('Stopping event propagation');
        e.stopPropagation();
    });
</script>
```

**Comment by boukenka** [comment]
Thanks for the support. But unfortunately this is how it is implemented for me below:

```JS
$('.mvc-grid').mvcgrid({
        rowClicked: function (grid, row, data) {
            ....
            alert('first');
 ...
```
```JS
$('.mvc-grid-row a').on('click', function (e) {
        alert('Too late');
        e.stopPropagation();
    });
```

The first popup is always 'first' and not 'Too late'. Or what is required is the opposite.
One solution would be have to have the event 'cellClicked'.From the content of the cell (position or content), the action will be different. Or another solution?

**Comment by Muchiachio** [comment]
I can't understand how is the above not working? Maybe you are not clicking on the anchor tag? :smiley:
If you want cell clicked, you can bind to `'.mvc-grid-row td'` or expand anchor tag to cover the cell.

**Comment by boukenka** [comment]
Good morning :smiley:

I am clicking on the anchor tag. But what is fired first is the event associated '$('.mvc-grid')' and not the event associated to $('.mvc-grid-row a') which is fired after. So I get 'first' pop-up and not 'Too late' at the beginning if I click the Anchor tag. Is there a possibility to by code to have the following?

```JS
$('.mvc-grid').mvcgrid({
    rowClicked: function (grid, row, data) {
        var celltext = ...columWhichHasBeenClicked().Tex():
        alert('Here is what has been clicked' + celltext);
```

From there (from identification of the selected cell) it could be implemented a different behaviour/action according to the selection. What do you think? Sorry to bother you with that issue.

**Comment by Muchiachio** [comment]
You can know the source of an event by using `e.target || e.srcElement`, too bad I don't pass that information back to you :disappointed: Maybe you can bind your own `on td click` and loading the data in the similar way the [grid does](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L330)?

**Comment by boukenka** [comment]
Would it be possible to make another release of the MVC Grid including the following change below?
```JS
 bindGridEvents: function () {
            var grid = this;
            this.element.find('.mvc-grid-row').on('click.mvcgrid', function (e) {
                if (grid.rowClicked) {
                    var cells = $(this).find('td');
                    var data = [];

                    for (var ind = 0; ind < grid.columns.length; ind++) {
                        var column = grid.columns[ind];
                        if (cells.length > ind) {
                            data[column.name] = $(cells[ind]).text();
                        }
                    }

                    grid.rowClicked(grid, this, data, e);
                }
            });
        },
```
then the event is passed in: 
```JS
$('.mvc-grid').mvcgrid({
    rowClicked: function (grid, row, data,e) {
        alert('Information: ' + e.target );
        alert('Information: ' + e.srcElement );
```
Or is it too much 'breaking' compared with previous implementations? 
I just want to use as maximum the 'standard' functionality of the NUGET MVC Grid package. :smiley:

**Comment by Muchiachio** [comment]
Yes I could include it at the end.
