### ISSUE TITLE
Unable to put table within a scrollable div

### ISSUE THREAD

**Issue by dawityise** [NonFactors/MVC5.Grid#220]
Thanks for the great work. This is not an issue but a feature request instead. Please see the attached screenshot. 

![grid-mvc](https://user-images.githubusercontent.com/3595212/69891852-79ecb700-12f7-11ea-99a2-92c0815daa74.png)

**Comment by Muchiachio** [comment]
Yes, this can be changed using [custom grid partial](http://mvc-grid.azurewebsites.net/Grid/Partial).
