### ISSUE TITLE
Question: Column or Row conditional Formatting

### ISSUE THREAD

**Issue by nickm324** [NonFactors/MVC5.Grid#221]
Is there a way to have conditional cell formatting per row, for example I have a two bool properties called isPastDue and IsPaid and if either is true I want the cell to show YES/NO and color coding in red or green.

I tried the RowAtributed function but it only works with one row even if more than one row is true.

Below is what I tried and it only partially works and not correctly since it only highlights the first row it encounters and then its like its just ignored after that row.

`.RowAttributed(model => new { @class = model.IsPastDue == true ? "alert alert-danger" : null })
 .RowAttributed(model => new { @class = model.IsPaid == true ? "alert alert-success" : null })`

Results in this and the PAST DUE in the first row is totally ignored..
![image](https://user-images.githubusercontent.com/6774571/69917416-d48b2d80-1433-11ea-8e1f-16ce6f683331.png)

**Comment by Muchiachio** [comment]
They have to be merged into one call.

**Comment by nickm324** [comment]
Could you give me an example , I cant find anything like that in the existing examples.

**Comment by Muchiachio** [comment]
Not sure which bootstrap you are using, but you can use either `success` or `table-success` instead of using alert classes, as for one call it's just a concat or similar
```C#
.RowAttributed(model => new
{
    @class = (model.IsPastDue == true ? "danger" : "") + (model.IsPaid == true ? "success" : "")
})
```
or without intersection
```C#
.RowAttributed(model => new
{
    @class = model.IsPastDue == true ? "danger" : model.IsPaid == true ? "success" : ""
})
```
