### ISSUE TITLE
Export data after Filtering it.

### ISSUE THREAD

**Issue by debs1979** [NonFactors/MVC5.Grid#223]
Is there any way to export the data after filtering the data in the client side.

**Comment by Muchiachio** [comment]
[Current export example](http://mvc-grid.azurewebsites.net/Grid/Export) does export the filtered out data only.
If you want to export it without hitting the back end, you can only export current page.

**Comment by debs1979** [comment]
Ohh  Yes. I just figured it out. So to download all data after column filtering I need to remove the RowsPerPage. Am I right?

**Comment by Muchiachio** [comment]
For all the data you need remove paging when constructing the grid for the export.

**Comment by debs1979** [comment]
Ok. Thanks a lot. By the way a very nice product you have build.
