### ISSUE TITLE
Format a Date Column in a grid

### ISSUE THREAD

**Issue by debs1979** [NonFactors/MVC5.Grid#224]
I have a Date Column in the grid. I want to show the date as "mm/dd/yyyy" format. How can I achieve that.
Just adding .Formatted(0: mm/dd/yyyy) is not working.

**Comment by dheoxic** [comment]
.RenderedAs(model=> model.YourDateColumn.ToString("mm/dd/yyyy"))

**Comment by Muchiachio** [comment]
`.Formatted("{0:mm/dd/yyyy}")` works too but you want to use `MM` for months not `mm` for minutes.

**Comment by debs1979** [comment]
.Formatted("{0:MM/dd/yyyy}") is not working. it is showing date with time.

**Comment by Muchiachio** [comment]
Maybe your date is a string?

**Comment by debs1979** [comment]
This is my code .
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "<a href='/Home/Details?batchid="+ model.BatchID + "'>View Details</a>").Encoded(false);
        columns.Add(model => model.BatchID).Titled("BatchID");
        columns.Add(model => model.TimeSystem).Titled("Time System");
        columns.Add(model => model.LoadDate).Titled("Load Date");

        columns.Add(model => model.TotalRecordCount).Titled("Total Record Count");
        columns.Add(model => model.SuccessRecordCount).Titled("Success Record Count");
    })
    .Empty("Select different search criteria to see data")
    .Id("my-ajax-grid")
    .Pageable(pager =>
    {
        pager.PagesToDisplay = 5;
        pager.RowsPerPage = 10;
    })
    .Sortable()

and controller code.
List<LogItems> items = new List<LogItems>();
            items.Add(new LogItems("CA-RD2000-02032020-212039", "CARD2000", new DateTime(2020, 2, 2), 100, 80));
            items.Add(new LogItems("CA-RD2000-02032020-212039", "CARD2000", new DateTime(2020, 2, 2), 100, 80));
            // Only grid query values will be available here.
            return PartialView("_IndexGrid", items);

**Comment by Muchiachio** [comment]
This is my formatting code for column

 public virtual IHtmlString ValueFor(IGridRow<Object> row)
        {
            Object value = Expression((row.Model as T));

            **if (Format != null)
                value = String.Format(Format, value);**

            return new HtmlString(value.ToString());
        }

**Comment by debs1979** [comment]
WHere do i put this?

**Comment by Muchiachio** [comment]
This code is part of the grid, can you identify which part of the library is not working or share a repro?
