### ISSUE TITLE
how to get the query string on an ajax grid?

### ISSUE THREAD

**Issue by rmcombs24** [NonFactors/MVC5.Grid#225]
I've been using your grid and it's been extremely helpful for me. However I am trying to get the latest query string after a user has updated the filters grid and I am trying to figure out how I can get those once the reload end event has happened?

```
   $("#divTicketingGrid")[0].addEventListener('reloadend', function (e) {
       console.log(new MvcGrid(document.querySelector('.mvc-grid')))
    });
```

when I  do this, all I get are the items that were set up when I initialized the grid. How can I get the current query that has happened after reloadend has fired?

**Comment by Muchiachio** [comment]
From [reload events page](https://mvc-grid.azurewebsites.net/Javascript/ReloadEvents)
```JS
document.addEventListener('reloadend', function (e) {
    console.log('grid: ', e.detail.grid);
});
```
Inspecting grid instance you can see the `grid.query` containing the data.

**Comment by rmcombs24** [comment]
Thanks. That works just fine. I've actually used the before and I completely blanked on using it again. I appreciate the help.
