### ISSUE TITLE
Add an "All" custom filter

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#226]
![image](https://user-images.githubusercontent.com/50933655/74208498-b7d66600-4cbe-11ea-9945-8039b6295cf1.png)

How do I add an "All" custom filter based on the image above instead of a blank SelectListItem?

**Comment by Muchiachio** [comment]
You can use [filter options](https://mvc-grid.azurewebsites.net/Column/FilterOptions), `.UsingFilterOptions()` loads distinct items from the data set.

**Comment by dheoxic** [comment]
Using `.UsingFilterOptions()` also adds a blank item on the select list, which when selected gives an empty data source for the table. I'm not sure if this happens to me only

**Comment by Muchiachio** [comment]
It gives empty filter in case you want to filter null or empty values and to not show random values in "not applied filter" cases. If you don't need that you can use your own extension.
