### ISSUE TITLE
Internet Explorer Error

### ISSUE THREAD

**Issue by dheoxic** [NonFactors/MVC5.Grid#227]
I'm getting this error on IE 10
"Object doesn't support property or method 'setPrototypeOf'"

**Comment by Muchiachio** [comment]
Only IE11+ is supported by the current version of the grid.

**Comment by dheoxic** [comment]
Oh, that's unfortunate. Is there a way that you can incorporate this
[https://gist.github.com/edoardocavazza/47246856759f2273e48b](url)
or this
[](https://github.com/wesleytodd/setprototypeof)
to your work?

**Comment by Muchiachio** [comment]
It should just work if you include those files in your project, although I think that there are more unsupported code than this in the grid.

Sorry but we don't have plans to support earlier releases which are not even supported by the Microsoft itself. Support for IE10 ended on 2016 ☹️
