### ISSUE TITLE
The pagination is not working properly

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/MVC5.Grid#228]
The pagination is not working properly
In Grid loading all records are fetched from the database
And that makes it slow!
Please provide a way to read the same page information from the database.

The official example does this:
[https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sorting-filtering-and-paging-with-the-entity-framework-in-an-asp-net-mvc-application](url)

**Comment by Muchiachio** [comment]
It doesn't read all records unless you gave that type of data source. As per starting and paging pages.
> Result needs to be IQueryable in database scenarios, to make use of database side paging.

```C#
[HttpGet]
public ViewResult Index()
{
    // Result needs to be IQueryable in database scenarios, to make use of database side paging.
    return View(Context.Set<Person>());
}
```

**Comment by KAJOOSH** [comment]
> It doesn't read all records unless you gave that type of data source. As per starting and paging pages.
> 
> > Result needs to be IQueryable in database scenarios, to make use of database side paging.
> 
> ```cs
> [HttpGet]
> public ViewResult Index()
> {
>     // Result needs to be IQueryable in database scenarios, to make use of database side paging.
>     return View(Context.Set<Person>());
> }
> ```

Thanks solved.
