### ISSUE TITLE
Another one

### ISSUE THREAD

**Issue by boukenka** [NonFactors/MVC5.Grid#23]
Thanks for the change with the event. It has solved my problem. :+1: 

Do you think in the future the following option could be proposed (meaning to have a vertical scrollbar instead of a page navigation)?
Probably it is not possible and another package should be used in that case, I guess. Could you recommend one in that case?

```C#
@(Html.Grid(Model).Named("PersonGrid")
    .Build(columns =>
    {
        columns.Add(model => model.ViewName).Titled("Name");
    })
    .Scrollable()
)
```

**Comment by Muchiachio** [comment]
It can be scrollable now, but I guess you want infinite scroll with ajax right?

**Comment by boukenka** [comment]
Yes, if it is possible.

**Comment by Muchiachio** [comment]
I would suggest using your own libraries to do that, because adding something generic would only work in simple table scenarios, while custom ones would be prone to fail.

**Comment by boukenka** [comment]
I understand for the Ajax part. I will sort it by building on my own. What about the vertical scrollbar? You write that it can be scrollable now. Is it a new feature in 2.3? Or an option that I do not see?

**Comment by Muchiachio** [comment]
With a fixed table height, it will be scrollable :smile:

**Comment by boukenka** [comment]
Is it possible to have an example? I do not see how to implement it.
```C#
@(Html.Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Id);
    })
```
How can you define specifically the body part to add a vertical scroll bar?

**Comment by Muchiachio** [comment]
By using css styling? No?

**Comment by boukenka** [comment]
Yes I guess so. But how would you do it with a simple example? :smile: I have searched several grid examples but I do not see how to inject in 'tbody' section a specific class for example. Where should it be written? In the global '.css()' C# section where the different elements of the grid are defined?

**Comment by Muchiachio** [comment]
You can use [table styling](http://mvc-grid.azurewebsites.net/Grid/Styling) to add css class on your table, and then write a css selector `.my-class > tbody`.
Or overwrite the default `_Grid.cshtml` partial with your own
```C#
@Html.Grid("_MyCustomPartial", Model)
```

**Comment by boukenka** [comment]
Thanks. I will use your advice.
