### ISSUE TITLE
Cannot use this whats the namespace?

### ISSUE THREAD

**Issue by paulsaxtonclarksons** [NonFactors/MVC5.Grid#230]
Hello

Whats the namespace for using the grid in a Razor view?

Paul

**Comment by Muchiachio** [comment]
[Installation](http://mvc-grid.azurewebsites.net/Home/Installation) and [quick start](http://mvc-grid.azurewebsites.net/) topics are covered on the official page.
Namespace should have been automatically included in the [web config](https://github.com/NonFactors/MVC5.Grid/blob/v7.1.2/src/Mvc.Grid/Views/Web.config.transform).
