### ISSUE TITLE
Low speed in Ajax

### ISSUE THREAD

**Issue by KAJOOSH** [NonFactors/MVC5.Grid#231]
Hi
When using Ajax loads for the first time, the speed is felt to be low and what is the solution?
Also available on the official website
Good luck and happy

**Comment by Muchiachio** [comment]
What slowdowns are we talking about here? 1 seconds 10 seconds?
For me official page and other projects never had slowdowns.

**Comment by KAJOOSH** [comment]
Average 3 sec
In the same way is local
You can remove your history and test
And refresh the site several times

![11](https://user-images.githubusercontent.com/47478490/76778484-2aa39700-67bf-11ea-9ecc-e935f1c0c16f.jpg)

**Comment by KAJOOSH** [comment]
Without Ajax the speed is good .. :)
![22](https://user-images.githubusercontent.com/47478490/76779128-1a3fec00-67c0-11ea-8193-8894c9a29cc7.jpg)

**Comment by Muchiachio** [comment]
Can't really repro anywhere, you will have to profile locally to see where the it blocks 😕
