### ISSUE TITLE
Paging not work 

### ISSUE THREAD

**Issue by Kavya27** [NonFactors/MVC5.Grid#232]

**Comment by Muchiachio** [comment]
Can you share a repro or indicate which part of the grid code doesn't work?

**Comment by Kavya27** [comment]
.Pageable(pager =>
                     {
                         pager.ShowPageSizes = true;
                         pager.PageSizes.Clear();
                         pager.RowsPerPage = 10;
                     })


this part is not work not added page and row in url querystring

**Comment by Kavya27** [comment]
I there issue of mis match version of javascript

**Comment by KAJOOSH** [comment]
> I there issue of mismatch version of javascript?

I had this problem and it was fixed by updating jquery
good luck.
