### ISSUE TITLE
reload 4 grid in my page

### ISSUE THREAD

**Issue by amir6mehrabi** [NonFactors/MVC5.Grid#234]
after an ajax request, I want to reload my grids.
I have 4 grid on that page and using 

`                         new MvcGrid(document.querySelector('.mvc-grid')).reload();
`
reload only the first grid!
what should I do?

**Comment by Muchiachio** [comment]
Iterate over `querySelectorAll` or `getElementsByClassName` results and call reload on every element.

**Comment by amir6mehrabi** [comment]
document.querySelectorAll('.mvc-grid').
                             forEach(function (griditem) { new MvcGrid(griditem).reload(); });
this code worked 
@Muchiachio thanks
