### ISSUE TITLE
Manual Paging (Server-Side) and Page Sizes

### ISSUE THREAD

**Issue by TorreyGarland** [NonFactors/MVC5.Grid#235]
I am running into an issue with server side pagination and the correct data being display.

If I have a list with 26 items, and initial only retrieve the first 10 everything displays correctly.

But if I go to page 3 and then select 20 or more from the default dropdown list, all results disappear.

Are there any examples of manual processing with the drop-downlist not being cleared?

**Comment by Muchiachio** [comment]
You are running into this https://github.com/NonFactors/AspNetCore.Grid/issues/252, grid does reset the page to the last page when it overruns. I will back port this to this version too.

**Comment by TorreyGarland** [comment]
thanks for putting out a fix for this!!!
