### ISSUE TITLE
Ajax reload Cannot read property 'children" of null

### ISSUE THREAD

**Issue by TorreyGarland** [NonFactors/MVC5.Grid#236]
Hi, I have an Ajax grid that I have configured to not load when the page loads the first time by setting the source url in Razor and javascript to an empty string.  Reload is initiated when a user clicks a filter button because their are several form input parameters that I am passing back to the server on the grid's reloadstart event.

When I click the filter button, the javascript code ensures that the sourceUrl property of the grid is not empty.  No problems.

If I enter a value of one of the aforementioned form fields, and then click the filter button, the DevTools console displays "Uncaught TypeError: cannot read property 'children" of null, thrown at mvc-grid.js, line 177.

Debugging this line, "var parent = grid.element.parentElement;', parentElement is coming back as undefined, and the code fails on the next line "var i = [].indexOf.call(parent.children, grid.element);"

Is there a fix for this or do you have any suggestions for correcting the behavior?

Also, the Razor/C# code for the grid is configured for ".UseProcessingMode(GridProcessingMode.Manual)".  Does this make any difference.

Please let me know if more information is needed.

**Comment by Muchiachio** [comment]
Does the grid exist in the dom? Feels like it got detached or initialized on window, otherwise I don't know how can parent element be undefined.
