### ISSUE TITLE
Filters and paging not working 

### ISSUE THREAD

**Issue by ssajid999** [NonFactors/MVC5.Grid#237]
Grid paging and filter is working properly when page is loaded initially. However when I am sending ajax call to get partial view and bind its result to div the filters and paging not working. How to attach these filters and paging to div in case of async ajax call.

Many thanks

**Comment by Muchiachio** [comment]
Seems to work correctly on http://mvc-grid.azurewebsites.net/Grid/Ajax, can you create a small repro showing the problem with the grid?

**Comment by ssajid999** [comment]
I am able to attach these filters now by adding     [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
                        new MvcGrid(element);
                    }); in success method of ajax. However, the grid is refreshing page after clicking page number and filters are not working properly according to dropdown selected value.

**Comment by Muchiachio** [comment]
Closing as there is no way to reproduce.
