### ISSUE TITLE
how can use filtered data in export with Html.AjaxGrid in razor page

### ISSUE THREAD

**Issue by sajadghobadi** [NonFactors/MVC5.Grid#238]
thanks for your great component.
i have use grid in Html.AjaxGrid like below
page projects.cshtml :

 @Html.AjaxGrid(Url.Page("/Projects/IndexGrid"))

and in indexGrid.cshtml : 
```C#
@(Html
    .Grid(Model.ExportProductVersions)
    .Build(columns =>
    {
        columns.Add().RenderedAs((model, row) => row + 1).Titled("index");
        columns.Add(model => model.FirstName).Titled("project"); .Empty("no data")
    })
    .Id("my-ajax-grid")
    .UsingFilterMode(GridFilterMode.Row)
    .Filterable(GridFilterType.Double)
    .Sortable()
)
```

my export handler is : 
```C#
private IGrid<ArchiveProject> CreateExportableGrid()
{
    IGrid<ArchiveProject> grid = new Grid<ArchiveProject>(_archiveProjectService.GetForGrid(new ArchiveProjectSearchModel<ArchiveProject>()));
    grid.ViewContext = new ViewContext { HttpContext = HttpContext };
    grid.Query = Request.Query;

    grid.Columns.Add(model => model.FirstName).Titled("FirstName");
    grid.Columns.Add(model => model.ContractNumber).Filterable(true).Titled("ContractNumber");
    grid.Columns.Add(model => model.FirstName).Filterable(true).Titled("Code");
  
    foreach (IGridColumn column in grid.Columns)
    {
        column.Filter.IsEnabled = true;
        column.Sort.IsEnabled = true;
    }

    return grid;
}
```

when i export all data exist in Excel file without applied filters.

**Comment by Muchiachio** [comment]
Most likely you are not passing `new MvcGrid(tableElement).url.searchParams` query to your export method. Does your `Request.Query` have filter parameters?

**Comment by sajadghobadi** [comment]
no. Request.Query has only **handler** query string and other query string is not in  Request.Query .
i have to in every apply filtering, update export url for add query string?

**Comment by Muchiachio** [comment]
Yes you will have to update it or concat it on export button click for ajax grid. Normal grid example worked without updating, because filter parameters are already in static window url.

**Comment by sajadghobadi** [comment]
grid has javascript event for filter updated?

**Comment by Muchiachio** [comment]
Yes they are covered in [api section](http://mvc-grid.azurewebsites.net/Javascript/Api). Using `reloadstart` would be most appropriate I guess.
