### ISSUE TITLE
How to make the grid responsive?

### ISSUE THREAD

**Issue by sohrabzia** [NonFactors/MVC5.Grid#239]
Is there any way to make the grid mobile friendly without having to scroll horizontally?
Cant find it in documentation, other grid system provide this feature but in my application MVC5 Grid is already implemented.

Thanks

**Comment by Muchiachio** [comment]
No there is no responsive implementation, any example of other grids?

**Comment by sohrabzia** [comment]
here is one example https://datatables.net/extensions/responsive/examples/styling/bootstrap4.html

**Comment by Muchiachio** [comment]
Well this is old js based grid with 3268142684 lines of features, while this grid is more of a helper for server side rendering for simple scenarios 😦

**Comment by Muchiachio** [comment]
Also it seems like it only applies bootstrap styling of hiding columns on lower resolutions and not something responsive, you can do that by using `Css(...)` on columns.

**Comment by sohrabzia** [comment]
could you direct me to any example for using `.Css(...)`

**Comment by Muchiachio** [comment]
[Column styling](http://mvc-grid.azurewebsites.net/Column/Styling) with [responsive bootstrap](https://getbootstrap.com/docs/3.4/css/#responsive-utilities) classes.

**Comment by sohrabzia** [comment]
Thank you :)
