### ISSUE TITLE
AJAX Export

### ISSUE THREAD

**Issue by junrikson** [NonFactors/MVC5.Grid#240]
Hi there,

Is there anything can I do to capture `ViewContext.HttpContext.Request.QueryString` for AJAX Grid Export like in this http://mvc-grid.azurewebsites.net/Grid/Export?sort=age&order=desc ?

**Comment by Muchiachio** [comment]
```new MvcGrid(...).query``` has the grid query you can use for the export url.

**Comment by junrikson** [comment]
Thanks a lot :D
