### ISSUE TITLE
How to empty a grid?

### ISSUE THREAD

**Issue by lbelloq** [NonFactors/MVC5.Grid#242]
I have an AJAX grid, and I want the grid to be empty when the refresh ends with an error. How do I do it? So far I'm hooking the `reloadfail` event but then I don't know how to proceed.

**Comment by Muchiachio** [comment]
I can only think of clearing the rows through javascript. Something similar to this
```JS
document.addEventListener("reloadfail", function (e) {
    e.detail.grid.element.querySelector("tbody").innerHTML = "";
});
```

**Comment by lbelloq** [comment]
It does remove the rows, but when trying to refresh the grid again shows the following error:

```javascript
Uncaught TypeError: Cannot read property 'removeChild' of null
    at MvcGrid.stopLoading (mvc-grid.js:303)
    at MvcGrid.startLoading (mvc-grid.js:259)
    at MvcGrid.reload (mvc-grid.js:175)
    at RecargaGrilla (Index:159)
    at HTMLInputElement.<anonymous> (Index:146)
```

**Comment by Muchiachio** [comment]
Weird, I can't repro on the newest version. Maybe more DOM got removed?
Crashing line fails on missing parent, which can only happen if the whole grid is missing.
```JS
if (grid.loader) {
    grid.loader.parentElement.removeChild(grid.loader);
}
```

**Comment by lbelloq** [comment]
Don't worry, I used a workaround: on server-side error, return 0 rows and use a custom message for empty grid. That shows an error message and allows the user to try and refresh the grid again.
