### ISSUE TITLE
Uncaught Type Error: Cannot read property 'innerText' of undefined

### ISSUE THREAD

**Issue by TorreyGarland** [NonFactors/MVC5.Grid#243]
I have an Ajax grid nested inside of another ajax grid.  Loading the data is not a problem.

The nested ajax grid has an "Add" new button in the table footer.

When the "add" button gets clicked, the error gets thrown in the "bind" method when attempting to loop through all columns (on line 333 of mvc-grid.js).

Any suggestions?

**Comment by Muchiachio** [comment]
You can avoid row click binding by putting table footer rows in `tfoot` or adding a `mvc-grid-empty-row` class to your row.

**Comment by TorreyGarland** [comment]
Adding the "mvc-grid-empty-row" css class fixes it.
