### ISSUE TITLE
Filter and sorting on collections

### ISSUE THREAD

**Issue by inversiondk** [NonFactors/MVC5.Grid#244]
I'm just getting started with the grid and must say it's a very nice addition to all of the super bloated grid frameworks out there! 
I can't however seem to figure out how to filter and sort on collections (if it's at all possible). 

My datasource is the following DTO: 

```
public string Name { get; set; }
public IEnumerable<int> Classes { get; set; }
```
I can easily display the values of these properties in the grid: 

```
columns.Add(model => model.Name).Titled("Name");
columns.Add(model => model.Classes).Titled("Classes").RenderedAs(model => String.Join(",", model.Classes));
```

This'll give me a nice comma-separated list of the classes. 
Now of course I can't filter or sort on this value because how would the IQueryable now what to do with this? I'm using EF so basically I'm just getting an "DbSortClause expressions must have a type that is order comparable."

What I'd really like to do is to make a multiselect containing the different classes in the collection and then filtering on these - and for sorting simply do a numeric sort on the values in the collection. 

But I can't seem to figure out if it's at all possible to use the grid to solve my dilemma? I could of course create a database column that contains the comma-separated string-value of my classes - and then everything would work great with sorting and filtering (on a string-basis) - but I would rather examine options that will allow me to keep my data model clean. 

So is it possible to create filter and sorting on collections? 

I hope it's not too unclear :)

**Comment by Muchiachio** [comment]
Yes, it is possible but was only included out of the box in the newer aspnet core grid.
However you can still implement your own filter for mvc5 as well.

Here's an example for list of strings.
```C#
public class ListStringContainsFilter : BaseGridFilter
{
    public override Expression Apply(Expression expression)
    {
        if (String.IsNullOrEmpty(Value))
            return null;

        Expression<Func<String, Boolean>> containsExpression = (list) => list.Contains(Value);
        MethodInfo anyMethod = typeof(Enumerable).GetMethods()
            .First(method =>
                method.Name == nameof(Enumerable.Any) &&
                method.GetParameters().Length == 2)
            .MakeGenericMethod(typeof(String));

        return Expression.Call(anyMethod, expression, containsExpression);
    }
}
```
and it would be registered on startup like this
```C#
MvcGrid.Filters.Register(typeof(List<String>), "contains", typeof(ListStringContainsFilter));
```

**Comment by inversiondk** [comment]
Thanks a lot @Muchiachio - I'll give it a go to see if I can't get it up and running. I'll be sure to leave some feedback :)

**Comment by inversiondk** [comment]
Unfortunately I didn't have much luck with this. 

I've created the following model: 

```
public string Name { get; set; }
public List<string> ClassesAsString { get; set; }
```

And have the following in my Razor view: 

```
@(Html
                    .Grid(Model.Registrations)
                    .Build(columns =>
                    {
                            columns.Add(model => model.Name).Titled("Name");
                            columns.Add(model => model.ClassesAsString).Titled("Classes");
                    })
                    .Empty("No data found")
                    .Filterable()
                    .Sortable()
                    .Pageable()
 )

```
I've then added the following filter class: 

```
public override Expression Apply(Expression expression)
        {
            var value = Values.FirstOrDefault();

            if (String.IsNullOrEmpty(value))
                return null;

            Expression<Func<String, Boolean>> containsExpression = (list) => list.Contains(value);
            MethodInfo anyMethod = typeof(Enumerable).GetMethods()
                .First(method =>
                    method.Name == nameof(Enumerable.Any) &&
                    method.GetParameters().Length == 2)
                .MakeGenericMethod(typeof(String));

            return Expression.Call(anyMethod, expression, containsExpression);
        }

```
NOTE: 
I know that my `var value = Values.FirstOrDefault();` might fail. But the current model doesn't have a "Value" property as per your example. Instead it has a Values array. 
As per your example I also had to create an override for the abstract method with the signature: 

`Expression? Apply(Expression expression, string? value)`

For starters I just wanted to get some kind of effect though. 

I then registered the filter in my Global.asax for my web application: 

`MvcGrid.Filters.Register(typeof(List<String>), "contains", typeof(ListStringContainsFilter));`

Unfortunately this doesn't do much. I've noticed that the filter icon in the grid completely disappears. After looking through the _Grid.cshtml file I can see that this is only rendered if the column has filters enabled. 
So I'm guessing I'm doing something wrong in one of the steps? 

Would you happen to be able to point me to a basic example of somewhere where the filtering and sorting of a collection is working? Or can you see what I might be doing wrong here? 

Thanks a lot :)

**Comment by Muchiachio** [comment]
You might have to set a filter popup provider (which doesn't exist for enumerable).
```C#
.Filterable(true).FilteredAs("text")
```
