### ISSUE TITLE
Ajax grid pagination not working when giving the pagination outside div 

### ISSUE THREAD

**Issue by Aswathims** [NonFactors/MVC5.Grid#245]
requirement : to make available pagination control while scrolling the table horizontally
to do this ,  i have given the pagination outside the div and created another div with same  id & class <div id="@Model.Id" class="mvc-grid mvc-grid-@(Model.FilterMode.ToString().ToLower()). It is working with normal grids. But not with ajaxgrids

**Comment by Muchiachio** [comment]
estimated price: $ 570 (3 hours development + 3 hours potential support over the years times our company's rate of 95).

Jokes aside, this project is already in maintenance only mode as announced and pinned in #222, so this won't be considered.
This can already be achieved by javascript binding mentioned in the [last issue](https://github.com/NonFactors/MVC5.Grid.Web/issues/29) or by using a [custom partial](http://mvc-grid.azurewebsites.net/Grid/Partial) by wrapping the table in scrollable div without tearing the dom apart.
