### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by boukenka** [NonFactors/MVC5.Grid#26]
Good evening,

I am still implementing a grid which is vertically scrollable with the MVC5 Grid. It is difficult (at least for me). 

A) How do you define the width of the headers of the grid? For example, if one header has the title 'Name' and the other one 'Surname', their width are different. How is it calculated? 
B) What are the rules for the TR/TD for the TBODY and the TR/TH for the THEAD about height and width calculation? How are they calculated?
C) What will contain the version 3.0? Will it be a vertical scrollable option?

Thanks

PS: So far here is the style I am using (see below). It is partially working. 
#researchGrid (DIV) is the section where I apply the specific style for the grid.
PS: Sorry to come back with a question about grid and vertical scrollability. But this is the missing piece for a migration.
PS: I have tried with the inspection of elements with Firefox and Google chrome. I get information about padding and margin. But not from where is coming the value of the width.

```JS
#researchGrid table{
  width:800px;
}

#researchGrid tbody {
  height: 100px;
  overflow-y: auto;
  position: relative;
  width:800px;
  display: block;
}

#researchGrid thead {
  display: block;
}

#researchGrid th {
    height:24px;
    width:128px;
}

#researchGrid td {
    margin:0px;
    height:32px;
    max-height:32px;
    padding:4px;
    width:128px;
    align-content:center;
    vertical-align:middle;
}
```

**Comment by Muchiachio** [comment]
A) By using css classes, by default they are calculated by the browser depending on cell content length.
B) They are automatically stretching as far as they can, unless they are limited by height specified in css.
C) Nothing much in features, just extensibility updates which brake semver and few other changes to match mvc core.

**Comment by boukenka** [comment]
For the point A, can you give to me an example please (based on one of the demo) for the width calculation.

**Comment by Muchiachio** [comment]
```C#
columns.Add(model => model.Age).Titled("Age").Css("wider")
```
```CSS
.wider {
    width: 100px;
}
```

**Comment by boukenka** [comment]
Yes it will work if you attribute a specific css for any column. 
But what about there is no specific attributed css to the column? 
How is calculated the width of a column in that case? ...

**Comment by Muchiachio** [comment]
As I mentioned above
> by default they are calculated by the browser depending on the cell's content length.

that is, if you have 100 char content in the first column and 50 char in the seconds one, the first one will be about 2 times wider than the second one and both of them will take the width of the table.

**Comment by boukenka** [comment]
I was just hoping that it would not be necessary to define a specifc css for each column (for the width attribution) but to find a global rule that I could apply one time via the CSS in my original post.

**Comment by boukenka** [comment]
Thanks for the answers
