### ISSUE TITLE
gridquery with multiple filters

### ISSUE THREAD

**Issue by danboone** [NonFactors/MVC5.Grid#29]
In your examples you have a filter for the global search and it works great.
however i have to filter the grid by a search, begin and end date and a status from a dropdown.

Here is my main gird search and it works 
```JS
$(document).on('keyup', '.grid-search', function () {
    var grid = $('.mvc-grid').data('mvc-grid');
    grid.gridQuery = 'search=' + this.value; // Reset page, filter and sort with new filter.

    $('.mvc-grid').mvcgrid({
        reload: true
    });
});

 $("#search-btn").click(function () {
            var start = $("#start").val();
            var end = $("#end").val();
            var search = $("grid-search").val();
            var stat = $("#status :selected").text();
I have tried it both of these ways and neither works;
************************
            grid.gridQuery = { search: search, start: start, end: end, status: stat };
            grid.gridQuery = 'search=' + search + ", start = " + start + ", end=" + end + ",status=" + status; 
**********************
            $('.mvc-grid').mvcgrid({
                reload: true
            });
```
This part of code works but it breaks the search feature i get this error when i inspect the element:
Uncaught TypeError: Cannot set property 'gridQuery' of undefined
            //$.get("GetRoeInfo", {search: search, start: start, end: end, status:stat })
            //    .success(function (data) {
            //        $("#grid").html(data);
            //    });
        });

Thank you for your help

**Comment by Muchiachio** [comment]
Because you are concatenating your grid query parameters using `,`
```Url
localhost/?search=search,start=X,end=Y
```
You should append your grid parameters using `&`.

**Comment by danboone** [comment]
i have modified my code as you suggested and I still am not getting any of the parameters fed back to the controller
Here is my code now
var start = $("#start").val();
            var end = $("#end").val();
            var search = $("grid-search").val();
            var stat = $("#status :selected").text();
            // Reset page, filter and sort with new filter.
            alert("Here are parameters search:"+search +" start:"+start+" end:"+end+" status:" +status);
            grid.gridQuery = 'search=' + search + '&start=' + start + '&end=' + end + '&status=' + status;
            
            $('.mvc-grid').mvcgrid({
                reload: true
            });
and the alert shows that the variables are getting loaded.

**Comment by Muchiachio** [comment]
Would be great if you could post a repro project, because I don't see anything bad :?

**Comment by danboone** [comment]
I used your global search as the start of mine and added in the date selector and 

 <div class="dropdown col-md-2">
        <select name="Status" id="status">
            <option>All</option>
            <option>R</option>
            <option>Y</option>
            <option>G</option>
        </select>
    </div>
    <span class="col-md-2 text-nowrap">Request Ship Date Filter:</span>
    <div id="sandbox-container" class="col-md-3 pull-left">
        <div class="input-daterange input-group col-md-2" id="datepicker2">
            <input type="text" class="input-sm form-control" name="start" id="start" />
            <span class="input-group-addon">to</span>
            <input type="text" class="input-sm form-control" name="end" id="end" />
        </div>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-success btn-xs" id="search-btn">Search</button>
    </div>
</div>
<br />
<div class="example content-block">
    <div class="widget">
        <div class="widget-header">
            <i class="fa fa-bars"></i>
            ROE
            <label class="sr-only" for="search-text">PO Number, Order Type or Campaign Name</label>
            <input type="text" class="grid-search" id="grid-search" style="width:300px" placeholder="PO Num, Order Type or Campaign">
            <span class="widget-buttons">
                <a class="fa fa-file-excel-o" href="@(Url.Action("ExportRoeIndex") + "?" + Request.QueryString)"></a>
                
            </span>
        </div>
        <div class="widget-content" id="grid">
            @Html.AjaxGrid(Url.Action("GetRoeInfo"))
        </div>
    </div>
</div>

**Comment by Muchiachio** [comment]
Did you debug the code using developer console? You should be able to find why it doesn't get posted back to the server this way.

**Comment by danboone** [comment]
do you mean googles developer console?  
I have been debugging in visual studio.

**Comment by Muchiachio** [comment]
Yes in browser's developer window, to see what javascript does.

**Comment by danboone** [comment]
I can see all the variables are loaded and but when trying to load the gridQuery its like it they are all not loaded I copied a snippet of it 
one thing i did notice though that if i have started a search in the bar that gets passed to all the different calls but none of the other parameters are passed.


![image](https://cloud.githubusercontent.com/assets/12700793/12825718/490be12a-cb3d-11e5-804b-fcb1689a7b2e.png)

**Comment by danboone** [comment]
Just to mess around with it i modified your original grid-search javascript to see what would happen
heres what i changed it to:
$(document).on('keyup', '.grid-search', function () {
    var grid = $('.mvc-grid').data('mvc-grid');
    var start = $("#start").val();
    var end = $("#end").val();
    var stat = $("#status :selected").text();
    grid.gridQuery = 'search=' + this.value + '&start=' + start + '&end=' + end + '&status=' + stat; // Reset page, filter and sort with new filter.

    $('.mvc-grid').mvcgrid({
        reload: true
    });
});

now when I hit the search it passes in the variables but only the original values they loaded to.  For example if i set the status to Y and then entered a character in the search it would pass the search and the Y then say i changed status to G then only the search gets passed, if i add to the search then it passes the search and status of Y.
This has me baffled as to why it is doing that.

**Comment by Muchiachio** [comment]
Did you fix your problems? Or there is something I can do?

**Comment by danboone** [comment]
I did a different work around never could get the gridquery to work :(.
but it is working now though

**Comment by adamdehaven** [comment]
@danboone I can't get `gridQuery` to work either. What was your workaround?

**Comment by Muchiachio** [comment]
If you can share an example repo, I can tell you what's wrong.

**Comment by adamdehaven** [comment]
@Muchiachio Here's the main code: https://gist.github.com/adamdehaven/764a714571c998239793

I have the Ajax grid working fine - displays and sorts correctly. If I pass a string directly into my grid call like this `@Html.AjaxGrid(Url.Action("AllGrid", new { facility = ViewBag.FacilityID, search = "Adam" }))` it loads the table correctly.

I can't get the table to filter from the search when the input changes

**Comment by Muchiachio** [comment]
Hmm, seems ok. Try this, if it doesn't work you should debug javascript/ajax call to see if its correct.
I'm interested to know why it doesn't work.
```JS
$(document).on('keyup', '#patient-search-input', function() {
    var grid = $('.mvc-grid').data('mvc-grid');
    grid.gridQuery = 'search=' + this.value;
    
    grid.reload();
});
```

**Comment by Muchiachio** [comment]
And you can always download mvc grid examples from [this repo](https://github.com/NonFactors/MVC5.Grid.Web), it works there so something must be different.

**Comment by adamdehaven** [comment]
Tried your new `keyup` function, but still no luck. The grid doesn't update or anything. How do you pass the search query to the view? I'm sure I'm missing something simple

**Comment by Muchiachio** [comment]
What do you mean to the view? Does it even do an ajax call to your controller? I'm pretty sure `reload` function should do at least something, because there is no empty paths there :confused:

**Comment by adamdehaven** [comment]
How can I tell if `reload` is doing anything?

**Comment by Muchiachio** [comment]
Debugging C# code or through F12 developer tools in your browser.

**Comment by adamdehaven** [comment]
The `reload()` function is trying to reload the data, but shows this as the URL: 
`http://localhost:14303/Patients/104/All?undefined&_=1456505370457`

**Comment by Muchiachio** [comment]
Maybe `this.value` is undefined?

**Comment by adamdehaven** [comment]
I got it working - I'm not sure what changed, but thanks :)
I went back to the original javascript
