### ISSUE TITLE
How to change the query for an Ajax Grid without changing the page querystring 

### ISSUE THREAD

**Issue by JeremyC88** [NonFactors/MVC5.Grid#31]
I have an ordinary grid created for instance, like in the example on 
http://mvc-grid.azurewebsites.net/Grid/Ajax?mainParam=mainValue. And I want to (based on filling a form out and clicking a button) change the query on the ajax grid. I don't know how to do this out of the box though.

**Sample Scenario**

CSHTML includes this:
```
@Html.AjaxGrid(Url.Action("IndexGrid", new { param = "value"}))
```

Then the grid is initialised in javascript:
```
// Mvc.Grid binding
$(function () {
    $('.mvc-grid').mvcgrid();
});

```
And heres the tricky part, I want to refresh the grid with a new query when a button is clicked:
```

submitSearch.click(function () {

	var isFormValid = $("#searchForm").valid();

	if (isFormValid) {
		var newQuery = $("#searchForm").serialize();
	
		$('.mvc-grid').mvcgrid({
			query: newQuery,
			reload: true

		});
	}            

});     

```
But when I do this, the query property isn't set to my new parameters. Is there any other way to do this?

**Comment by Muchiachio** [comment]
You just need to add current paging information, which is saved in query's `grid.name + '-Page'` key.
You can find examples of parsing query string [here](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L301). I should probably try to make page information available through grid instance in v3.0.0.

**Comment by JeremyC88** [comment]
Hi, thanks for replying. I tried to add the paging information to my existing code, but it didn't seem to work. I have found that if I use the grid instance, I can use the grid methods myself and construct my new query like so:
```
$("#submitSearch").click(function() {

	// Query Refresh Method 2

	var gridElem = $('.mvc-grid').first();
	var grid = gridElem.data('mvc-grid');

	var formValues = $("#searchForm").serializeArray();

	for (var i = 0; i < formValues.length; i++) {
		grid.gridQuery = grid.addOrReplace(grid.gridQuery, formValues[i].name, formValues[i].value);
	}

	grid.reload(grid.gridQuery);

});
```

Is this more of a recommended way of changing the query?

**Comment by Muchiachio** [comment]
Yes you can use existing methods, if they actually return a result, because some of them work on internal state.

**Comment by Muchiachio** [comment]
Can I close?

**Comment by JeremyC88** [comment]
Yes thank you for the assistance.
