### ISSUE TITLE
Load image on paging?

### ISSUE THREAD

**Issue by santiago998** [NonFactors/MVC5.Grid#35]
Hi,

First thanks very much for your job.
I want to use a gif image while user is paging, i'm now using ajax grid. This is possible?

Thanks,

**Comment by Muchiachio** [comment]
Yes, you can implement your own loading logic in `reloadStarted`, `reloadEnded`, `reloadFailed` events as shown [here](http://mvc-grid.azurewebsites.net/Javascript/ReloadEvents).

**Comment by santiago998** [comment]
Thanks, it works!
