### ISSUE TITLE
Add Grid ID

### ISSUE THREAD

**Issue by ryzam** [NonFactors/MVC5.Grid#36]
Hi,

I have push new code in fork repository to add grid id. You can give value id for Grid. This is important if you have multiple grid in one page and want to reload specific grid. 
Eg:

```C#
@(Html
    .Grid(Model.Members)
    .Build(columns =>
    {
        columns.Add(model => model.DisplayName).Titled("Displayname");
    })
    .Id("MembersGrid")
)
```

```JS
$('#MembersGrid').mvcgrid({               
    reload: true
});
```

**Comment by Muchiachio** [comment]
This can be achieved by using `.Css("MembersGrid")`, and then getting parent grid
```JS
var grid = $('.MembersGrid').parent().data('mvc-grid');
```
I will be exposing grid name data and it's ID in v3.0.0, so it can be selected using
```JS
var grid = $('.mvc-grid[data-name="MembersGrid"]').data('mvc-grid');
or
var grid = $('#MembersGrid').data('mvc-grid');
```
