### ISSUE TITLE
Question regarding filtering

### ISSUE THREAD

**Issue by describeme** [NonFactors/MVC5.Grid#37]
Hello,
First of all, thank you for such cool tool.
Second,
I cant get the onclick event to bind on the filter icons, i see the icon but when i click on it nothing happens,  (the filter box doesnt show up), also i dont have any errors on the console, any idea of what could be happening?

**Comment by Muchiachio** [comment]
This seems to work for me, at least on [grid documentation](https://github.com/NonFactors/MVC5.Grid.Web) page.
```JS
$('.mvc-grid-filter').on('click', function (e) {
    console.log('Clicked');
});
```
