### ISSUE TITLE
Select page size

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#38]
How to implement a dropdown list of a page size?(10,20,...all)
Thanks

**Comment by Muchiachio** [comment]
You will need to apply [this](https://github.com/NonFactors/MVC5.Grid/commit/e67481c57d0552e03a9bc719df911e9e85af4a78) and [this](https://github.com/NonFactors/MVC5.Grid/commit/ce68c73ba70410f3773ea27518d3207e1f1d3fe7) patch, or create your own pager based on these commits. And then update `.mvc-grid-pager-rows` from your dropdown.
This is a planned and already implemented feature which will be available with v3.0.0 which should be release right after MVC Core's RTM.
