### ISSUE TITLE
Problem with Paging

### ISSUE THREAD

**Issue by vladirimia** [NonFactors/MVC5.Grid#41]
Hi,

First of all, great job with this ! Grat control. 
But I have a problem when I set the grid to support Paging. I get an error regarding LINQ and Entity: The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.

The model in the View is of type IEnumerable, just as in your example.
There nothin else going on there. I add the model to the MvcGrid, and that's it.

The problem is here (in the _Grid.cshtml file):
@if (Model.Rows.Any())

**Comment by Muchiachio** [comment]
You need to sort your models in any order for pagination to work, that's a database limitation on paging.

**Comment by vladirimia** [comment]
Thank you for the solution. It works now ! 
Do you have somewhere a more complete documentation please?

**Comment by Muchiachio** [comment]
What do you mean by more complete?

**Comment by vladirimia** [comment]
The only thing I can find related to "how to" is here: http://mvc-grid.azurewebsites.net/
Take the situation described by me in the ticket, regarding the paging. It wasn't clear from the website that the model needs ordering before use.
That's what I mean by "more complete" documentation.

In any case, it's no problem. 
Like I said, great work ! and thanks for the help !
