### ISSUE TITLE
issue search date

### ISSUE THREAD

**Issue by thewinner55** [NonFactors/MVC5.Grid#42]
Ex.   date in database  :   2016-08-26 17:21:11.650

 I can not find  ( 26/08/2016 )  

Help me, thanks

**Comment by Muchiachio** [comment]
Grid is comparing two dates, so `2016-08-26 17:21:11.650` is not equal to `2016-08-26`
You can either select trimmed dates to be showed in the grid or use [date multi filter](http://mvc-grid.azurewebsites.net/Grid/MultiFiltering).
