### ISSUE TITLE
Errors while compiling

### ISSUE THREAD

**Issue by c-arnab** [NonFactors/MVC5.Grid#43]
I get the following errors while compiling the project. What am i doing wrong??

1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(24,44,24,45): error CS1002: ; expected
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(24,52,24,54): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(24,61,24,62): error CS1519: Invalid token ';' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(31,37,31,38): error CS1002: ; expected
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(31,39,31,40): error CS1519: Invalid token '>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(31,52,31,54): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Columns\BaseGridColumn.cs(31,65,31,66): error CS1519: Invalid token ';' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(20,40,20,41): error CS1002: ; expected
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(20,49,20,51): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(20,59,20,60): error CS1519: Invalid token ';' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(23,32,23,33): error CS1002: ; expected
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(23,38,23,40): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(23,45,23,46): error CS1519: Invalid token ';' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(26,25,26,26): error CS1002: ; expected
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(26,32,26,34): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>D:\del\datatables-mvc\MVC5.Grid-master\src\Mvc.Grid.Core\Grids\Grid.cs(26,40,26,41): error CS1519: Invalid token ';' in class, struct, or interface member declaration

**Comment by Muchiachio** [comment]
You need VS2015 or C# 6.0 compatible compiler.
