### ISSUE TITLE
filtering/sorting not working

### ISSUE THREAD

**Issue by mpevreuls** [NonFactors/MVC5.Grid#44]
Hi,

i have installed the package through nuget..
Followed the installation steps, but my grid does not filter, order, sort in any way. Changes in de CSS are applied.

I have tried:

- putting the mvc-grid.js in the bundleconfig.
- putting the mvc-grid.js in the bottom of the page
- removed all pop-up blockers, etc in the browser.
- in the controller i made it a sortable IQueryable viewmodel and passes it to the view.
- tried it in IE, Firefox and chrome

The grid renders nicely, only the actions  do not work, any Ideas???
It stil it does not sort. 

Best regards, Marcel

**Comment by mpevreuls** [comment]
moving the 

$('.mvc-grid').mvcgrid({
        rowClicked: function (grid, row, data, e) {
            console.log('data: ' + data);
            console.log('grid: ' + grid);
        }
    })
just before the </body> tag in _Layout.chtml. did the job..

**Comment by mpevreuls** [comment]
Now just the click event is not working :-)

**Comment by Muchiachio** [comment]
Could you debug [this line](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L149) in your browser and see why it's not being called?
Alternatively you could download [examples project](https://github.com/NonFactors/MVC5.Grid.Web) and check for differences in your code and row clicked example page.

**Comment by Muchiachio** [comment]
Did you managed to track down the issue?

**Comment by mpevreuls** [comment]
Hi,

yes, it is working now. Something was messed up with the javascript i
guess. I started over in a clean project, and it worked.

Thank!

Marcel
