### ISSUE TITLE
style rows

### ISSUE THREAD

**Issue by ftrevisani** [NonFactors/MVC5.Grid#45]
Hello,
I want to change cursor on rows hover and change the style of a clicked row (something like .Css("table-hover")).
At the end I would open a modal popup to edit the clicked row.
Can anyone suggest me the best way to add this features to my grid?

**Comment by Muchiachio** [comment]
You can bind your own row clicked event using java script or use grid's [row clicked](http://mvc-grid.azurewebsites.net/Javascript/RowClicked) function, to set row styling.

Changing cursor is just as simple as adding a css rule for your table
```CSS
.mvc-grid tr:hover {
    cursor: pointer;
}
```

**Comment by Muchiachio** [comment]
Did this help?

**Comment by ftrevisani** [comment]
Yes! Thank you.
