### ISSUE TITLE
Custom paging and sorting

### ISSUE THREAD

**Issue by explosiveaction** [NonFactors/MVC5.Grid#46]
I have had to consider removing this grid as the performance hit taken on large data sets is too great.

The problem is due to the automatic sorting and paging, I have to return the complete data set from the database for the grid to work its magic on post-retrieval. On large datasets with complicated filtering options this is not very performant.

Is there/can there be a way to implement custom paging and sorting so that I only need to retrieve 10 items from the database per page (as well as a total count of items to determine the amount of pages required), plus also pipe in the selected sort option and direction to my EF query?

**Comment by Muchiachio** [comment]
This already works by default. Grid runs the database query for X rows only, unless you already enumerated them to memory. Make sure you are returning `IQueryable<T>` from your controller.
```C#
public ActionResult Index()
{
    return View(context.Set<BigModel>().OrderBy(model => model.Field));
}
```
As for initial sort order, you can either return `IOrderedQueryable<T>` (same as exmaple above) or use [initial sort option](http://mvc-grid.azurewebsites.net/Column/InitialSort) on grid column, which will add a sort arrow for the grid.

**Comment by explosiveaction** [comment]
I'm not sure I follow how that is meant to work. My DAL method needs to be where the page number and page size is set. E.g.

```
response = await query
                        .Skip(itemsPerPage * (pageNo - 1))
                        .Take(itemsPerPage)
                        .ToListAsync();
```

With itemsPerPage being say 25 and pageNo being 3. If I set this in the DAL EF method I can limit the data returned from SQL to be just the 10 rows I require. But then how does your built in paging and sort options know about the data outside of that loaded for page 3? If I were to sort the grid by one of the columns, only the visible 10 would sort.

Am I making sense?

**Comment by Muchiachio** [comment]
You don't need to page your result set by hand, grid will do it automatically if `Pageable()` is applied.
```C#
response = query.OrderBy(model => model.Field);
```
and in your view
```C#
@model IQueryable<ResponseModel>

Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "Data");
    })
    .Pageable()
    .Sortable()
```

**Comment by explosiveaction** [comment]
I follow what you are saying now regarding returning an IQueryable to the controller instead of a List, however I can't just return the raw query all the way through to the view to be compiled by the Grid. I need to pass it through a view model first and sanitise or calculate a couple of columns before display. This is why I was looking at the page number, items per page and sort column/direction being directly handled by the DAL so that my view model and the grid itself only had 10 rows to work deal with.

**Comment by Muchiachio** [comment]
If your calculations can be done without involving other classes, I would recommend calculating them directly in the query, using `.Select` statement or AutoMapper.

If not, then there are grid processors which can handle data mutations before or after the data has been fetched from the database, [here's and example](http://mvc-grid.azurewebsites.net/Grid/RowProcessing). Although it is semi-limited if you need to have a lot of other classes to calculate your results, because you would have to pass those classes to the processor class.

Other than that, you would need to override [grid pager's process method](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid.Core/Paging/GridPager.cs#L83) to skip paging and set `TotalRows` from your own variables. Grid paging data is available from request's query.

**Comment by Muchiachio** [comment]
Did you managed to "bind" grid functionality to your will? :smile:

**Comment by engmsalem** [comment]
Hi @Muchiachio ,
I am trying to override   grid pager's process method :
I added new class inherited from GridPager<Person> and I override the method. but where can I use my new class instead of the current pager?
Thanks a lot

**Comment by Muchiachio** [comment]
You should specify your model in the view.

**Comment by engmsalem** [comment]
@Muchiachio Thanks for your reply:
this my implmentation:

 public class GridPagination: GridPager<MyModel> 
    {
        public GridPagination(IGrid<MyModel> grid) : base(grid)
        {}

        public override IQueryable<MyModel> Process(IQueryable<MyModel> items)
        {
            return base.Process(items);
        }
    }
and in my Partial View
 .Pageable(new GridPagination(MyModel)
                                                        {
                                                            PagesToDisplay = 5,
                                                            RowsPerPage = 2,
                                                            TotalRows = Model.FirstOrDefault().TotalNumberOfPages,
                                                        })

but the new GridPagination should have  IGrid of the model which I don't know how to get it to pass it.
Can you please Advise about that?
Thanks

**Comment by Muchiachio** [comment]
The thing you building with `.Pageable` and other methods is `IHtmlGrid` which has a grid instance being built. So you can either use a local view variable to store html grid and use grid from there `IHtmlGrid.Grid` or create an extension with implementation similar to [.Pageable](https://github.com/NonFactors/MVC5.Grid/blob/v7.0.0/src/Mvc.Grid.Core/Html/HtmlGridExtensions.cs#L126-L133), but using your pager.

**Comment by engmsalem** [comment]
@Muchiachio 

I tried the same but I got the following error: 

Severity	Code	Description	Project	File	Line	Suppression State
cannot convert from 'DMIWeb.Common.GridPagination' to 'System.Action<NonFactors.Mvc.Grid.IGridPager<DMIEntities.Entities.MyModel>>'	in _PartialViewForms.cshtml	
I added this variable : @{var grid=((IHtmlGrid<MyModel>)this.Html.Grid(Model)).Grid;}

and use it 
 .Pageable(new GridPagination(grid)
                                                                {
                                                                    PagesToDisplay = 5,
                                                                    RowsPerPage = 2,
                                                                    TotalRows = Model.FirstOrDefault().TotalNumberOfPages,
                                                                })

@using DMIEntities.Entities;
@model IEnumerable<MyModel>

@* Should only include grid declaration *@
@{var grid=((IHtmlGrid<MyModel>)this.Html.Grid(Model)).Grid;}
@(Html
                                                                .Grid(Model)
                                                                .Build(columns =>
                                                                {

                                                                    columns.Add(model => model.FormName).Titled("Name");
                                                                    columns.Add(model => model.FormDescription).Titled("Surname");

                                                                })
                                                                .Empty("No data found")
                                                                .Id("my-ajax-grid")
                                                                .Pageable(new GridPagination(grid)
                                                                {
                                                                    PagesToDisplay = 5,
                                                                    RowsPerPage = 2,
                                                                    TotalRows = Model.FirstOrDefault().TotalNumberOfPages,
                                                                })
                                                                .Filterable()
                                                                .Sortable()
)

Any suggestion please

**Comment by engmsalem** [comment]
@Muchiachio I think adding my own Extension is more clear. Thanks for you kind advice
