### ISSUE TITLE
Grid Ajax call not compatible with jQuery 3.1.1

### ISSUE THREAD

**Issue by morrisnc** [NonFactors/MVC5.Grid#47]
As of jQuery 3.0 the .success and .error functions are deprecated and this code in mvc-grid.js at line 170 uses them: 

`            if (grid.sourceUrl) {
                $.ajax({
                    cache: false,
                    url: grid.sourceUrl + '?' + grid.query
                }).success(function (result) {
                    grid.element.hide();
                    grid.element.after(result);`

Any plans to upgrade support to jQuery 3.x?  I made modifications to fix in my project to get by this issue.

Ed

**Comment by Muchiachio** [comment]
Yes, they will be replace. It's strange that I didn't caught them on my initial check on compatibility with jQuery 3.X.
