### ISSUE TITLE
How to change grid.query on multiple calls to reload Ajax grid

### ISSUE THREAD

**Issue by morrisnc** [NonFactors/MVC5.Grid#48]
I have a need to change the query parameter passed to my controller whenever a user selected value changes.  I have read the GlobalSearch page and tried to duplicate that to no avail.

The first time through this works without issue using this javascript:

`                $('.mvc-grid').mvcgrid({
                    query: 'accountId='+acctId,
                    reload: true
                });`

I have tried using this code from GlobalSearch however the grid variable is always undefined therefore the next line fails.

`        var grid = $('.mvc-grid').data('mvc-grid');
        grid.query = 'search=' + this.value;

        $('.mvc-grid').mvcgrid({
            reload: true
        });`

How to correct?

Ed

**Comment by Muchiachio** [comment]
Hmm, seems like javascript problem.
Could you make a small repro project or use [grid documentation project](https://github.com/NonFactors/MVC5.Grid.Web) to see what's different?

**Comment by morrisnc** [comment]
I found that the grid was never getting initialized with this code:

`// Mvc.Grid binding
$(function () {
    $('.mvc-grid').mvcgrid();
});
`
Working now!
