### ISSUE TITLE
Calculating sum of a column value after reload 

### ISSUE THREAD

**Issue by archanakarthik** [NonFactors/MVC5.Grid#49]
Thanks for all the features on this grid. I have a requirement where I need to calculate the sum of values in particular column of the grid and display it as a footer. This works very well with jquery when pagination is disabled. However, when pagination is enabled, I could get access to only first page/current page rows and hence not able to get sum of ALL rows returned from service. 

I was able to get all rows just before bindPager method call in mvc-grid.js. But since this implementation is one page specific, would not want to change the core js file. Is there anyway I can pass additional values to grid along with data from the controller?

**Comment by Muchiachio** [comment]
There are quite a few ways to go about it. One of the easier ones is making your calculations in the view and then using it in js code to append the footer. At this point data is not paged yet.
````
@model IQueryable<Model>

@{
    Decimal sum = Model.Sum(model => model.Sum);
}
```

**Comment by archanakarthik** [comment]
Thanks for the response. I am using AjaxGrid and there are multiple grids loaded on the same page. 

  $('.mvc-grid').mvcgrid(); is what am using to render the grid and the sourceurl for the grid returns Ienumerable of custom object. Please note the columns settings like title, sortable etc are set in controller method.

At what point can I have access to all the data that is returned by controller method so that I can calculate the total in js.

**Comment by Muchiachio** [comment]
If you are creating grid in the controller, you can access data in the controller, before passing it to the grid.
And return a model with grid instance and sums as model properties or set it to `ViewBag`.

**Comment by archanakarthik** [comment]
Thanks for the response. I understand the ViewBag part. But if I want to send the sum as part of Model property, the controller method currently returns IGrid instance bound to model "TransactionViewModel". Below is the code in partial view with HtmlGrid:
@model IGrid<TransactionViewModel>
@(new HtmlGrid<TransactionViewModel>(Html, Model))

Now, to pass sum from controller as part of model property, it should be added to same view model which is a list and hence the property will be repeated for each item with same value(total) or is there any other way?

Also, how do I access this property in the above said partial view?

**Comment by Muchiachio** [comment]
You don't have to return `IGrid` object, it can be your model, like
```
public class AggregateModel
{
    public IGrid Grid { get; set; }
    public Decimal Sum { get; sum; }
}
```
```
@model AggregateGrid

@(new HtmlGrid(Html, Model.Grid))
```
Other option is to extend [Grid](https://github.com/NonFactors/MVC5.Grid/blob/efa9ae61c49fe1dfbd74e8a1dd9b4490a39a848b/src/Mvc.Grid.Core/Grids/Grid.cs) class with your properties.
So your custom partial view can use `MyGrid` class as it's model and access properties accordingly.

**Comment by archanakarthik** [comment]
Thanks a ton. This works!!
