### ISSUE TITLE
Multi partial ajaxgrid

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#50]
Hi,
How can i put multi partial ajaxgrid in same view?
I tried to give a name to every grid but still not working

**Comment by Muchiachio** [comment]
By multi partial, you mean two ajax grids on the same page?

**Comment by samihatuka** [comment]
Yes. With global search
My View:
@Html.AjaxGrid(Url.Action("IndexGrid"))
@Html.AjaxGrid(Url.Action("IndexGrid2")
How can i find the name of the element from javascript?
In both grid the class is "
mvc-grid"

<script>
    $(document).on('keyup', '.grid-search', function() {
        var grid = $('.mvc-grid').data('mvc-grid');
        grid.query = 'search=' + this.value; // Reset page, filter and sort with new filter.

        $('.mvc-grid').mvcgrid({
            reload: true
        });
    });
</script>

**Comment by Muchiachio** [comment]
Your partial views for `IndexGrid` and `IndexGrid2` need to call `.Named()` with different parameters.

**Comment by Muchiachio** [comment]
Did it work?

**Comment by samihatuka** [comment]
Yes. Thanks
