### ISSUE TITLE
ajax, doesn't work after changes data

### ISSUE THREAD

**Issue by ftrevisani** [NonFactors/MVC5.Grid#51]
Hello,
I have a page with a dropdownlist to filter data.
The grid is defined in a partial view called by an ajax function like that:
`@Html.AjaxGrid(Url.Action("GetPortfolioCompositionGrid", new { idPortfolio = "" }))`

When I change the select index in my dropdownlist, I do somthing like this:
`onchange = @"var selectedID = $(this).val(); $.ajax({ url: 'GetPortfolioCompositionGrid/?idPortfolio=' + selectedID , success: function(data) { $('#element').html(data); }} );"`

After this event, the grid changes with new data, but every functionality like sort, paging, doesn't work.

I think that the page is linked to the old data: if I call in my onchange event this function:
```JS
$('.mvc-grid').mvcgrid({
    reload: true
});
```
the old data will be shown.

Can you help me?

**Comment by Muchiachio** [comment]
You should reload grid using `mvcgrid` function, instead of loading it by hand. Because your load overwrites html without re-initializing the grid functionality. You can do it like this:
```JS
var grid = $('.mvc-grid').data('mvc-grid');
grid.query = 'idPortfolio=' + selectedID;

$('.mvc-grid').mvcgrid({
    reload: true
});
```

Next release will simplify this scenario, so you will be able to refresh grid like this:
```JS
$('.mvc-grid').mvcgrid({
    query = 'idPortfolio=' + selectedID,
    reload: true
});
```

**Comment by ftrevisani** [comment]
Thank you very much.
Is it possible to overwrites html and then re-initializing the grid functionality?

**Comment by Muchiachio** [comment]
I think it would be possible using private grid API's (didn't try), but I don't see why would you do that?

**Comment by ftrevisani** [comment]
I'm trying to do that because I don't want load all data from database server without any filter.

**Comment by Muchiachio** [comment]
You can add your own filter in the controller to return no data on empty portfolio id.
And then add a reasonable no data message with `.Empty("Please select a portfolio")`.

**Comment by ftrevisani** [comment]
Ok. Thank you very much.
