### ISSUE TITLE
How can i button click and insert mvc5.grid ? 

### ISSUE THREAD

**Issue by safakseyrek** [NonFactors/MVC5.Grid#52]
I have master detail grid . Master grid row clicked function. I could not open the second grid? 
How can i insert grid ,after page load?
Help please

**Comment by Muchiachio** [comment]
You could just render a partial view through javascript, which only output the second grid.

**Comment by safakseyrek** [comment]
How can i do it ? I get partial view but doesnt work filter and paging buttons.

**Comment by Muchiachio** [comment]
Every grid needs to be initialized by `$('<grid selector>').mvcgrid();` for client side features to work.

**Comment by safakseyrek** [comment]
I already did it. Grids pager and filter it looks. But doesnt work? Did you try initalized after page loading show grid?

**Comment by safakseyrek** [comment]
Thank u resolve problem , I have to do it 2 times initilazed. thank you
