### ISSUE TITLE
textbox focus keyboard hide on mobile

### ISSUE THREAD

**Issue by thewinner55** [NonFactors/MVC5.Grid#53]
me focus textbox  keyboard hide

**Comment by Muchiachio** [comment]
Yes, there are few problems with mobile devices, which I will be fixing as soon as I get my hand on a mobile device. Thank for reporting.

**Comment by thewinner55** [comment]
try , It good ;
me insert script last record file ( mvc-grid.js )

```

$(function () {
    $('body').append('<div class="mvc-grid-popup"></div>');

    if (/Android|webOS|iPhone|iPad|iPod|Opera Mini/i.test(navigator.userAgent)) {
        // run your code here
    } else {
        $(window).resize(function () {
            $('.mvc-grid-popup').removeClass('open');
        });
    }

    $(document).on("click", ".mvc-grid-cancel", function() {
        $('.mvc-grid-popup').removeClass('open');
    });

});
```

**Comment by Muchiachio** [comment]
Which device are you using? I thought it's closing your filter popup window, like it does on android devices.
But from your example, I seems that keyboard was triggering a window resize?

**Comment by thewinner55** [comment]
I'm not sure. but pass script it Work correctly
device : samsung tab 10.1

I want you to try it.
