### ISSUE TITLE
Html.AjaxGrid not calling controller's action

### ISSUE THREAD

**Issue by vivekdeshmukhhr** [NonFactors/MVC5.Grid#54]
Hello Team,
We are using NonFactor.Mvc.Grid package in our MVC5 application.

As per their example to call AjaxGrid we need to make a call to controller method as

`@Html.AjaxGrid(Url.Action("IndexGrid",new { param = "value"})) `
or
`@Html.AjaxGrid(Url.Action("IndexGrid"))`
Or
`@Html.AjaxGrid(Url.Action("IndexGrid", "ControllerName"))`

But my making same and adding required js reference mentioned in Installation it is not calling controller's action. 
Both views and controller action are in same controller.

Can someone please hint/help how can we get it working?

Thank you so much in advance!

**Comment by Muchiachio** [comment]
Did you called `$('.mvc-grid').mvcgrid();` to initialize it?

**Comment by vivekdeshmukhhr** [comment]
Yes, I did.

**Comment by Muchiachio** [comment]
Hmm, you can try stepping through [this code](https://github.com/NonFactors/MVC5.Grid/blob/develop/src/Mvc.Grid/Scripts/MvcGrid/mvc-grid.js#L22-L43) in your browser and see if source url is set correctly and grid reload is called.

**Comment by vivekdeshmukhhr** [comment]
Thanks for quick response. Will check with this.

**Comment by vivekdeshmukhhr** [comment]
Hi Dear, Identified the problem,  `$('.mvc-grid').mvcgrid();` must be on main view and not on partial view. I can see the view, but now the page number click not working now. Neither console have any error.

Can you please help with this?
Also can I load multiple ajax grid on same page?

**Comment by Muchiachio** [comment]
Yes you can have multiple ajax grid on the same page, they just need to have different names.
But if you are using ajax grid, your grid partial should only render the grid and nothing else.

**Comment by vivekdeshmukhhr** [comment]
Understood. Thanks for clarifications..

**Comment by sajeshd2008** [comment]
i am calling $('.mvc-grid').mvcgrid(); in main view as well still its not calling the action method.

**Comment by Muchiachio** [comment]
Can you share a repro? No errors happening? Debugging js file doesn't show anything suspicious?

**Comment by sajeshd2008** [comment]
The code below shows my implementation in .net core 
Controller:- 
[HttpGet]
        public IActionResult Index()
        { return View(); }
        [HttpGet]
        public PartialViewResult IndexGrid()
        { var result = _personaRepository.AllPersona();
            return PartialView("_IndexGrid", result); }
Main view:-
  @Html.AjaxGrid(Url.Action("IndexGrid"), new { id = "my-ajax-grid"})
 <script>
    $('.mvc-grid').mvcgrid();
    </script>
Partial view:-
 @(Html
            .Grid(Model)
            .Build(columns =>
            {
                columns.Add(model => model.GroupTitle).Titled("GroupTitle");
                columns.Add(model => model.Stig).Titled("Stig");
                columns.Add(model => model.Severity).Titled("Severity");

                //columns.Add(model => model.Age).Titled("Age");
                //columns.Add(model => model.Birthday).Titled("Birthday").Formatted("{0:d}");
                //columns.Add(model => model.IsWorking).Titled("Employed");
            })
            .Empty("No data found")
    .Id("my-ajax-grid")
                .Pageable(pager =>
    {
        pager.PagesToDisplay = 2;
        pager.RowsPerPage = 2;
    })
    .Filterable()
    .Sortable()
        )
Can you share any working repo I can follow?

**Comment by Muchiachio** [comment]
You can checkout [examples repository](https://github.com/NonFactors/AspNetCore.Grid.Web) for core, which has most of the grid api covered. You might need to checkout specific tag version you are using, because newest versions doesn't use jquery.
