### ISSUE TITLE
Css header

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#55]
Hi,
How can i change the style of the headr.
I need to align the header from left to center

**Comment by Muchiachio** [comment]
Em, with css?

**Comment by samihatuka** [comment]
Em? What do you mean?

I meant to the header of the column
.title("headername")

**Comment by Muchiachio** [comment]
Yes so if you want to change header style you will have to write css, like
```CSS
.mvc-grid th {
    color: red;
}
```

**Comment by Muchiachio** [comment]
Did it help?

**Comment by samihatuka** [comment]
Yes. Thanks alot
