### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by wstaelens** [NonFactors/MVC5.Grid#56]
is there a way to show a loader icon when data is loading?

(Btw: great control!)

**Comment by Muchiachio** [comment]
Yes you can bind reload start and ended as per [documentation page](http://mvc-grid.azurewebsites.net/Javascript/ReloadEvents).

**Comment by wstaelens** [comment]
oh ok.
(is there an overview of the full api and all the options? (something like: http://summernote.org/deep-dive/ ) 
because I have not found a TypeScript definition file (.d.ts) and would maybe like to create one to use in TypeScript.

**Comment by Muchiachio** [comment]
Sorry, I don't have a list of API. But example pages cover all possible api calls.

**Comment by Muchiachio** [comment]
Do you have more questions or this issue can be closed out?

**Comment by wstaelens** [comment]
can be closed, will have to test some things first :)
