### ISSUE TITLE
Render as ActionLink?

### ISSUE THREAD

**Issue by Bitzz** [NonFactors/MVC5.Grid#57]
Is there any working implementation of this? I am try to create a render as action link button as follows:

`columns.Add(model => model.ProjectName).Titled("").RenderedAs(m =>  Html.ActionLink("Edit", "EditSourceTable", "SourceTables", new {id = m.ProjectName}));`

But instead of setting the  route value "id" to the ProjectName, it instead infers a length of 12 for every element.

 ie) instead of creating 
http://localhost/SourceTables/EditSourceTable?id=ProjectName
it creates 
http://localhost/SourceTables/EditSourceTable?Length=12

Aside from project name being a bad index- (i know, i know) what am I doing wrong in this case?

**Comment by Bitzz** [comment]
Silly me, I forgot that ActionLink has 2 anonymous objects. Fixed it by changing the action link to:

`Html.ActionLink("Edit", "EditSourceTable", "SourceTables", new {id = m.ProjectName}, new {} )`

**Comment by tanojsaipraveen** [comment]
columns.Add(model => Html.ActionLink("Edit", "Edit", new { id = model.Username }));
