### ISSUE TITLE
How to get total count of rows in NonFactors.Grid.Mvc5 in pager mode

### ISSUE THREAD

**Issue by swastida** [NonFactors/MVC5.Grid#58]
Hi All,

In the following grid how get the total no of rows in the grid after applying the filter.

```C#
 @(Html.Grid(Model.employee).Named("employeeReport")
    .Build(columns =>
    {
        columns.Add(p => p.joiningDate.Date).Titled("Date").Formatted("{0:dd/MM/yyyy}").Filterable(true);
        columns.Add(p => p.Name).Titled("Name").Filterable(true);
        columns.Add(p => p.Department).Titled("Department").Filterable(true);
       
    })
    .MultiFilterable()
    .Sortable()
    .Pageable(pager =>
    {
        pager.CurrentPage = 1;
        pager.RowsPerPage = 10;
    })
)
```
thanks in advance

**Comment by Muchiachio** [comment]
Total row count will only be available after `Grid.Rows` is enumerated, so basically in the grid's partial view.
Why do you need that kind of information, maybe your problem can be solved in a different way?

**Comment by swastida** [comment]
I want to display the total rows above the grid.

**Comment by swastida** [comment]
e.g. 


<div style="text-align:right; margin-right:20px;">
    Total: <span>@Grid.Rows</span>
</div>
@(Html.Grid(Model.employee).Named("employeeReport")
    .Build(columns =>
    {
        columns.Add(p => p.joiningDate.Date).Titled("Date").Formatted("{0:dd/MM/yyyy}").Filterable(true);
        columns.Add(p => p.Name).Titled("Name").Filterable(true);
        columns.Add(p => p.Department).Titled("Department").Filterable(true);
       
    })
    .MultiFilterable()
    .Sortable()
    .Pageable(pager =>
    {
        pager.CurrentPage = 1;
        pager.RowsPerPage = 10;
    })
)

**Comment by Muchiachio** [comment]
You can create your own grid partial for example `_MyGrid.cshtml` and add a total rows.
[Here's](http://mvc-grid.azurewebsites.net/Grid/Partial) an example of writing your own grid partial (basically copy current one and change it).

```HTML
@using NonFactors.Mvc.Grid;
@using System.Linq;

@model IGrid
@{
    IGridRows<Object>[] rows = Model.Rows.ToArray(); // Force enumeration
    Int32 rowCount = Model.Pager != null ? Model.Pager.TotalRows : rows.Length;
}

<div id="@Model.Name" class="mvc-grid">
    ...
</div>

```

**Comment by swastida** [comment]
Thanks for the help
