### ISSUE TITLE
How to load AjaxGrid in div as a Partial view using jquery

### ISSUE THREAD

**Issue by vivekdeshmukhhr** [NonFactors/MVC5.Grid#59]
Hello Team,
We need to load AjaxGrid in div from Jquery.

Existing implementation on view is 
```
<div id="dvProducts">
@Html.AjaxGrid(Url.Action("IndexGrid"))
</div>
```
This works fine; but when we try to load same action in div using jquery as 

`$("#dvProducts").load("IndexGrid")`

It reloads whole page and not just div contents. Also, after doing this, filtering not working.

Can you please help, how to load AjaxGrid in div using Jquery?

Thank You!

**Comment by Muchiachio** [comment]
[Here's](http://mvc-grid.azurewebsites.net/Javascript/Reload) an example of reloading ajax grid.

**Comment by vivekdeshmukhhr** [comment]
Thanks Dear. It worked. was aware abut reload but didn't clicked to use it. 
Thanks for the hint!
