### ISSUE TITLE
Changing visited link style within grid

### ISSUE THREAD

**Issue by archanakarthik** [NonFactors/MVC5.Grid#60]
Hi, 

We have a requirement where the link within the grid needs to change its style if its visited. Something similar to a:visited{color: grey;}. Below is the css definition for the same:

.mvc-grid .reviewButton:visited {
        color:red;
    }

where 'reviewButton' is the class applied on the anchor tag. I can see the color of anchor text changing to red just when we are clicking and navigating to another page but on visiting this page again, it goes back to default style. Please note, unique id is assigned to anchor tag and cache is enabled.

The grid is reloaded via ajax call on loading the page and I believe the DOM is not yet loaded with this anchor tag when the visited style is applied. Please let me know if there is any alternate for this approach.

Thanks in advance,
Archana

**Comment by Muchiachio** [comment]
Not sure if it's grid related, if you successfully open a link it does change to `visited` at least for me.
And it stays that way unless the link url changes.

**Comment by archanakarthik** [comment]
Thanks for your response. Yes, it is grid related where the link is one of the columns in grid. May be in our case, it is not working since we are appending additional values to link url on click. I shall check this. Thanks again.

**Comment by Muchiachio** [comment]
Yes changing url in any way will result in not visited link.
