### ISSUE TITLE
Grouping Headers

### ISSUE THREAD

**Issue by mrajalko** [NonFactors/MVC5.Grid#63]
Is there any method by which some column headers can be grouped together and a title can be assigned to this grouped entity.

**Comment by Muchiachio** [comment]
Currently, no. The only way to do it now is to override `_Grid.cshtml` partial or use a little bit of javascript.
I thought about grouping `colspans` before, but couldn't think of a clean API to do it.

**Comment by mrajalko** [comment]
Thanks for your early response. 

can you please give me a sample on how to override _Grid.cshtml.

**Comment by Muchiachio** [comment]
There is an [example](http://mvc-grid.azurewebsites.net/Grid/Partial) on official page.
You basically need to copy current `_Grid.cshtml` and change header generation.
And then specify your partial then calling `.Grid("_MyGridPartial.cshtml", Model)`.
