### ISSUE TITLE
Primary and Secondary sorting

### ISSUE THREAD

**Issue by archanakarthik** [NonFactors/MVC5.Grid#64]
Is there anyway of specifying the secondary sort column. I need a way to specify the primary and secondary columns for sorting. 

Am currently using InitialSort to sort the primary column.

**Comment by Muchiachio** [comment]
No, there is no way to do that.

You could sort your data in the controller without specifying `InitialSort`, that way you would at least have them sorted by two columns on page load, unless they need to be reordered in any way by the user.

I tried adding it, but currently all the columns are separated from one another and are processing rows one by one in order they were created, changing that would require a lot of breaking changes to be made :disappointed:

**Comment by archanakarthik** [comment]
Thank you. I shall try this and see how it goes. 

Also, wanted to know what does "FirstSort" actually do? 
http://mvc-grid.azurewebsites.net/Column/FirstSort

**Comment by Muchiachio** [comment]
First sort is for setting which order should be used first then ordering a column, default is ascending
`No order -> ascending -> descending -> ascending -> descending -> (...)`

Changing first sort order to descending, would result in
`No order -> descending -> ascending -> descending -> ascending -> (...)`

**Comment by archanakarthik** [comment]
Thank you..
