### ISSUE TITLE
Custom filter not working - Cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by trfletch** [NonFactors/MVC5.Grid#65]
I am trying to setup a custom filter as explained here http://mvc-grid.azurewebsites.net/Column/CustomFilter. My end goal is to have a dropdown filter that lists out the available values for the user to select (this is a status column so it could be Active, Pending, Closed etc) but I have copied the code from the page above exactly and whenever I click on the filter icon I get the following javascript error:

```
Uncaught TypeError: Cannot read property 'first' of undefined
    at CustomTextFilter.render (eval at globalEval (jquery-2.2.1.min.js:2), <anonymous>:16:112)
    at MvcGrid.renderFilter (mvc-grid.js:178)
    at HTMLSpanElement.<anonymous> (mvc-grid.js:106)
    at HTMLSpanElement.dispatch (jquery-2.2.1.min.js:3)
    at HTMLSpanElement.r.handle (jquery-2.2.1.min.js:3)
```

**Comment by Muchiachio** [comment]
Could you share a repro? I copied from the custom filter example page and it worked.

**Comment by trfletch** [comment]
This is the code I am using, the first column filters correctly but the second column shows the error mentioned above in developer tools when clicking on the filter icon:

```
@model IEnumerable<MyProject.TestViewModel>
@using NonFactors.Mvc.Grid;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test</title>

```
    
    <link href="/Content/MvcGrid/mvc-grid.css" rel="stylesheet" />

    
    <script src="/Scripts/jquery-2.2.1.min.js"></script>
    <script src="/Scripts/MvcGrid/mvc-grid.js"></script>
</head>
<body>
    <div>

        @(Html
    .Grid(Model)
    .Build(columns =>
    {

        // Reference
        columns.Add(item => item.Reference)
        .Titled("Reference");

        // Quote status
        columns.Add(item => item.QuoteStatusName)
        .Titled("Status")
        .FilteredAs("Custom");

    })
    .Filterable()
    .Sortable()
    .Pageable(pager =>
    {
        pager.RowsPerPage = 20;
    })
    .Empty("No records available")
        )

    </div>

    <script>

        var CustomTextFilter = (function () {
            function CustomTextFilter() {
            }

            CustomTextFilter.prototype = {
                render: function (grid, popup, filter) {
                    popup.html(
                        '<div class="popup-arrow"></div>' +
                        '<div class="popup-content">' +
                            '<div class="first-filter popup-group">' +
                                '<input class="mvc-grid-input" placeholder="Contains" type="text" value="' + filter.first.val + '">' +
                            '</div>' +
                            (filter.isMulti ?
                            '<div class="popup-group popup-group-operator">' +
                                '<select class="mvc-grid-operator">' +
                                    '<option value=""></option>' +
                                    '<option value="And"' + (filter.operator == 'And' ? ' selected="selected"' : '') + '>And</option>' +
                                    '<option value="Or"' + (filter.operator == 'Or' ? ' selected="selected"' : '') + '>Or</option>' +
                                '</select>' +
                            '</div>' +
                            '<div class="second-filter popup-group">' +
                                '<input class="mvc-grid-input" placeholder="Contains" type="text" value="' + filter.second.val + '">' +
                            '</div>' :
                            '') +
                            '<div class="popup-button-group">' +
                                '<button class="btn btn-success mvc-grid-apply" type="button">✔</button>' +
                                '<button class="btn btn-danger mvc-grid-cancel" type="button">✘</button>' +
                            '</div>' +
                        '</div>');
                },

                init: function (grid, column, popup) {
                    this.bindValue(grid, column, popup);
                    this.bindApply(grid, column, popup);
                    this.bindCancel(grid, column, popup);
                },
                bindValue: function (grid, column, popup) {
                    var inputs = popup.find('.mvc-grid-input');
                    inputs.on('keyup.mvcgrid', function (e) {
                        if (e.which == 13) {
                            popup.find('.mvc-grid-apply').click();
                        }
                    });
                },
                bindApply: function (grid, column, popup) {
                    var apply = popup.find('.mvc-grid-apply');
                    apply.on('click.mvcgrid', function () {
                        popup.removeClass('open');
                        column.filter.first.type = 'Contains';
                        column.filter.second.type = 'Contains';
                        column.filter.operator = popup.find('.mvc-grid-operator').val();
                        column.filter.first.val = popup.find('.first-filter .mvc-grid-input').val();
                        column.filter.second.val = popup.find('.second-filter .mvc-grid-input').val();

                        grid.applyFilter(grid, column);
                        grid.reload(grid);
                    });
                },
                bindCancel: function (grid, column, popup) {
                    var cancel = popup.find('.mvc-grid-cancel');
                    cancel.on('click.mvcgrid', function () {
                        popup.removeClass('open');

                        if (column.filter.first.type || column.filter.second.type) {
                            grid.cancelFilter(grid, column);
                            grid.reload(grid);
                        }
                    });
                }
            };

            return CustomTextFilter;
        })();

        $('.mvc-grid').mvcgrid({
            filters: {
                'Custom': new CustomTextFilter()
            }
        });


    </script>

</body>
</html>

**Comment by Muchiachio** [comment]
I tried copy pasting this code and it worked on my project, it seems like there is a misconfiguration of some sort in your solution. If you can create/share a whole repro project I'll be willing to look into it. Or you can debug js and check for the root cause.

**Comment by trfletch** [comment]
I resolved the issue by updating using Nuget from version 2.3.2 to version 3.4.0.
