### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#66]
Hi ,
How to refresh grid evrey x seconds or after changes in database without clicking on the button?
Thank you

**Comment by Muchiachio** [comment]
Use javascript's `setInterval` to call refresh function every `x` seconds:
```JS
var x = 60000;
setInterval(function() {
    $('.mvc-grid').mvcgrid({
        reload: true
    });
}, x);
```

**Comment by Muchiachio** [comment]
Did you manage to solve your issues?

**Comment by samihatuka** [comment]
Yes. Thank you!
