### ISSUE TITLE
Ajax grid pushstate

### ISSUE THREAD

**Issue by N30NF15H** [NonFactors/MVC5.Grid#67]
Do you have pushstate in the pipeline for ajax grid? I've modified the code myself to update the query string in the url, but I'm no JS expect so it's not great...

Cheers

**Comment by Muchiachio** [comment]
What do you mean by pushstate? You need some kind of event triggered by the grid or something else?

**Comment by N30NF15H** [comment]
I'd like to use query string parameters for the ajax grid the same way they work for postback, so I can copy the link and send it to someone and they can see the same filter.

**Comment by Muchiachio** [comment]
Why not use a simple grid then? You can get current ajax query from the grid instance if you want.

**Comment by Muchiachio** [comment]
Do you have any more comments or you have solved your issue?

**Comment by N30NF15H** [comment]
Sorry forgot to respond. This grid works really well although I didn't want to refresh the whole page to keep page loading times down,  so I modified the code to change the url with JavaScript while using Ajax.

**Comment by Muchiachio** [comment]
If you just want to change the browser url after grid is being reloaded, you can use grid's `reloadStarted` or `reloadEnded` events, from which you can access the current query `grid.query`.

**Comment by N30NF15H** [comment]
I used the events and I think I got it

$('.mvc-grid').mvcgrid({
	reloadStarted: function (grid) {
		if (history.pushState) {
			if (grid.query != "") {
				var splitIndex = window.location.href.indexOf('?');
				if (splitIndex > -1) {
					if (window.location.search.replace('?', '') != grid.query)
						history.pushState({}, "", window.location.href.substring(0, splitIndex) + '?' + grid.query);
				} else {
					history.pushState({}, "", window.location.href + '?' + grid.query);
				}
			} else {
				var splitIndex = window.location.href.indexOf('?');
				grid.query = "";
				if (splitIndex > -1) {
					grid.query = window.location.search.replace('?', '');
				}
			}
		}
	},
	reloadEnded: function (grid) {
		window.onpopstate = function (e) {
			var splitIndex = e.target.location.href.indexOf('?');
			grid.query = "";
			if (splitIndex > -1) {
				grid.query = e.target.location.search.replace('?', '');
			}

			grid.reload(grid)
		};
	},
});

**Comment by Muchiachio** [comment]
Yes something like that.
