### ISSUE TITLE
Tabs with partial Views not paging correctly on the selected tab

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#69]
Hi

I have 3 tabs.  Each tab displaying a collection of data (Web Orders, Orders, Invoices).  Each tab is a partial View.  When clicking on the paging the paging would go to the different tabs rather then paging on the collection of data.

        <div id="tabs-1" class="tab-pane fade in active>
            @Html.Action("_CustomerWebOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })

        <div id="tabs-2" class="tab-pane fade">
            @Html.Action("_CustomerOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
        </div>

        <div id="tabs-3" class="tab-pane fade">
            @Html.Action("_CustomerInvoices", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
        </div>

So I added the **pager.PartialViewName = "_CustomersOrder";**  I am now getting this error message.

**The model item passed into the dictionary is of type** 'NonFactors.Mvc.Grid.Grid`1[App.Models.Dto.OrderDto]', but this dictionary requires a model item of type 'System.Collections.Generic.IEnumerable`1[App.Models.Dto.OrderDto]'.

How do I fix the error message.

**View**

     @using NonFactors.Mvc.Grid;
     @model  IEnumerable<App.Models.Dto.OrderDto>
     @(Html
        .Grid("_CustomerOrders",Model)
        .Build(columns =>
        {
           columns.Add(model => model.Order_ID).Titled("Order ID");
           columns.Add(model => model.Ship_To_Name).Titled("Ship To Name");
           columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
           columns.Add(model => model.Added_Date).Titled("Order Date");
           columns.Add(model => model.Order_Total_Amt).Titled("Order Amount");
        })
       .Pageable(pager =>
       {
           pager.PartialViewName = "_CustomerOrders";
           pager.PagesToDisplay = 3;
           pager.CurrentPage = 2;
           pager.RowsPerPage = 2;
       })
      )

**Controller**

            var orderModel = _orderRepo.GetOrders(customerId, sortOrder);
            //Load Dto
            var orderList = orderModel.Select(o => new OrderDto
            {
                Order_ID = o.Order_ID,
                Ship_To_Code = o.Ship_To_Code,
                Ship_To_Name = o.Ship_To_Name,
                Customer_Po_Nbr = o.Customer_Po_Nbr,
                Added_Date = o.Added_Date,
                Order_Total_Amt = o.Order_Total_Amt
            }).ToList();

            customerVM.OrderDtos = orderList;
            return PartialView("_CustomerOrders", customerVM.OrderDtos);

**Comment by Muchiachio** [comment]
What is grid doing wrong here?

**Comment by retthom** [comment]
When paging within the tab the paging was not working correctly.

When I added the following 2 lines of code in the view.

Html
    .Grid("_CustomerOrders",Model)

pager.PartialViewName = "_CustomerOrders";

Now I get this error message.

The model item passed into the dictionary is of type 'NonFactors.Mvc.Grid.Grid1[App.Models.Dto.OrderDto]', but this dictionary requires a model item of type 'System.Collections.Generic.IEnumerable1[App.Models.Dto.OrderDto]'.

**Comment by Muchiachio** [comment]
Yes, because you are overriding grid pager rendering partial as per [this example](http://mvc-grid.azurewebsites.net/Pager/SelectableRowsPerPage). If you want to change grid pager rendering you have to use `IGrid` as a model and if you just want to render your own data in a partial you don't have to use `PartialViewName`.

**Comment by retthom** [comment]
Okay.

I am sorry.

I did not page down far enough in your example.

Thanks

**Comment by retthom** [comment]
Hi,

I still can't get this to do paging.

The data is showing in the view

I have a customer entity that contain the Customer Info,  Orders, Invoices and Shipments.

The grid is displaying the collection of orders for the customer.  The problem is that when
 I click on the paging it getting confused with the Tabs.  How do I get this to page on just the grid and not get confused with the tab.

I would think this should work without using the custom partial.

**Tabs**

    <div id="tabs-1" class="tab-pane fade in active>
        @Html.Action("_CustomerWebOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })

    <div id="tabs-2" class="tab-pane fade">
        @Html.Action("_CustomerOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
    </div>

    <div id="tabs-3" class="tab-pane fade">
        @Html.Action("_CustomerInvoices", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
    </div>


**View**

I am passing the the collection from the customer entity like this
IEnumerable<App.Models.Dto.OrderDto>

 @using NonFactors.Mvc.Grid;
 @model  IEnumerable<App.Models.Dto.OrderDto>
 @(Html
    .Grid(Model)
    .Build(columns =>
    {
       columns.Add(model => model.Order_ID).Titled("Order ID");
       columns.Add(model => model.Ship_To_Name).Titled("Ship To Name");
       columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
       columns.Add(model => model.Added_Date).Titled("Order Date");
       columns.Add(model => model.Order_Total_Amt).Titled("Order Amount");
    })
   .Pageable(pager =>
   {
       pager.PagesToDisplay = 3;
       pager.CurrentPage = 2;
       pager.RowsPerPage = 2;
   })
  )

**Controller**

        var orderModel = _orderRepo.GetOrders(customerId, sortOrder);
        //Load Dto
        var orderList = orderModel.Select(o => new OrderDto
        {
            Order_ID = o.Order_ID,
            Ship_To_Code = o.Ship_To_Code,
            Ship_To_Name = o.Ship_To_Name,
            Customer_Po_Nbr = o.Customer_Po_Nbr,
            Added_Date = o.Added_Date,
            Order_Total_Amt = o.Order_Total_Amt
        }).ToList();

        customerVM.OrderDtos = orderList;
        return PartialView("_CustomerOrders", customerVM.OrderDtos);
