### ISSUE TITLE
Still having problems with the tabs and grid issue

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#70]
Hi,

I still can't get this to do paging.

The data is showing in the view

I have a customer entity that contain the Customer Info,  Orders, Invoices and Shipments.

The grid is displaying the collection of orders for the customer.  The problem is that when
 I click on the paging it getting confused with the Tabs.  How do I get this to page on just the grid and not get confused with the tab.

I would think this should work without using the custom partial.

**Tabs**

    <div id="tabs-1" class="tab-pane fade in active>
        @Html.Action("_CustomerWebOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })

    <div id="tabs-2" class="tab-pane fade">
        @Html.Action("_CustomerOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
    </div>

    <div id="tabs-3" class="tab-pane fade">
        @Html.Action("_CustomerInvoices", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
    </div>

**View**

I am passing the the collection from the customer entity like this

Coming the:
**Controller**
        customerVM.OrderDtos = orderList;
        return PartialView("_CustomerOrders", customerVM.OrderDtos);

**View**
       IEnumerable<App.Models.Dto.OrderDto>

      @using NonFactors.Mvc.Grid;
      @model  IEnumerable<App.Models.Dto.OrderDto>
      @(Html
         .Grid(Model)
         .Build(columns =>
         {
            columns.Add(model => model.Order_ID).Titled("Order ID");
            columns.Add(model => model.Ship_To_Name).Titled("Ship To Name");
            columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
            columns.Add(model => model.Added_Date).Titled("Order Date");
            columns.Add(model => model.Order_Total_Amt).Titled("Order Amount");
         })
        .Pageable(pager =>
        {
            pager.PagesToDisplay = 3;
            pager.CurrentPage = 2;
            pager.RowsPerPage = 2;
        })
       )

**Controller**

        var orderModel = _orderRepo.GetOrders(customerId, sortOrder);
        //Load Dto
        var orderList = orderModel.Select(o => new OrderDto
        {
            Order_ID = o.Order_ID,
            Ship_To_Code = o.Ship_To_Code,
            Ship_To_Name = o.Ship_To_Name,
            Customer_Po_Nbr = o.Customer_Po_Nbr,
            Added_Date = o.Added_Date,
            Order_Total_Amt = o.Order_Total_Amt
        }).ToList();

        customerVM.OrderDtos = orderList;
        return PartialView("_CustomerOrders", customerVM.OrderDtos);

**Comment by Muchiachio** [comment]
If you are using multiple grids on the same page, you have to name every grid using `Named` method.
Otherwise there is no way to bind sorting/filtering/paging to a unique grid.
You can see naming [example](http://mvc-grid.azurewebsites.net/Grid/Multiple) here.

**Comment by retthom** [comment]
Yes.. I tried that too.

The problem is that the grid seems to be having problems with multiple grids in a tabs.

When clicking the next page the grid does not know what grid in the tab to page on.

Here's what it looks like:

With adding     **.Named("CustomerOrder")**

If I'm in tab 2  **"_CustomerOrders"**.  When paging it's not returning back to tab 2 to do the paging.  It's going to tab 1 **"_CustomerWebOrders"**. 

**http://localhost:49308/Customer?CustomerOrder-Page=3&CustomerOrder-Rows=2**


**Tabs:**

      <div id="tabs-1" class="tab-pane fade">
        @Html.Action("_CustomerWebOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
      </div>

      <div id="tabs-2" class="tab-pane fade">
        @Html.Action("_CustomerOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
      </div>

      <div id="tabs-3" class="tab-pane fade">
        @Html.Action("_CustomerInvoices", "Customer", new { m = Model, sortData = ViewBag.CurrentSort })
     </div>

**Comment by Muchiachio** [comment]
Yes, it wont be back because normal grid does a full page refresh, you would have to use ajax grid to not refresh the page.

**Comment by retthom** [comment]
Beautiful!!!!

It's working now.

I like this grid because it keeps my code clear and I am not spending a lot of my time laying out a grid.

Thanks for your help.
