### ISSUE TITLE
Icons instead cell value

### ISSUE THREAD

**Issue by fabriziotrevisani** [NonFactors/MVC5.Grid#71]
Hello,
is it possible to show an icon instead of model field value in a cell?
I have a field of my source data that can assume one of these value: INFO, WARN, ERROR. I would like to show three images instead of text.

Thank you.

**Comment by Muchiachio** [comment]
Yes you can, columns `Add` and `Render` methods are using your expression to evaluate the value.
So you just have to render an image in there and disabled html encoding for that column.
[Here](http://mvc-grid.azurewebsites.net/Column/Encoding) are some examples on how to render html in a cell.

**Comment by fabriziotrevisani** [comment]
Thank you.
