### ISSUE TITLE
Column filtering dropdown

### ISSUE THREAD

**Issue by pkapare** [NonFactors/MVC5.Grid#72]
Default column filtering implementation is we have filter operator dropdown i.e. Contains, Equals, Not Equals, Starts With, Ends with and textbox for filter value. Is there any way where in we can replace filter value textbox with dropdown populated with unique values from columns so that user don't need to type filter value but select it from dropdown. Any pointers on this will be much appreciated.
Thanks

**Comment by Muchiachio** [comment]
Yes, you can register a custom filter, [here's](http://mvc-grid.azurewebsites.net/Filter/Register) an example on that.

**Comment by pkapare** [comment]
Thanks. This worked Great. Link was very helpful.
