### ISSUE TITLE
Using Search with tab and getting the wrong controller action

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#73]
I have 3 tabs displaying a grid.  The grid are working correctly within the tabs.  When I added the "Grid global search".  The search is not always calling the correct Controller Action.

For example : If I'm on the invoice tab **"CustomerInvoice"** and searching for a customer PO the controller action that is being called is **"CustomerOrder"**.

When searching how do I make sure the correct controller action is being called.

**I used this to allow a user to determine what to search on:**

    <div class="form-group">
        @Html.LabelFor(model => model.Search_Option_Code, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(model => model.Search_Option_Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Search_Option_Code, "", new { @class = "text-danger" })
        </div>
    </div>

**Add data to search:**

    <input class="grid-search" />

**Tabs:**

    <div class="tab-content">
        <div id="tabs-1" class="tab-pane fade in active">
           @Html.AjaxGrid(Url.Action("_CustomerWebOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort }))
        </div>

        <div id="tabs-2" class="tab-pane fade">
            @Html.AjaxGrid(Url.Action("_CustomerOrders", "Customer", new { m = Model, sortData = ViewBag.CurrentSort }))
        </div>

        <div id="tabs-3" class="tab-pane fade">
            @Html.AjaxGrid(Url.Action("_CustomerInvoices", "Customer", new { m = Model, sortData = ViewBag.CurrentSort }))
        </div>
    </div>

    <script type="text/javascript">

       $(document).ready(function () {
           $('.mvc-grid').mvcgrid();
  
          $(".grid-search").on('keyup', function () {
              var searchOption = $("#Search_Option_Code").val();
              if (searchOption !== "") {
                   $('.mvc-grid').mvcgrid({
                      query: 'searchTerm=' + this.value + "|" + searchOption,
                      reload: true
                   });
               }
           });
        })
     </script>

**Comment by Muchiachio** [comment]
`$('.mvc-grid')` selector includes all three grids and assigns them the same configuration.
You have to be more specific, you can used grid's `.Named("MyId")` method to assign each grid instance and id and then initialize specific grid using `$('#MyId').mvcgrid()`.

**Comment by retthom** [comment]
I made the changes to initialize each grid.  Now the grid's are no longer working. 

I also added the ".grid-mvc" class.

Added:

     <script type="text/javascript">

      $(document).ready(function () {
          $('#CustomerWebOrder').mvcgrid();
         $('#CustomerOrder').mvcgrid();
         $('#CustomerInvoice').mvcgrid();

          $(".grid-search").on('keyup', function () {
              var searchOption = $("#Search_Option_Code").val();
              if (searchOption !== "") {
                  $('.mvc-grid').mvcgrid({
                      query: 'searchTerm=' + this.value + "|" + searchOption,
                      reload: true
                  });
              }
          });
        })
     </script>

Tab Grid:

      @(Html
        .Grid(Model)
        .Build(columns =>
        {
             columns.Add(model => model.Invoice_ID).Titled("Invoice ID");
             columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
             columns.Add(model => model.Invoice_Date).Titled("Invoice Date");
             columns.Add(model => model.Total_Invoice_Amt).Titled("Invoice Amount");
       })
**.Named("CustomerInvoice")**
      .Pageable(pager =>
      {
         pager.PagesToDisplay = 10;
         pager.CurrentPage = 1;
         pager.RowsPerPage = 13;
      })
    )

**Comment by Muchiachio** [comment]
I was talking about this part
```JS
$('.mvc-grid').mvcgrid({
    query: 'searchTerm=' + this.value + "|" + searchOption,
    reload: true
});
```
because with these lines
```JS
$('#CustomerWebOrder').mvcgrid();
$('#CustomerOrder').mvcgrid();
$('#CustomerInvoice').mvcgrid();
```
you are telling `initialize grid named CustomerWebOrder, CustomerOrder and CustomerInvoice, one by one`, you could easily just use `$('.mvc-grid').mvcgrid()` meaning `initialize all grids on the page.

While this search
```JS
$('.mvc-grid').mvcgrid({
    query: 'searchTerm=' + this.value + "|" + searchOption,
    reload: true
});
```
means, `refresh every grid on the page with given query`, but I guess you would want to refresh only one grid with search parameters? By doing this
```JS
$('#CustomerInvoice').mvcgrid({
    query: 'searchTerm=' + this.value + "|" + searchOption,
    reload: true
});

```
As for controller action for invoices grid, it will use the same action you specified in grid's declaration, so whatever is generated by this `Url.Action("_CustomerInvoices", "Customer", ...)` call with added query parameters.

**Comment by retthom** [comment]
Thanks for the quick response and your help!

It's working now.  I understand what I was doing wrong.
