### ISSUE TITLE
How to get the grid filtering box data

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#74]
Hi

I tried to capture the data being entered in the grid filter.  When I click the check button I can see my controller being executed.  But I can't capture the data from the filter box.

What jquery can I use to capture the data from the filter box and pass that data back to the controller?

I thought "grid-search' would do that but the jquery is never being fired.

**Comment by Muchiachio** [comment]
Which filter box do you mean, grid one or your created one?

**Comment by retthom** [comment]
Sorry for that.

I am talking about the grid filter.

**Comment by Muchiachio** [comment]
Grid filters are only available from `Request.QueryString`, in a form of:
`"<Grid name>-<Column name>-<Filter type>=<Filter value>"`.

**Comment by retthom** [comment]
Got it.

Over thinking this.

Thanks
