### ISSUE TITLE
How to add hyperlink columns

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#75]
Do you have an example on how to add hyperlinks to the grid.
```
@Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = item.Order_ID }, new { target = "_blank" })

    @(Html
      .Grid(Model)
      .Build(columns =>
      {
          columns.Add(model => model.Order_ID).Titled("Order ID");
          columns.Add(model => model.Ship_To_Name).Titled("Ship To Name");
          columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
          columns.Add(model => model.Added_Date).Titled("Order Date").Filterable(true);
          columns.Add(model => model.Order_Total_Amt).Titled("Order Amount").Filterable(false);

 **@Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = item.Order_ID }, new { target = "_blank" })** 


      })
      .Filterable()
      .Named("CustomerOrder")
      .Pageable(pager =>
      {
          pager.PagesToDisplay = 10;
          pager.CurrentPage = 1;
          pager.RowsPerPage = 13;
      }) 
   )
```

**Comment by Muchiachio** [comment]
Does [this](http://mvc-grid.azurewebsites.net/Column/Encoding) help?

**Comment by retthom** [comment]
So I make this a string

@Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = item.Order_ID }, new { target = "_blank" })

and add "Encoder"

**Comment by retthom** [comment]
So I make this a string

@Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = item.Order_ID }, new { target = "_blank" })

and add "Encode"

**Comment by Muchiachio** [comment]
You don't have to `HtmlString` will not be encoded by default, like in `Html.CheckBox` example.
So you can use it without `ToString`ing it.

**Comment by retthom** [comment]
Trying it now.

**Comment by retthom** [comment]
It's working now.

columns.Add(model -> Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = item.Order_ID }, new { target = "_blank" }))
