### ISSUE TITLE
Can I use If-else-statements in a grid

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#76]
Hi

How would I do an if-else-statement within a grid.

Should I use a "Helper"?

     @(Html
         .Grid(Model)
         .Build(columns =>
         {
             columns.Add(model => model.Order_ID).Titled("Order ID");
             columns.Add(model => model.Ship_To_Name).Titled("Ship To Name");
             columns.Add(model => model.Customer_Po_Nbr).Titled("PO Number");
             columns.Add(model => model.Added_Date).Titled("Order Date").Filterable(true);
             columns.Add(model => model.Order_Total_Amt).Titled("Order Amount").Filterable(false);

 **if(Model.OrderID != null)
{
      columns.Add(model => Html.ActionLink("PDF file", "ShowPdf", "Order", new { orderID = model.Order_ID }, new { target = "_blank" }));
 }
 else
 {
    columns.Add(model => "No Image");
 }**
 
            })
            .Filterable()
            .Named("CustomerOrder")
            .Pageable(pager =>
            {
                pager.PagesToDisplay = 10;
                pager.CurrentPage = 1;
                pager.RowsPerPage = 13;
            })
         )

**Comment by Muchiachio** [comment]
You can only use short if statements or function calls in Add method to render a value:
`columns.Add(model => model.IsCondition ? Html.ActionLInk(...) : new HtmlString("No image"));`

**Comment by retthom** [comment]
Great!!!

Thanks
