### ISSUE TITLE
Custom filter in ajax grid?

### ISSUE THREAD

**Issue by MartinTittensor** [NonFactors/MVC5.Grid#77]
Hi, I'm trying to apply custom filtering to a column in an ajax grid. I've declared this function:
```
function initGrid() {
  $('.mvc-grid').mvcgrid({
    filters: {
      'MyFilt': new MyFilter()
    }
  });
}
```
Which I call in the document.ready method. And I use this to create my grid:
```
@Html.AjaxGrid(Url.Action("IndexGrid"))
```
When filtering, the URL seems to include the correct parameters, e.g.

`?Grid-Status-Equals=42&_=1491490855281`

(I'm not sue what that _ parameter is supposed to be, but I don't think it's a problem). Anyway, the response from that query doesn't look right. Here's the **th** for the Status column which I'm trying to filter:
```
<th class="filterable sortable"
                        data-name="Status"
                        data-filter="True"
                        data-filter-name="MyFilt"
                        data-filter-multi=""
                        data-filter-first-type="" <-- I don't think this should be empty...
                        data-filter-first-val="" <-- ...or this
                        data-filter-operator=""
                        data-filter-second-type=""
                        data-filter-second-val=""
                        data-sort="True"
                        data-sort-order=""
                        data-sort-first="">
                            <span class="mvc-grid-header-title ">Status</span>
                                                    <span class="mvc-grid-filter "></span>
                    </th>
```
I would expect the **data-filter-first-type** to be set to "Equals" and the **data-filter-first-val** to be set to "42" in the response. That seems to be what happens when using a 'built-in' text filter, for example.

Also, when I bring the filter dialog up again, the filter object has been reset. This doesn't happen with the 'built-in' filters (text, bool, date etc). I notice in the debugger that the createColumn function is rebuilding the filters, but for the column that I'm interested in, the header.data doesn't have the data it needs to rebuild my filter:

![image](https://cloud.githubusercontent.com/assets/22616381/24797696/47e6b9e8-1b8a-11e7-89cf-cf3109f9f1f2.png)

Again, the built-in filters seem to behave differently. Even if I replace `new MyFilt()` with new new `MvcGridNumberFilter()` (i.e. using a built-in filter as a custom filter), then filtering still doesn't work.

I'm _extremely_ new to Javascript and Ajax. If I'm doing something stupid then I hope you can forgive me.

**Comment by Muchiachio** [comment]
Did you register your filter on application start and followed [these custom filter usage steps](http://mvc-grid.azurewebsites.net/Filter/Register)?

**Comment by MartinTittensor** [comment]
Thanks @Muchiachio.

Ah, no, I didn't do that. I was following the steps for [column custom filters](http://mvc-grid.azurewebsites.net/Column/CustomFilter), which I now see is referring to replacement interfaces for filters which already registered (presumably by the MVC Grid DLL?).

What I need is to match on an `enum` type. Equality and inequality should be enough. Would I be correct in thinking that I'll need to register two filters? Something like:
```
MvcGrid.Filters.Register(typeof(MyEnum), "Equals", typeof(EnumEqualsFilter));
MvcGrid.Filters.Register(typeof(MyEnum), "Not Equals", typeof(MyEnumNotEqualsFilter));
```
And then have those two filter types each override the `Apply` method? If so, I'll just need to read up about `Expression`s! Could you show how your numeric filter does that as an example?

**Comment by Muchiachio** [comment]
You can check the source code at this repository, number filter is [here](https://github.com/NonFactors/MVC5.Grid/blob/16e9da0979201d37ab42403598ff71e429424cae/src/Mvc.Grid.Core/Filtering/Number/NumberFilter.cs).

**Comment by MartinTittensor** [comment]
Thanks. That seems to have done the trick.
