### ISSUE TITLE
Cannot read property 'Filter' of undefined

### ISSUE THREAD

**Issue by tareq2** [NonFactors/MVC5.Grid#79]
Hello,
I have used the grid with MVC5.Template but i have changed the template to another one and everything is working fine except the filtering i have got the following error (from developer console)
```
Uncaught TypeError: Cannot read property 'Filter' of undefined
    at MvcGridTextFilter.render (mvc-grid.js?bundleVirtualPath=~%2fbundles%2fmvcGrid:367)
    at MvcGrid.renderFilter (mvc-grid.js?bundleVirtualPath=~%2fbundles%2fmvcGrid:220)...
```
This [template](https://wrapbootstrap.com/theme/beyondadmin-responisve-admin-app-WB06R48S4) is using jQuery v2.1.3 and  Bootstrap 3.3.6 .
Could anyone please help here.

**Comment by Muchiachio** [comment]
Check if you are not overwriting `$.fn.mvcgrid.lang` to null somewhere in your code.

**Comment by tareq2** [comment]
Thank you for this hint.
The problem was from the missing lang attribute in html tag
