### ISSUE TITLE
Grid Footer

### ISSUE THREAD

**Issue by mkchmiel** [NonFactors/MVC5.Grid#80]
Is there any way of adding a footer for totals?

**Comment by Muchiachio** [comment]
Nothing built in, you would have to add them by hand.
I think it's possible to add them, I will just have to think of a way to do it for next release.

**Comment by mkchmiel** [comment]
Thanks, much appreciated. By the way lowing your grids compared to the others I have used. Keep up the good work.

**Comment by guidozanon** [comment]
Hi guys, this is what I did to add a footer with totals:
- Changed Grid.cshtml adding following code where the footer should be displayed
```
if (ViewBag.SumirizePartialView != null)
{
	@Html.Partial((string)ViewBag.SumirizePartialView, Model.Rows)
}
```
- Add a new partial view with the footer view as following:
`
@model IGridRows<ExpenseGridModel>
@using NonFactors.Mvc.Grid;
<tr class='bold'>
	<td></td>
	<td colspan="2">Subtotales</td>
	<td colspan="4" class='column-right'>@Model.Sum(c => c.Model.Amount).ToString("C")</td>
	<td></td>
	<td></td>
	<td></td>
</tr>
`
- Finaly in the view where the grid will be displayed you will have to add the viewbag property:
`
@{
	ViewBag.SumirizePartialView = "ExpenseGridSumarize";
}
`
This example will only sum the visible rows.

@Muchiachio It will cool if you can add a new argument called FooterView to Html.Grid in order to display that footer if not null or empty.

Hope this help!

**Comment by Muchiachio** [comment]
@guidozanon I was thinking of making an aggregate method for each column, like
```C#
columns.Add(model => model.Amount).Aggregate(~Sum~);
```
But your solution is actually better, because mine wouldn't allow to add footer row text like
`<td colspan="2">Subtotales</td>`, which will most likely be needed.

**Comment by mkchmiel** [comment]
Hi @Muchiachio,

Any thoughts as to when the next release will be? Not sure if I should just pull the project from here to build and test or wait for your new release.

**Comment by Muchiachio** [comment]
It will take at least few weeks or even a month before I push all the breaking changes.
So we are looking at mid-late June.

**Comment by mkchmiel** [comment]
@Muchiachio That makes sense, thanks for the quick response.

**Comment by tareq2** [comment]
Is there any workaround to @guidozanon solution when using paging?

**Comment by Muchiachio** [comment]
Paging should work with that @tareq2.

**Comment by tareq2** [comment]
The aggregate is just for the current page but i want it for all the data ,I think the problem is from **Model.Rows** which  contains just the current page .

**Comment by Muchiachio** [comment]
You can aggregate on `Grid.Source` which is the initial data source you specified.

**Comment by tareq2** [comment]
Still i need the filters

**Comment by Muchiachio** [comment]
What do you mean you need filters?

**Comment by Muchiachio** [comment]
You will have to run this somewhere then
```C#
IQueryable<T> items = Grid.Source;
    foreach (IGridProcessor<T> processor in Grid.Processors.Where(proc => proc.ProcessorType == GridProcessorType.Pre))
        items = processor.Process(items);
```

**Comment by tareq2** [comment]
Thank you i have put the code in the partial view .

**Comment by simone40love** [comment]
Search for footer in the examples. But the documentation is wrong.
Instead of:
`.UsingFooter("_GridFooter")`
It's
`.WithFooter("_GridFooter")`
