### ISSUE TITLE
RFE: allow defining columns without an expression

### ISSUE THREAD

**Issue by fsateler** [NonFactors/MVC5.Grid#82]
That is, and `Add` overload without parameters. Useful for eg, a column that will display Details/Edit links.
What I end up doing is something like this:
```C#
col.Add(m => m.Id).RenderedAs(item => Html.ActionLink(T("Edit"), "Edit", new { id = item.Id }))
```
The expression here is totally superfluous.

**Comment by Muchiachio** [comment]
Yes, this is something I will add in the major next release together with the new extensions.

**Comment by Muchiachio** [comment]
And you can actually add links in side the `Add` method or you are doing something different?

**Comment by fsateler** [comment]
what I end up doing is something like this:

```csharp
col.Add(m => m.Id)
    .RenderedAs(item => Html.ActionLink(Trans.T("Edit"), "Edit", new { id = item.Id }))
```

The expression here is totally superfluous.

**Comment by Muchiachio** [comment]
Yes, but you can do
```C#
col.Add(m => Html.ActionLink(Trans.T("Edit"), "Edit", new { id = m.Id }))
```
