### ISSUE TITLE
Pageable does not work

### ISSUE THREAD

**Issue by Dallas411** [NonFactors/MVC5.Grid#83]
I try to use Pageable like this example http://mvc-grid.azurewebsites.net/Grid/Paging but the footer pager not works.

thanks

Marco

**Comment by Muchiachio** [comment]
Could you share a repro? Because it somehow works on that page :)

**Comment by Dallas411** [comment]
Now works fine! Jquery problem.

Sorry

M

Da: Muchiachio [mailto:notifications@github.com]
Inviato: venerdì 28 aprile 2017 16:45
A: NonFactors/MVC5.Grid <MVC5.Grid@noreply.github.com>
Cc: Marco Dalla Libera <marco@dallalibera.net>; Author <author@noreply.github.com>
Oggetto: Re: [NonFactors/MVC5.Grid] Pageable does not work (#83)


Could you share a repro? Because it somehow works on that page :)
