### ISSUE TITLE
change grid.cshtml file name

### ISSUE THREAD

**Issue by sai30** [NonFactors/MVC5.Grid#84]
Hi,

Can I know where is `_Grid.cshtml` file getting called. Can i change the name of this file?

Thanks in advance!

**Comment by Muchiachio** [comment]
[Here's](http://mvc-grid.azurewebsites.net/Grid/Partial) example on that.

**Comment by sai30** [comment]
I renamed _Grid.cshtml to _MyGrid.cshtml and made the change mentioned above. It is saying net::ERR_CONNECTION_RESET in console and grid is not getting loaded. Am i missing anything?

**Comment by Muchiachio** [comment]
I would not recommend touching or renaming the grid's content at all.
You should use your own new partials and then tell the grid to use them if you need to change generated html.
