### ISSUE TITLE
Search not working in arabic letters

### ISSUE THREAD

**Issue by samihatuka** [NonFactors/MVC5.Grid#85]
I have a problem with global search with arabic letters in internet explorer (works in chrome)
Thanks

**Comment by Muchiachio** [comment]
It's a known issue in IE. But it can work, if you encode your input value
```JS
$('.mvc-grid').mvcgrid({
    query: 'search=' + encodeURIComponent(this.value),
    reload: true
});
```

**Comment by samihatuka** [comment]
Great! Thanks
