### ISSUE TITLE
Master-detail capability: Reload with different sourceUrl

### ISSUE THREAD

**Issue by grammophone** [NonFactors/MVC5.Grid#86]
Hello,

First, thank you for the best grid for ASP.NET MVC, in my opinion.

I worked out a fully AJAX-enabled master-detail scenario where a selection in master grid shows a details grid. The existing code has all the inner workings to allow an elegant approach like:

``$("#detailsContainer .mvc-grid").mvcgrid({
  reload: true,
  sourceUrl: newDetailsUrl
});``

The sourceUrl field is already supported for initial loading, so i just enabled it for reloading as well by adding a single line in mvc-grid.js, inside the MvcGrid.set method (line 113 in the original file):

``grid.sourceUrl = options.sourceUrl || grid.sourceUrl;``

You might think this is a useful capability for allowing easy master-detail work, avoiding more complex solutions.

Thank you,

-emmanuel

**Comment by Muchiachio** [comment]
Yes, it should work in theory. I will just check one more time to see if it doesn't have any side effects.
