### ISSUE TITLE
Does ASP NET dropdownlist triggers to NonFactors.MVC5 Grid?

### ISSUE THREAD

**Issue by keremburak** [NonFactors/MVC5.Grid#87]
Hi,

This grid is so cool.
I have a scneario. There is a HTML Helper dropdownlist on my page. And when I choose an item from dropdown then I want to list items in NonFactors.MVC5 Grid. 

Is there any example about that scenario? Could you give me a hand for this? 

Kerem

**Comment by Muchiachio** [comment]
You can use global search [example](http://mvc-grid.azurewebsites.net/Grid/GlobalSearch) as a starting point on reloading grid with selected dropdown value.

**Comment by keremburak** [comment]
Thanks
