### ISSUE TITLE
Paging footer disappear when rows-per-page more than maximum rows

### ISSUE THREAD

**Issue by diehard27** [NonFactors/MVC5.Grid#88]
in SelectableRowsPerPage when Grid-Rows dropdown higher than maximum rows, Page footer will gone.

[http://mvc-grid.azurewebsites.net/Pager/SelectableRowsPerPage?Grid-Page=1&Grid-Rows=20](http://mvc-grid.azurewebsites.net/Pager/SelectableRowsPerPage?Grid-Page=1&Grid-Rows=20)

**Comment by Muchiachio** [comment]
Yes, this is by design. If you don't have more pages, you don't really need a pager.
