### ISSUE TITLE
How to use ViewModel for a grid.

### ISSUE THREAD

**Issue by diehard27** [NonFactors/MVC5.Grid#89]
I try to user viewmodel in order to show multiple view in same grid (number of student register to an activity). But compilor show error "CS0411: The type arguments for method 'NonFactors.Mvc.Grid.MvcGridExtensions.Grid<T>(System.Web.Mvc.HtmlHelper, System.Collections.Generic.IEnumerable<T>)' cannot be inferred from the usage. Try specifying the type arguments explicitly."
Do you have any sample code for this problem?
Thank you for your suggestion.

```
Model Activity
   
        public string ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual ICollection<ActivityRegister> ActivityRegisters { get; set; }



Model ActivityRegister
        public string ActivityID { get; set; }
        public string StudentID { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual Student Student { get; set; }

ViewModel ActivityIndexData
public class ActivityIndexData
    {
        public IEnumerable<Activity> Activities { get; set; }
        public IEnumerable<ActivityRegister> ActivityRegisteres { get; set; }
        public IEnumerable<Student> Students { get; set; }
    }
} 

Controller
  public ActionResult Index()
        {
           var viewModel = new ActivityIndexData();
            viewModel.Activities = db.Activities.Include(a => a.ActivityCategory).OrderByDescending(a => a.ID);
            return View(viewModel);
         }


View Index.html
@model IEnumerable<ARUSARS.Models.ActivityIndexData>
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Activity.Name);
        columns.Add(model => model.ActivityRegister.Count);
    })
    .Pageable(pager =>
    {
        pager.PartialViewName = "_PagerWithRows";
        pager.RowsPerPage = 20;
    })
    .Sortable()
    .Filterable()
)

```

**Comment by Muchiachio** [comment]
This seems like a stackoverflow question.

**Comment by mkchmiel** [comment]
Hate to agree with Muchiachio.

Never the less I have a suggestion, under your .Grid(Model) in the view, are you sure its Model and not Model. Something?

**Comment by Muchiachio** [comment]
It's `Model.Something` if you have a model structured like that, same as mvc helpers.
It could be any of these
```
@Html.HiddenFor(model => model)
@Html.HiddenFor(model => model.Keys)
@Html.HiddenFor(model => model.Key.Values)
```
Same with grid
```
@Html.Grid(Model)
@Html.HiddenFor(Model.Keys)
@Html.HiddenFor(Model.Key.Values)
```
It depends where you are holding your grid values.

**Comment by Muchiachio** [comment]
@mkchmiel I actually mistook you for @diehard27 :smile:

**Comment by mkchmiel** [comment]
Hehe its fine, your answer is spot on.

**Comment by diehard27** [comment]
I found [this](https://www.codeproject.com/Articles/1043977/Mapping-ViewModel-to-Model-in-ASP-NET-MVC-using-Im) that make my code dry.

Thank you for you attention.
