### ISSUE TITLE
Mixing c# code and html in a column

### ISSUE THREAD

**Issue by weblaik** [NonFactors/MVC5.Grid#91]
Hi,
is it possible to write a column like this:

```
columns.Add().Encoded(false)
.Titled("Roles")
.RenderValueAs(d =>
	@<div style="text-align: left;">
               <ul>
		@foreach (var role in d.Roles.OrderBy(r => r.Description)) {
		       <li>@role.Description</li>
		}
               </ul>
	</div>);
```

If not, could you add this feature?
Thank you!
Sergio

**Comment by Muchiachio** [comment]
Yes, it's possible, here's a few different ways you could do this:
- an extension or a function which returns rendered values
- concat descriptions, using linq's `Aggregate` function
- write a razor helper.

**Comment by Muchiachio** [comment]
Did you managed to render your column?

**Comment by weblaik** [comment]
Yes, I wrote a razor helper. 
But I don't like this solution because I can't cover easily every situation (mixing foreach, if and other statements).
Thanks

**Comment by Muchiachio** [comment]
Well, it's a language constraints for writing lambdas, so not much we can do.
