### ISSUE TITLE
Html.ActionLink not working correctly

### ISSUE THREAD

**Issue by retthom** [NonFactors/MVC5.Grid#92]
Hi

Trying to get the Html.ActionLink to work.  Not having any luck.

**Code:**
`columns.Add(model => "<a class=data-modal="">" + Html.ActionLink("Edit", "Edit", "ProductDescription", new { productNumber = model.Product_Number }, null) + "<a/>");`

**Result:**

> `<a data-modal><a href="/ProductDescription/Edit?productNumber=8275">Edit</a><a/>`

****I try an example from issue #11**** 

`columns.Add(model => "<a class='data-modal' href='" + Url.Action("Edit", "ProductDescription", new { productNumber = model.Product_Number }) + "'><i class='fa fa-info'>Edit</i></a>");`

**Same result:**

`<a class='data-modal' href='/ProductDescription/Edit?productNumber=8275'><i class='fa fa-info'></i></a>`

**Comment by retthom** [comment]
Found the problem.  I need to add "Edit" between <i>.

`columns.Add(model => "<a class='data-modal' href='" + Url.Action("Edit", "ProductDescription", new { productNumber = model.Product_Number }) + "'><i class='fa fa-info'>Edit</i></a>");`

**Comment by tanojsaipraveen** [comment]
columns.Add(model => Html.ActionLink("Edit", "Edit", new { id = model.Username }));
