### ISSUE TITLE
Between Filters

### ISSUE THREAD

**Issue by mstfatmc** [NonFactors/MVC5.Grid#95]
Hello there

Can you add a between filter for the date type, please?

**Comment by Muchiachio** [comment]
Its already available by using `.Multifilterable(Boolean)` option. You can find an example [here](http://mvc-grid.azurewebsites.net/Grid/MultiFiltering).

**Comment by Muchiachio** [comment]
Is that's what you wanted?

**Comment by mstfatmc** [comment]
Yes thats it
Thank you very much
________________________________
Gönderen: Aldis Rameika <notifications@github.com>
Gönderildi: 7 Temmuz 2017 Cuma 18:21:07
Kime: NonFactors/MVC5.Grid
Bilgi: mstfatmc; Author
Konu: Re: [NonFactors/MVC5.Grid] Between Filters (#95)


Is that's what you wanted?

**Comment by mstfatmc** [comment]
Thank you so much
________________________________
Gönderen: Muchiachio <notifications@github.com>
Gönderildi: 5 Temmuz 2017 Çarşamba 18:53:58
Kime: NonFactors/MVC5.Grid
Bilgi: mstfatmc; Author
Konu: Re: [NonFactors/MVC5.Grid] Between Filters (#95)


Its already available by using .Multifilterable(Boolean) option. You can find an example here<http://mvc-grid.azurewebsites.net/Grid/MultiFiltering>.
