### ISSUE TITLE
Virtual Scrolling

### ISSUE THREAD

**Issue by jsaraiva7** [NonFactors/MVC5.Grid#96]
Hello, 
First of all, let me congrat you for the great job you have done!
After searching for a while i finally settled with your grid. 

As a feature/question, 
Is it possible to implement Virtual scrolling, instead of paging?
Thanks. 
Keep up the good work!

**Comment by Muchiachio** [comment]
Yes, in theory it's possible, but it's currently unpractical to do with the current implementation.

**Comment by jsaraiva7** [comment]
Hi, 
Ok. i will see if i can come up with something. 
I saw a few examples doing it on clientside with default mvc grid, and javascript fetching the data as required. i will try to do it. 

Thanks.
