### ISSUE TITLE
How to do thumbnails & sparklines in the gridview

### ISSUE THREAD

**Issue by weedkiller** [NonFactors/MVC5.Grid#97]
Hello,
love the grid, have some ideas and help please

How can we do 
1) Thumbnails [views](http://www.vandelaydesign.com/list-grid-view-switch/)
2) display micro-charts like sparklines inside a grid
![image](https://user-images.githubusercontent.com/21086190/28127308-10b651b6-66fa-11e7-9972-b355f2cf2339.png)
3) mini-mapbox /leaflet with hyperlinks

Thanks

**Comment by Muchiachio** [comment]
Everything should be achievable with html as column value, you can see an example [here](http://mvc-grid.azurewebsites.net/Column/Encoding).

**Comment by Muchiachio** [comment]
Did it help @weedkiller?
