### ISSUE TITLE
Manual Paging in MVC5.Grid Nuget Package

### ISSUE THREAD

**Issue by jjkcharles** [NonFactors/MVC5.Grid#98]
Hi,

Can you please let me know when would commit [960023449b2decc9e1a27260e33bbaa27212b13d](https://github.com/NonFactors/MVC5.Grid/commit/960023449b2decc9e1a27260e33bbaa27212b13d)  make its way into the Nuget package. I see, the package is currently in version 3.4.0, and the last update it has received was back in Nov 2016.

**Comment by Muchiachio** [comment]
I finished everything I had in my own backlog, the only issue left is #81.
I will try to do or reject that feature this week, so you can expect a release on 23rd.

**Comment by jjkcharles** [comment]
Thanks for the update.

One more question. (I haven't looked at the code completely on how filters work, but just wondering based on what I see in the changeset, so this could end up being an absurd question!)

Wouldn't enabling Manual Paging have a conflict with that of other column Filters?

For instance, l have a page size of 10, and current page number is 2. In this case, my Data access layer would be returning 10 rows that are supposed to be in the 2nd page. Now, when Grid applies the filters to it, the results are not one would want it to be, as the filtering is applied only to the data set returned by the data access layer (which is already a subset of the actual unfiltered data).

**Comment by Muchiachio** [comment]
Good point, didn't thought about that.
However manual paging would mainly be used for hand made queries which can't be casted back to a proper `IQueryable` with query generating `IQueryable.Provider`. So grid filtering would only work on in-memory collection, which most likely won't be desired and therefore not used.

So to summarize
- if you can use filtering you can use automatic paging
- if you can't use automatic paging you probably can't use filtering either

**Comment by jjkcharles** [comment]
That's what I thought too. 

I feel that, it would be nice to place a restriction to prevent such conflicting usage or throw an obvious error message saying that two incompatible features are currently turned on in the Grid. This is to make the developer aware of what is happening, rather than him/her spending time to figure out why filtering isn't working as it should.

On a side note, when manual paging is enabled, it is not fair for the developer to lose the entire Filtering capabilities. There should be a way to extend the code, so that a custom filter can be implemented in the Data Access Layer which can be plugged into the Grid.

**Comment by Muchiachio** [comment]
Well filtering is not turned off, it just works on in-memory collection, instead of changing the query we know nothing about. And current column and filter implementation can already be extended to support hand made queries. What we usually do for hand written queries is wrap them with a queryable provider which understands properties being mapped and can wrap original query with any filter/sort/page expression as needed.

**Comment by jjkcharles** [comment]
Ah, ok. Can you please provide me with a sample implementation for custom filters implemented using Queryable prvoviders, or point me to the appropriate page in http://mvc-grid.azurewebsites.net if it is already available.

**Comment by Muchiachio** [comment]
Queryable provider uses expression trees to convert C# code to query like syntax, examples on how to create an expression tree filter can be found in the grid's [filtering source](https://github.com/NonFactors/MVC5.Grid/tree/cfca7a85e38b669a470f50eb642a46fb25440339/src/Mvc.Grid.Core/Filtering). And [this](http://mvc-grid.azurewebsites.net/Filter/Register) is a full example.

As for query providers, we are reusing database specific ones from their respective packages. EF provides SQL server one, postgres, oracle and other ones usually come from nuget packages. They do need some glue code (given there is no context for the model metadata), but it's doable.

**Comment by jjkcharles** [comment]
This would still do the filtering off the in-memory collection right, and, not really benefit  in cases where the Data layer is not able to return an IQueryable type.

The scenario I am talking about is, where the Data layer cannot return IQueryable (say for instance, a Web Service written in a different non-.Net language), and both paging/filtering needs to be done manually by passing the paging/filtering criteria to the service.

**Comment by Muchiachio** [comment]
No, you would be returning a query, which then can be wrapped with any filtering needed.

It could look something like this

```C#
public ActionResult Index()
{
    var rawQuery = db.Query("SELECT name, surname FROM people GROUP 1, 2");
    IQueryable<Person> peopleQuery = new DbContextProvider.To<Person>(rawQuery).AsQueryable();

    return View(peopleQuery);
}
```
